In [1]:
import pandas as pd
from utilities.preprocessors import preprocess, assign_gender, series_to_1D_array, construct_embedding_dict, construct_embedding_matrix
from utilities.visualizers import view_rows
from utilities.loaders import load_file
from models.fil_lstm_glove import load_lstm_model

import os
from dotenv import load_dotenv
from pathlib import Path

%load_ext autoreload
%autoreload 2

# Load dataframe

In [2]:
conn_info = pd.read_csv('../documents/conn_info.csv', index_col=0)
conn_info

,email,mobile_no,company_name,conn_link,conn_name,gender,salutation
0,paulinomarcus2914@gmail.com,0,Dyson · Full-time,https://www.linkedin.com/in/paulinomarcus/,Marcus Paulino,male,NaN
1,jhericksid15@gmail.com,09294383786 (Home),Cielo Talent · Full-time,https://www.linkedin.com/in/jhericksid/,Jherick Sid Celestial,male,NaN
2,EvanJake.Montano@libertymutual.com,+639260328119 (Mobile),Tata Consultancy Services · Full-time,https://www.linkedin.com/in/evanjakesorianomon...,Evan Jake Soriano Montano,male,NaN
3,capiorheg@gmail.com,0,JBW Managed Services and Consulting Corp · Ful...,https://www.linkedin.com/in/reggielee-capio-a4...,Reggielee Capio,male,NaN
4,johncarlotadeo18@gmail.com,+639432681245 (Mobile),Trojan Recruitment Group · Full-time,https://www.linkedin.com/in/john-carlo-tadeo-2...,John Carlo Tadeo,male,NaN
...,...,...,...,...,...,...,...
1065,NaN,0,transcosmos Asia Philippines Inc. · Full-time,https://www.linkedin.com/in/jamie-rose-cleofas...,Jamie Rose Cleofas,NaN,NaN
1066,jovitfrias@gmail.com,0,RCM Health Care Services · Full-time,https://www.linkedin.com/in/jovit-frias-06a561...,Jovit Frias,NaN,NaN
1067,danlopezatwork@gmail.com,0,Abacus Service Corporation · Full-time,https://www.linkedin.com/in/danlopezprofessional/,Mark Daniel Lopez,NaN,NaN
1068,dmrc_06@yahoo.com,09983696222 (Mobile),RingCentral · Full-time,https://www.linkedin.com/in/daena-michaela-roy...,Daena Michaela Ceria,NaN,NaN
1069,reyes.joanamace10@gmail.com,09672 182668 (Mobile),iQor Philippines,https://www.linkedin.com/in/joana-mace-reyes-b...,Joana Mace Reyes,NaN,NaN

In [3]:
conn_info['gender'].unique()

array(['male', 'female', nan], dtype=object)

In [4]:
# what I want to do is if there are names that have more than 1 first name e.g.
# Jherick and Sid, we want to train a classifier that classifies these individual
# names and output its probability and then average these two probabilities to get
# the final probability of whether it is male or female name
# i.e. Jherick has prob 0.75732 of being positive label Sid has prob of 0.6343 of
# being a positive label the average of this would be 0.69581 which would be a postive
# label, wee can assign the positive label 1 to a male label and the negative label 0
# would be female
conn_info['conn_name'].apply(lambda name: name.split() if not pd.isna(name) else name)

0                    [Marcus, Paulino]
1            [Jherick, Sid, Celestial]
2       [Evan, Jake, Soriano, Montano]
3                   [Reggielee, Capio]
4                 [John, Carlo, Tadeo]
                     ...
1065            [Jamie, Rose, Cleofas]
1066                    [Jovit, Frias]
1067             [Mark, Daniel, Lopez]
1068          [Daena, Michaela, Ceria]
1069              [Joana, Mace, Reyes]
Name: conn_name, Length: 1070, dtype: object

# Loading libraries for gender classifier

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow import one_hot

# Loading dataset for gender classifier

In [6]:
name_gender_df = pd.read_csv('./data/name_gender_dataset.csv')
name_gender_df

           Name Gender    Count   Probability
0         James      M  5304407  1.451679e-02
1          John      M  5260831  1.439753e-02
2        Robert      M  4970386  1.360266e-02
3       Michael      M  4579950  1.253414e-02
4       William      M  4226608  1.156713e-02
...         ...    ...      ...           ...
147264   Zylenn      M        1  2.736740e-09
147265   Zymeon      M        1  2.736740e-09
147266   Zyndel      M        1  2.736740e-09
147267   Zyshan      M        1  2.736740e-09
147268    Zyton      M        1  2.736740e-09

[147269 rows x 4 columns]

In [7]:
name_gender_df['Gender'].value_counts()

Gender
F    89749
M    57520
Name: count, dtype: int64

#### 0 for male 1 for female

In [8]:
name_gender_df['Gender'] = name_gender_df['Gender'].apply(lambda label: 0 if label == 'M' else 1)
name_gender_df['Gender'].value_counts()

Gender
1    89749
0    57520
Name: count, dtype: int64

In [9]:
# split into training and testing
X_trains, X_tests, Y_trains, Y_tests = train_test_split(name_gender_df['Name'], name_gender_df['Gender'], test_size=0.2, random_state=0)
X_trains

2853        Kamden
143300       Qiang
111302    Evthokia
27499       Tasean
84175     Elysiana
            ...
41993       Adryel
97639       Caydan
95939     Sturgill
117952     Breonny
43567       Kinjal
Name: Name, Length: 117815, dtype: object

#### dataset indicates a slight imbalance therefore it may be useful to use AUC and F1 as a metric rather than accuracy

In [10]:
# what we should do is encode each name we have into a numerical value
unique_train_names = X_trains.unique().tolist()
unique_train_names

['Kamden',
 'Qiang',
 'Evthokia',
 'Tasean',
 'Elysiana',
 'Vermon',
 'Zaylem',
 'Kuiam',
 'Konesha',
 'Jayga',
 'Ark',
 'Evelin',
 'Termaine',
 'Debraca',
 'Georgiane',
 'Rebbekah',
 'Martene',
 'Dianni',
 'Lyric',
 'Panithi',
 'Joanny',
 'Ivory',
 'Brindle',
 'Akai',
 'Koa',
 'Yosniel',
 'Huldah',
 'Ireri',
 'Amanoa',
 'Tsung-Wei',
 'Tosca',
 'Zander',
 'Didier',
 'Shacara',
 'Mariah-Lee',
 'Amiella',
 'Khushpreet',
 'Shauna-Ann',
 'Babram',
 'Kornell',
 'Catessa',
 'Izah',
 'Treisha',
 'Kidae',
 'Corlis',
 'Alana-Jade',
 'Edsil',
 'Arleyah',
 'Boe',
 'Sehreen',
 'Hareshwar',
 'Josiahh',
 'Liberti',
 'Devahn',
 'Lyra',
 'Sirach',
 'Maki',
 'Danieljames',
 'Maezy',
 'Rea',
 'Michaile',
 'Guinette',
 'Ezequias',
 'Creztinez',
 'Khrystina',
 'Bhagwana',
 'Kanyon',
 'Nicharon',
 'Deamontae',
 'Zeilah',
 'Hemi-Alex',
 'Skyelar',
 'Rorik',
 'Mave',
 'Niya',
 'Rawen',
 'Popi',
 'Toya',
 'Azeeza',
 'Uniquia',
 'Trager',
 'Emin',
 'Amarah',
 'Maomi',
 'Jemeria',
 'Shanrell',
 'Anjani',
 'Jahaven',
 'Deonica',
 'Anaunziatina',
 'Clydine',
 'Charnette',
 'Briana',
 'Flosie',
 'Lexyee',
 'Kinnie',
 'Marry',
 'Tekiesha',
 'Zenus',
 'Raul',
 'Jerilee',
 'Chanise',
 'Elisabetta',
 'Cortland',
 'Rayansh',
 'Kemar',
 'Zakaria',
 'Birklee',
 'Josif',
 'Nagee',
 'Avory',
 'Metra',
 'Veril',
 'Olisha',
 'Hallett',
 'Leonnie',
 'Dayln',
 'Amanpreet',
 'Quamain',
 'Kastiel',
 'Akoya',
 'Marinda',
 'Cereniti',
 'Piers',
 'Lizzett',
 'Joeph',
 'Gahnshyam',
 'Chares',
 'Aarom',
 'Olivia-Jane',
 'Jeannine',
 'Airyn',
 'Karletta',
 'Caleen',
 'Maddie',
 'Tykese',
 'Chantrear',
 'Aureus',
 'Junee',
 'Kem',
 'Doretha',
 'Kazu',
 'Chinedu',
 'Salvadore',
 'Ricardo',
 'Sahajdeep',
 'Arlynne',
 'Camaya',
 'Harjas',
 'Dennison',
 'Gracyn',
 'Susan-Jade',
 'Warrine',
 'Yuxuan',
 'Phoebie',
 'Daison',
 'Earsie',
 'Juwan',
 'Drevaughn',
 'Girolamina',
 'Benji-Terrence',
 'Merleen',
 'Oen',
 'Sewit',
 'Wandalee',
 'Edye',
 'Rishaank',
 'Simrat',
 'Kynndal',
 'Willowdean',
 'Asunta',
 'Teneka',
 'Katiria',
 'Lashay',
 'Berrett',
 'Dafna',
 'Georffrey',
 'Haniah',
 'Jakalan',
 'Cecillia',
 'Nev',
 'Euva',
 'Riliegh',
 'Granger',
 'Nurbi',
 'Osyris',
 'Corneliu-Ioan',
 'Aviyon',
 'Yolaunda',
 'Sahri',
 'Arfan',
 'Velda',
 'Milanie',
 'Jatana',
 'Aylissa',
 'Tanealle',
 'Zara-Jay',
 'Tranel',
 'Maimouna',
 'Akyia-Destiny',
 'Jymere',
 'Ryan',
 'Birger',
 'Camrun',
 'Ralf-Peter',
 'Ylli',
 'Ronee',
 'Yuan',
 'Jaketa',
 'Nitara',
 'Ikea',
 'Makynleigh',
 'Aaleiyah',
 'Bartola',
 'Arvey',
 'Hawanya',
 'Eviee',
 'Amandra',
 'Kensli',
 'Dajanay',
 'Amelio',
 'Payal',
 'Daleelah',
 'Delyn',
 'Kasten',
 'Tommie',
 'Arryonna',
 'Vaira-Baiba',
 'Cohlton',
 'Dibanhi',
 'Tamiaya',
 'Breda',
 'Welty',
 'Marietta',
 'Larrry',
 'Zyariah',
 'Diari',
 'Cherrish',
 'Toshiye',
 'Kellie-Louise',
 'Ainsley',
 'Nazibuneesha',
 'Maklin',
 'Francelina',
 'Quinnly',
 'Storey',
 'Joyell',
 'Ahalia',
 'Olvie',
 'Obrian',
 'Derya',
 'Dija',
 'Ayrabella',
 'Dianalee',
 'Lagreta',
 'Rabekah',
 'Zakhari',
 'Tyah',
 'Iphigene',
 'Maysam',
 'Iras',
 'Caseylynn',
 'Mckinzi',
 'Kiaya',
 'Kmles',
 'Furnell',
 'Joxiel',
 'Salih',
 'Roseleigh',
 'Fama',
 'Kamere',
 'Ryken',
 'Ailis',
 'Bronda',
 'Nicklous',
 'Tralaina',
 'Jacquez',
 'Charlottie',
 'Shirrel',
 'Dashone',
 'Malaz',
 'Welda',
 'Jovan',
 'Dashae',
 'Pancho',
 'Sinncere',
 'Terreance',
 'Johnathyn',
 "Jo'Anne",
 'Ameer',
 'Jasani',
 'Reel',
 'Tyrece',
 'Srinija',
 'Areliz',
 'Myreta',
 'Adara',
 'Juref',
 'Jarvez',
 'Sharrelle',
 'Alanaha',
 'Kaedyn',
 'Cordarrell',
 'Kelseyanne',
 'Jakeob',
 'Narendera',
 'Kynnsley',
 'Damariye',
 'Orietta',
 'Keiston',
 'Mikal',
 'Keiaira',
 'Samayia',
 'Zandar',
 'Tyler-Braidyn',
 'Solanus',
 'Mischell',
 'Lavonn',
 'Jaser',
 'Thorval',
 'Takeko',
 'Coutney',
 'Sarom',
 'Neylah',
 'Jazzleen',
 'Jerious',
 'Calloway',
 'Englas',
 'Darae',
 'Chevea',
 'Marselino',
 'Fumiyo',
 'Dahana',
 'Dystany',
 'Dakai',
 'Christie-Anne',
 'Shirilee',
 'Veska',
 'Anahy',
 'Gordan',
 'Tyris',
 'Sumaiyya',
 'Raymell',
 'Lyndsay',
 'Zamarien',
 'Bern',
 'Emmaleah',
 'Jadiel',
 'Cassell',
 'Matok',
 'Arasele',
 'Avo',
 'Kersty',
 'Solan',
 'Topeka',
 'Vikarm',
 'Kurstie',
 'Anarckis',
 'Kiari',
 'Fernando',
 'Zyreion',
 'Lueann',
 'Kelseyann',
 'Lyyrle',
 'Chadley',
 'Hajrah',
 'Alexis',
 'Tishea',
 'Chappla',
 'Vandna',
 'Chyara',
 'Daxxon',
 'Mixtli',
 'Christina-Rosa',
 'Lizette',
 'Emonii',
 'Bolish',
 'Jennett',
 'Selisha',
 'Paratibha',
 'Haflidi',
 'Kiayne',
 'Alazah',
 'Jiyanna',
 'Cardi',
 'Sayeda',
 "Leeonora'E",
 'Jayni',
 'Hayoon',
 'Shaquoya',
 'Niklaus',
 'Ovaline',
 'Chericka',
 'Roggie',
 'Elleshia',
 'Ishman',
 'Rosswell',
 'Icsis',
 'Vibhav',
 'Aubreonna',
 'Darleen',
 'Jackthomas',
 'Ashlund',
 'Johnna',
 'Shyanne',
 'Aijha',
 'Loralie',
 'Enjamin',
 'Addysan',
 'Joydeep',
 'Shariece',
 'Aarhon',
 'Serica',
 'Yelonda',
 'Sing',
 'Cherese',
 'Marli-Rose',
 'Nyall',
 'Manju',
 'Nashara',
 'Ceyda',
 'Kordarius',
 'Donevan',
 'Klhoe',
 'Maari',
 'Wolodimir',
 'Basam',
 'Zaylyn',
 'Darry-Lisa',
 'Gianluka',
 'Aliczia',
 'Runan',
 'Rossalynd',
 'Decker',
 'Kortne',
 'Airlie-Jaye',
 'Liang',
 'Girja',
 'Savonia',
 'Zepher',
 'Ledra',
 'Daniela',
 'Joslene',
 'Palmyra',
 'Nute',
 'Addeline',
 'Aker',
 'Rosellen',
 'Quinlen',
 'Oktavia',
 'Regen',
 'Deyanara',
 'Haleigh',
 'Davine',
 'Kelise',
 'Arkadi',
 'Jirah',
 'Bulqis',
 'Rutherford',
 'Declyn',
 'Daquavion',
 'Lota',
 'Jaeliana',
 'Shermain',
 'Manka',
 'Mardie',
 'Rosezell',
 'Shalayna',
 'Walace',
 'Dharini',
 'Farley',
 'Kabi',
 'Manisha',
 'Simone-Steva',
 'Yaden',
 'Cerjio',
 'Eutycus',
 'Child',
 'Smithie',
 'Hela',
 'Kendrys',
 'Rahme',
 'Aleja',
 'Swanika',
 'Jackey',
 'Hermia',
 'Oya',
 'Delima',
 'Donzel',
 'Astraia',
 'Shi-Ann',
 'Ajana',
 'Martika',
 'Daneja',
 'Alarie',
 'Waford',
 'Nickolette',
 'Orfhlaith',
 'Harliv',
 'Pasqalino',
 'Mawada',
 'Jayelin',
 'Laporche',
 'Wazdi',
 'Janeia',
 'Kaylyne',
 'Delrene',
 'Iboja',
 'Ariano',
 'Murle',
 'Erling',
 'Nekedra',
 'Bailynn',
 'Shwanna',
 'Anthonyjoseph',
 'Ursla',
 'Khaesahn',
 'Emeree',
 'Vilinda',
 'Leiu',
 'Eu-Jin',
 'Premo',
 'Adeoluwa',
 'Rael',
 'Dusten',
 'Cazna',
 'Bentleigh',
 'Chrles',
 'Fatih',
 'Antoinese',
 'Aleisha',
 'Kout',
 'Kalman',
 'Taleka',
 'Jahsier',
 'Satoko',
 'Kaile',
 'Samaire',
 'Chrishelle',
 'Cion',
 'Sabriya',
 'Lakshana',
 'Kylene',
 'Chantz',
 'Dominquie',
 'Derralee',
 'Joretha',
 'Tylah-James',
 'Kymesha',
 'Shonell',
 'Geetha',
 'Valire',
 'Wakenda',
 'Dorthea',
 'Rouen',
 'Kalep',
 'Lakima',
 'Tekeema',
 'Rithika',
 'Jamara',
 'Nissan',
 'Tayvionna',
 'Geanine',
 'Hagan',
 'Mekka',
 'Elovie',
 'Danijah',
 'Kyahlin',
 'Ebani',
 'Vaadi',
 'Omri',
 'Giobani',
 'Siraj',
 'Lyden',
 'Meisha',
 'Deanya',
 'Charlis',
 'Artur',
 'Araon',
 'Kashlyn',
 'Raylein',
 'Valorie',
 'Zandah',
 'Endy',
 'Mckaylin',
 'Burtie',
 'Harmanpreet',
 'Makyra',
 'Tierany',
 'Marieo',
 'Vaniyah',
 'Dallyn',
 'Jaylyn',
 'Jonoah',
 'Kichirou',
 'Natha',
 'Kalayla',
 'Joelle',
 'Hemant@Teeku',
 'Gorgonio',
 'Pasquale',
 'Ishya',
 'Milie',
 'Orlanda',
 'Drish',
 'Sumedha',
 'Javell',
 'Khaysan',
 'Cemil',
 'Marrisa',
 'Marlecia',
 'Mychal',
 'Ameliah-Rose',
 'Lani',
 'Rhonesha',
 'Aissata',
 'Kieyha',
 'Ladarrien',
 'Zacery',
 'Raelin',
 'Saania',
 'Trell',
 'Jerrianna',
 'Hanu',
 'Aireonna',
 'Nuzia',
 'Qing',
 'Peggy-Lee',
 'Shaindel',
 'Jia-Yi',
 'Rhodayna',
 'Porcher',
 'Bowyn',
 'Delrita',
 'Kelsa',
 'Panayoula',
 'Celeene',
 'Priah',
 'Stefin',
 'Eva',
 'Carilon',
 'Rozelle',
 'Darna',
 'Minh-Tuan',
 'Dannely',
 'Murline',
 'Arcenio',
 'Jessalynne',
 'Juliam',
 'Linita',
 'Sagit',
 'Bernida',
 'Kalino',
 'Emberleigh',
 'Jamescia',
 'Clellie',
 'Sharrae',
 'Esveidy',
 'Tiffney',
 'Katherynn',
 'Tarry',
 'Gwendalynn',
 'Zyliyah',
 'Sharlise',
 'Makina',
 'Mingyi',
 'Dimetrios',
 'Ahmeir',
 'Yaribel',
 'Shamise',
 'Inga',
 'Rhemi',
 'Suhayb',
 'Lamarrion',
 'Birame',
 'Tyger',
 'Irfa',
 'Clements',
 'Laketta',
 'Hineawatea',
 'Carlo',
 'Precious',
 'Michla',
 'Abilyn',
 'Saturnino',
 'Mereki-Le',
 'Kinyin',
 'Yarissa',
 'Sonn',
 'Ngan',
 'Tahli-Jade',
 'Marien',
 'Kayliee',
 'Issael',
 'Sheenah',
 'Phillipa',
 'Jaeya',
 'Pressley',
 'Pahola',
 'Kevinmichael',
 'Kaedan',
 'Pravin',
 'Mark-Herbert',
 'Kingjames',
 'Leeasia',
 'Claritsa',
 'Shykeim',
 'Aabriella',
 'Kimiko',
 'Anquinetta',
 'Florisa',
 'Meilarn',
 'Tammecka',
 'Elyssa-Kate',
 'Sharocka',
 'Tarick',
 'Jhye',
 'Amyiah',
 'Mashael',
 'Jizzel',
 'Martika-Carla',
 'Vraj',
 'Anganette',
 'Curley',
 'Teagun',
 'Morodok',
 'Elliard',
 'Vanessa-Lee',
 'Kimika',
 'Rennick',
 'Cerrissa',
 'Kamorra',
 'Tiawana',
 'Jo-Anna',
 'Jeremyiah',
 'Erani',
 'Odessa',
 'Elijahjohn',
 'Monik',
 'Shabreen',
 'Kacey',
 'Joesha',
 'Kashad',
 'Mariadelrosario',
 'Shavon',
 'Mekala',
 'Eladio',
 'Yachira',
 'Marcos',
 'Harue',
 'Dacota',
 'Bojana',
 'Lapriest',
 'Zalie',
 'Gyanender',
 'Madylynn',
 'Chyleen',
 'Anello',
 'Aryav',
 'Kazi',
 'Chenequa',
 'Hien',
 'Thoralf',
 'Isioma',
 'Zymeer',
 'Cheramie',
 'Hawo',
 'Ibarhim',
 'Yaremy',
 'Charmi',
 'Sinit',
 'Audrene',
 'Bivian',
 'Joshia',
 'Gurmit',
 'Markkus',
 'Shymia',
 'Lario',
 'Raiph',
 'Jaykay',
 'Carl-Heinz',
 'Tina-Maria',
 'Deede',
 'Glennisha',
 "Onike'",
 'Javonna',
 'Kohl',
 'Gavriele',
 'Epsie',
 'Raby',
 'Jori',
 'Kiyomi',
 'Anjeli',
 'Reetima',
 'Solveig',
 'Clois',
 'Arlana',
 'Tyron',
 'Sandro',
 'Maoriella',
 'Dayanah',
 'Joplin',
 'Timmeka',
 'Halei',
 'Tellie',
 'Meshach',
 'Genesi',
 'Yamelin',
 'Ricquel',
 'Verlyn',
 'Kyrsta',
 'Kynna',
 'Sbeidy',
 'Denyel',
 'Deronte',
 'Alisse',
 'Roshanne',
 'Darragh',
 'Hubart',
 'Tahjah',
 'Gloyd',
 'Vanella',
 'Knoxlee',
 'Marly',
 'Omyra',
 'Godofredo',
 'Byrle',
 'Zealan',
 'Lylh',
 'Mawatta',
 'Tahlea',
 'Clomer',
 'Rolin',
 'Asimelia',
 'Zi',
 'Serach',
 'Halfred',
 'Tresor',
 'Shaekyrah',
 'Brandeis',
 'Pelligrino',
 'Ahijah',
 'Amanda-Jaine',
 'Janell',
 'Jonatthan',
 'Allee',
 'Siraaj',
 'Oebe',
 'Jainab',
 'Valari',
 'Satyvrat',
 'Sahba',
 'Presciliano',
 'Ondria',
 'Shayah',
 'Redinald',
 'Malaysia',
 'France',
 'Jon-Luc',
 'Bonny',
 'Coralynne',
 'Karmani',
 'Charrelle',
 'Khamora',
 'Maclane',
 'Sacia',
 'Nilza',
 'Gionny',
 'Nykell',
 'Nikul',
 'Damorian',
 'Nagela',
 'Dejanay',
 'Julanja',
 'Travia',
 'Kyona',
 'Juliano',
 'Parminder',
 'Dzemal',
 'Tkaiya',
 'Jakab',
 'Naquon',
 'Kenzy',
 'Toledo',
 'Darwood',
 'Courtney-Lee',
 'Yasemin',
 'Savannahmarie',
 'Darielis',
 'Bair',
 'Vicki-Luz',
 'Keyshana',
 'Tangerine',
 'Corderall',
 'Roane',
 'Nikkiah',
 'Lakiea',
 'Nyiesha',
 'Draevyn',
 'Adhem',
 'Mahbub',
 'Taimur',
 'Arko',
 'Hadil',
 'Gabryel',
 'Layane',
 'Navgun',
 'Shastelin',
 'Myleene',
 'Ruthellen',
 'Narcisco',
 'Kagen',
 'Graceleigh',
 'Beniamin',
 'Tayvian',
 'Sifa',
 'Reinaldo',
 'Zira',
 'Sarayha',
 'Kee',
 'Katlan',
 'Jeaneth',
 'Marcelle',
 'Lanaeya',
 'Burkleigh',
 'Oreen',
 'Viaansh',
 'Adrin',
 'Charlyn',
 'Itzayana',
 'Mazel',
 'Irine',
 'Arlenne',
 'Frita',
 'Tomoaki',
 'Ja',
 'Annuziato',
 'Coulton',
 'Jenesia',
 'Leaster',
 'Cathalina',
 'Den',
 'Evely',
 'Suwa',
 'Marylinn',
 'Yekaterina',
 'Ta-Liya',
 'Stacy',
 'Azarya',
 'Jadarrius',
 'Sonni',
 'Derrick',
 'Tesneem',
 'Keyontay',
 'Neton',
 'Zmnako',
 'Dhara',
 'Gabrieljohn',
 'Sanjiv',
 'Dunte',
 'Aniso',
 'Selman',
 'Ameliarose',
 'Suhasini',
 'Cayse',
 'Keithia',
 'Shavonte',
 'Reinardo',
 'Ohn',
 'Hepzibah',
 'Welby',
 'Nissah',
 'Darrin',
 'Charelle',
 'Alyster',
 'Shylynn',
 'Navay',
 'Corradino',
 'Damaris-Lucy',
 'Mircle',
 'Roshika',
 'Adryan',
 'Lockie',
 'Yuveraj',
 'Alyka',
 'Abraham',
 'Chiya',
 'Broni',
 'Alonte',
 'Amber-Rose',
 'Rook',
 'Archelle',
 'Clayvon',
 'Sahaan',
 'Lafayette',
 'Amandy',
 'Worner',
 'Makyla',
 'Naylea',
 'Joquavious',
 ...]

In [11]:
# what we should do is encode each name we have into a numerical value
unique_test_names = X_tests.unique().tolist()
unique_test_names

['Hans-Christian',
 'Dilhan',
 'Zohar',
 'Myrl',
 'Broadie',
 'Sitta',
 'Duyen',
 'Nesaru',
 'Xeormenas',
 'Bauer',
 'Xamiyah',
 'Euella',
 'Racheale',
 'Yazmyn',
 'Yamille',
 'Lillie',
 'Siyuri',
 'Wylee',
 'Larod',
 'Ashalee',
 'Amaryah',
 'Doyla',
 'Kearstyn',
 'Esprit',
 'Heber',
 'Aszure',
 'Tyki',
 'Summerlynn',
 'Versal',
 'Seiko',
 'Shawntai',
 'Rehaazvir',
 'Carlson',
 'Loreita',
 'Noriah',
 'Sienna-Jai',
 'Shelvrene',
 'Ganajah',
 'Xaida',
 'Reather',
 'Myrella',
 'Krsevan',
 'Demorea',
 'Crisslyn',
 'Michilu',
 'Syliss',
 'Keisha',
 'Gino-Carlo',
 'Billijean',
 'Chalonda',
 'Shakeeka',
 'Kola',
 'Arthalia',
 'Eraclis',
 'Leinaala',
 'Lynley',
 'Addylin',
 'Cerinity',
 'Tassie',
 'Bersain',
 'Julysa',
 'Kaillou',
 'Paolo-Nino',
 'Shawntasia',
 'Adam',
 'Guisepina',
 'Merrick',
 'Margena',
 'Buck',
 'Karmandeep',
 'Aliyyah',
 'Aisha',
 'Gemma',
 'Taviana',
 'Katherine',
 'Reynna',
 'Talyssa',
 'Hakar',
 'Constant',
 'Vice',
 'Chadsten',
 'Demi-Rose',
 'Czeslow',
 'Staffon',
 'Randll',
 'Kamelah',
 'Litsa',
 'Sherneice',
 'Luevenia',
 'Pietra',
 'Khloe',
 'Jceion',
 'Deshun',
 'Stefan',
 'Zasiah',
 'Yeleini',
 'Ncole',
 'Nayarit',
 'Bavly',
 'Miloö',
 'Jovane',
 'Xanthus',
 'Ksharmra',
 'Katravia',
 'Mysha',
 'Asdrubal',
 'Ajju',
 'Zakoda',
 'Sylvain',
 'Mahjenta',
 'Baileigh',
 'Ronel',
 'Arlus',
 'Manon',
 'Cadia',
 'Abdollah',
 'Bernd',
 'Walley',
 'Kylaya',
 'Suchada',
 'Evannie',
 'Yoshikatsu',
 'Arvo',
 'Adon',
 'Jaykwon',
 'Mckynzee',
 'Miliyah',
 'Kaiya',
 'Anndria',
 'Marco-Antonio',
 'Ashyiah',
 'Arreh',
 'Clesson',
 'Aliziah',
 'Marquiez',
 'Jaisnav',
 'Jerrell',
 'Trayven',
 'Helaine',
 'Warna',
 'Demetria',
 'Mauriella',
 'Breslin',
 'Pariti',
 'Jemeeka',
 'Shanvika',
 'Aoibh',
 'Bhateri',
 'Aderonke',
 'Emrynn',
 'Orme',
 'David-James',
 'Joanelle',
 'Hannahrose',
 'Foolmaya',
 'Mckayle',
 'Chinh',
 'Eashaan',
 'Sokuntheavy',
 'Cathie-Anne',
 'Roa',
 'Rashita',
 'Beyounce',
 'Daniellemarie',
 'Ryanpaul',
 'Tyshai',
 'Cosette',
 'Elsbieta',
 'Sanquetta',
 'Dimitty',
 'Nubia',
 'Cuyler',
 'Anupriya',
 'David-John',
 'Brayce',
 'Lavares',
 'Kandys',
 'Gholam',
 'Fredrika',
 'Rinukanwr',
 'Dud',
 'Gershon',
 'Donnalou',
 'Summa-Asha',
 'Sunayana',
 'Elveda',
 'Makedde',
 'Luster',
 'Nanola',
 'Aphra',
 'Berwick',
 'Virlan',
 'Reinis',
 'Saurish',
 'Kristan',
 'Kaviyon',
 'Johnnisha',
 'Brenan',
 'Adrenna',
 'Stylianos',
 'Kohlten',
 'Jaxson',
 'Rittany',
 'Anjeev',
 'Xiclali',
 'Meshayla',
 'Lutisha',
 'Barellda',
 'Jeniva',
 'Themetrios',
 'Makhy',
 'Duewa',
 'Fiadh',
 'Adaira',
 'Cletta',
 'Gurubaksh',
 'Taneca',
 'Georgia-Skye',
 'Jenson',
 'Riquelme',
 'Juanice',
 'Wesner',
 'Ritamae',
 'Latanya',
 'Sinan',
 'Shukveer',
 'Rickesha',
 'Donovan',
 'Cheyanah',
 'Zahir',
 'Soreya',
 'Onnalee',
 'Terrae',
 'Branigan',
 'Veeksha',
 'Emelyn',
 'Lashe',
 'Rhen',
 'Rodricus',
 'Jvon',
 'Warnell',
 'Meilani',
 'Caralee',
 'Litta',
 'Vitus',
 'Naveena',
 'Destined',
 'Ladavid',
 'Raffie',
 'Savahanna',
 'Hilbert',
 'Walton',
 'Willey',
 'Rayvon',
 'Fateh',
 'Johnnesha',
 'Lajavion',
 'Caral',
 'Marlese',
 'Heatherlyn',
 'Inaara',
 'Grazio',
 'Shatonna',
 'Tengyuan',
 'Rohsaan',
 'Darrian',
 'Teshayla',
 'Kirijai',
 'Eyvonne',
 'Roneka',
 'Jerray',
 'Sheryee',
 'Jannel',
 'Makkiyah',
 'Jamnaa',
 'For',
 'Celette',
 'Teonte',
 'Taviyon',
 'Pawnee',
 'Ryuki',
 'Semmie',
 'Reiner',
 'Fiorina',
 'Atlas',
 'Shaylor',
 'Deshanon',
 'Shantrice',
 'Mealea',
 'Freida',
 'Tarnay',
 'Katyanna',
 'Zahari',
 'Karoleena',
 'Ibrahim',
 'Ocelotl',
 'Siew',
 'Diaz',
 'Duriyah',
 'Miryea',
 'Nikkole',
 'Stefone',
 'Daisylynn',
 'Rheese',
 'Geumtian',
 'Fresh',
 'Katavia',
 'Raydyn',
 'Gwenivere',
 'Kin',
 'Sulay',
 'Konar',
 'Lisajean',
 'Avelyn',
 'Ashlie',
 'Jourdynn',
 'Harsanjh',
 'Shylow',
 'Treniyah',
 'Sunbeam',
 'Adriyanna',
 'Ravnoor',
 'Dajour',
 'Prisches',
 'Anterria',
 'Chastity',
 'Tuhlee',
 'Lagatha',
 'Sierra',
 'Ashawna',
 'Curran',
 'Tionne',
 'Floy',
 'Anouk',
 'Shelby-Louise',
 'Makynsie',
 'Khama',
 'Vivalea',
 'Macaden',
 'Jyonna',
 'Sarah-Lise',
 'Elliyanah',
 'Betheny',
 'Tysne',
 'Asraa',
 'Macoy',
 'Jamayel',
 'Kaci',
 'Jaboree',
 'Leelynn',
 'Braylie',
 'Kyriakoyla',
 'Keiaha',
 'Jot',
 'Liesbeth',
 'Jonchristopher',
 'Yusaf',
 'Rosalie',
 'Jaylond',
 'Brandylee',
 'Rhegan',
 'Keyarnah',
 'Paytin',
 'Belinda',
 'Siebert',
 'Basile',
 'Prabjot',
 'Kolbey',
 'Nazly',
 'Dustyn',
 'Dierdra',
 'Matai',
 'Shauni',
 'Zackrey',
 'Sophery',
 'Eliahs',
 'Galyn',
 'Gordana',
 'Leyton',
 'Joshniel',
 'Chiron',
 'Iliah-Marie',
 'Emogine',
 'Jiyaan',
 'Kobi',
 'Jeffreys',
 'Keland',
 'Andrew-Gert',
 'Berris',
 'Laquaysha',
 'James-Tiller',
 'Margerita',
 'Alekzandr',
 'Sakir',
 'Hansi',
 'Norita',
 'Camas',
 'Lisamarie',
 'Rishikesh',
 'Yuheng',
 'Adae',
 'Kaylah',
 'Hamsiran',
 'Lamoni',
 'Lakessa',
 'Chiniqua',
 'George-Eric',
 'Miroslow',
 'Ariagrace',
 'Creedence',
 'Markia',
 'Naledi',
 'Cristalo',
 'Giannetta',
 'Eather',
 'Poon-Jin',
 'Kyliegh',
 'Dyaire',
 'Darniesha',
 'Mishka',
 'Nithila',
 'Briceyda',
 'Mat…O',
 'Nalya',
 'Evanelle',
 'Muneerah',
 'Efimia',
 'Arrington',
 'Gara',
 'Norma',
 'Keeley-Marie',
 'Juliska',
 'Adeng',
 'Kysin',
 'Ranyiah',
 'Dakora',
 'Dylan-Douglas',
 'Malysa',
 'Francell',
 'Marieli',
 'Rakeria',
 'Wissam',
 'Jiaire',
 'Cadon',
 'Arlo',
 'Aurin',
 'Zikra',
 'Tumika',
 'Lashea',
 'Matiya',
 'Bresha',
 'Sylbia',
 'Raidyn',
 'Jamonta',
 'Jarrah',
 'Shakeyla',
 'Kendricka',
 'Julean',
 'Kairi-Lea',
 'Jayme-Lea',
 'Chnada',
 'Gessica',
 'Keandrea',
 'Tobie',
 'Hermanus',
 'Vaneza',
 'Anazia',
 'Steel',
 'Raheem',
 'Laylamarie',
 'Airam',
 'Seleina',
 'Adrec',
 'Anandu',
 'Tyionna',
 'Fidelis',
 'Priyam',
 'Cesar',
 'Quineka',
 'Wonder',
 'Tahneisha',
 'Emmeri',
 'Markiea',
 'Jabes',
 'Terrylee',
 'Amyah',
 'Sarah',
 'Eraste',
 'Reanda',
 'Kaliannah',
 'Shig',
 'Milisia',
 'Kelley',
 'Ataja',
 'Kirlira',
 'Ralen',
 'Colsyn',
 'Lene',
 'Alray',
 'Kwok',
 'Lorenia',
 'Modestina',
 'Devion',
 'Kai',
 'Clarion',
 'Kyleigh',
 'Ishank',
 'Chrystel',
 'Jacie',
 'Chesney',
 'Sheldon',
 'Zaveyar',
 'Ketch',
 'Khiv',
 'Alameda',
 'Arling',
 'Kraige',
 'Britnie',
 'Torria',
 'Parmood',
 'Modelle',
 'Toribia',
 'Kastoori',
 'Jeeyoung',
 'Pourya',
 'Tierah',
 'Tammey',
 'Amaia',
 'Christinna',
 'Ayashia',
 'Laxmanram',
 'Cherianne',
 'Dyane',
 'Nigar',
 'Shanais',
 'Rhyli',
 'Atif',
 'Steffani',
 'Tobby-Aaron',
 'Monelle',
 'Farrell',
 'Beltra',
 'Yazira',
 'Araya',
 'Muktar',
 'Notnamed',
 'Everleen',
 'Cylas',
 'Kherul',
 'Keiana',
 'Terrea',
 'Jaleigh',
 'Valle',
 'Llesenia',
 'Navendra',
 'Kalouda',
 'Micah',
 'Harjass',
 'Zakhiya',
 'Tagen',
 'Seanda',
 'Salesh',
 'Brayn',
 'Barbara',
 'Rekisha',
 'Monteia',
 'Garren',
 'Ezer',
 'Srisai',
 'Fabiha',
 'Vrigorio',
 'Karisa',
 'Precella',
 'Jermont',
 'Alanda',
 'Zenovia',
 'Teela',
 'Trayshawn',
 'Holt',
 'Harjeevan',
 'Emmani',
 'Adaire',
 'Rebbeca',
 'Mccrae',
 'Areege',
 'Jaivik',
 'Lirim',
 'Joji',
 'Neeven',
 'Sikke',
 'Erasmo',
 'Su-Ellen',
 'Elshodov',
 'Yeyetzi',
 'Zykevious',
 'Enqi',
 'Lachyna',
 'Unkar',
 'Jayliyah',
 'Shean',
 'Leonidus',
 'Ajaypal',
 'Bravery',
 'Purlie',
 'Xiah',
 'Summa-Ray',
 'Shantya',
 'Elijio',
 'Mendy',
 'Collis',
 'Karagen',
 'Cigi',
 'Alinka',
 'Marrack',
 'Cataliyah',
 'Colt',
 'Dash',
 'Vivian',
 'Jenny-Lynne',
 'Ala',
 'Yathziri',
 'Yitong',
 'Targ',
 'Shauntoria',
 'Rosale',
 'Franchezco',
 'Joni-Marie',
 'Joston',
 'Hammed',
 'Rever',
 'Leilonie',
 'Eshwari',
 'Virgean',
 'Sokadah-Chanthyra',
 'Josedaniel',
 'Felix',
 'Karolyne',
 'Aahil',
 'Aleksei',
 'Kirti',
 'Maxan',
 'Desi-Marie',
 'Taelour',
 'Yani',
 'Kakteka',
 'Rajvi',
 'Myriana',
 'Jaijairam',
 'Rainn',
 'Latefah',
 'Courteney',
 'Keeya',
 'Zon',
 'Leightyn',
 'Guyann',
 'Shadel',
 'Carleah',
 'Azaelia',
 'Nona',
 'Gardner',
 'Ruskin',
 'Brenah-May',
 'Wajih',
 'Ibadat',
 'Games',
 'Shahnee',
 'Eathin',
 'Brighid',
 'Raffela',
 'Halid',
 'Margotte',
 'Thrisha',
 'Jayvaun',
 'Achuoth',
 'Kaveona',
 'Xyon',
 'Maddalen',
 'Yosmairy',
 'Tassanne',
 'Kabal',
 'Jonquil',
 'Gayel',
 'Gizelle',
 'Frank-Cono',
 'Jakiya',
 'Ailet',
 'Annaalicia',
 'Kenmari',
 'Nionila',
 'Adrianjames',
 'Dia',
 'Rijwan',
 'Yohannus',
 'Jinette',
 'Sebatian',
 'Ekram',
 'Hulises',
 'Cacee',
 'Kessandra',
 'Amiryah',
 'Roselee',
 'Han',
 'Taureon',
 'Ziham',
 'Chaslyn',
 'Dasamnoor',
 'Deveron',
 'Haralambo',
 'Aspenn',
 'Deseree',
 'Thrisa',
 'Zaarkacha',
 'Zilin',
 'Thianna',
 'Tamie',
 'Cheriann',
 'Kasheena',
 'Milt',
 'Mattia',
 'Jaimii-Lee',
 'Tracyann',
 'Elahnore',
 'Kaylisa',
 'Jamall',
 'Chuba',
 'Mille',
 'Presley',
 'Jetlyn',
 'Tonyah-Rose',
 'Sireena',
 'Shyona',
 'Jennadene',
 'Nazmuslam',
 'Waverly',
 'Adollorata',
 'Salu',
 'Ifteshyam',
 'Taien',
 'Jakyan',
 'Allayne',
 'Remedios',
 'Deiveon',
 'Ancika',
 'Donneta',
 'Juneth',
 'Policarpio',
 'Laszlo',
 'Oved',
 'Quashawn',
 'Kiarie',
 'Ezechyel',
 'Lachelle',
 'Jakesha',
 'Joumana',
 'Edony',
 'Curtavious',
 'Dlyla',
 'Amron',
 'Chouly',
 'Filippa',
 'Garlyn',
 'Sterle',
 'Mackyle',
 'Akimi',
 'Manuelita',
 'Rupak',
 'Satia',
 'Pejman',
 'Cashe',
 'Genoveffa',
 'Andyn',
 'Minairo',
 'Pravallika',
 'Shenan',
 'Safe',
 'Graicyn',
 'Iryna',
 'Nixson',
 'Teel',
 'Shamecca',
 'Acxel',
 'Lisbet',
 'Zell',
 'Lardine',
 'Murrie',
 'Tenzi',
 'Astin',
 'Yandry',
 'Treton',
 'Kwamae',
 'Duann',
 'Matrim',
 'Saron',
 'Sharleen',
 'Lisseth',
 'Paisleigh',
 'Verle',
 'Izma',
 'Yarah',
 'Jex',
 'Irwin',
 'Ashalyn',
 'Deslynn',
 'Quenisha',
 'Leanne-Maria',
 'Cataia',
 'Erby',
 'Pratheek',
 'Tihara',
 'Justi',
 'Tyneece',
 'Jermaria',
 'Shiv',
 'Arzelia',
 'Refan',
 'Shafia',
 'Kaydin',
 'Leishla',
 'Garnetta',
 'Huxley',
 'Sonia',
 'Paulyn',
 'Angeth',
 'Roshena',
 'Tollie',
 'Krishanna',
 'Ladonda',
 'Bendu',
 'Danusia',
 'Yizhou',
 'Rhyle',
 'Shatavia',
 'Dolores',
 'Leah',
 'Kreshna',
 'Jaydurga',
 'Tuwaenganui',
 'Maecee',
 'Kianoush',
 'Skylee',
 'Taeghan',
 'Lucesita',
 'Baljinder',
 'Jedsen',
 'Daezha',
 'Ireon',
 'Song',
 'Antjuan',
 'Litzzy',
 'Kewaun',
 'Elianie',
 'Ogie',
 'Jacobi',
 'Tyonne',
 'Merrawyn',
 'Rozama',
 'Zhaoqing',
 'Daxxton',
 'Narrah',
 'Pulak',
 'Janaiah',
 'Maleesa',
 'Octavia',
 'Coy',
 'Rallie',
 'Dejahnae',
 'Dar',
 'Ovey',
 'Marjolaine',
 'Savrin',
 'Jahzion',
 'Foruq',
 'Takiyha',
 'Senn',
 'Nerissa',
 'Traisana',
 'Dainette',
 'Kendalle',
 'Colicia',
 'Javontay',
 'Brolin',
 'Kanise',
 'Delimar',
 'Dametrius',
 'Siri',
 'Abdikarim',
 'Oluwanifemi',
 'Carylon',
 'Leba',
 'Andera',
 'Damyen',
 'Saho',
 'Amanii',
 'Justina',
 'Davieon',
 'Ernice',
 'Arjeta',
 'Razim',
 'Soroosh',
 'Aaraya',
 'Ermioni',
 'Wynoma',
 'Nour',
 'Nikiki',
 'Daughn',
 'Dajua',
 'Keelia',
 'Indhira',
 'Juwayriya',
 'Chizaram',
 'Aoran',
 'Kailayah',
 'Via',
 'Perlita',
 'Fionia',
 'Nivedha',
 'Eryk',
 'Ammie',
 'Eveanna',
 'Tessa-Marie',
 'Mckenly',
 'Thorbjorn',
 'Myral',
 'Merrilly',
 'Tocha',
 'Milanni',
 'Dayson',
 'Joson',
 'Alfonza',
 'Belverly',
 'Angharad',
 'Aiven',
 'Jaydn',
 'Sabriyya',
 'Fool',
 'Mayerlin',
 'Kailha',
 'Dashanta',
 'Teres',
 'Magdolna',
 'Mayron',
 'Jenel',
 'Marjolein',
 'Nicte',
 'Daynor',
 'Thavry',
 'Savhanna',
 'Tajahnae',
 'Whittley',
 'Hollynd',
 'Keyuntae',
 'Herson',
 'Vishu',
 'Zan',
 'Stephano',
 'Cervante',
 'Manny',
 'Novisha',
 'Khameron',
 'Lonnell',
 'Damiaan',
 'Regnold',
 'Jullius',
 'Rashamel',
 'Hollylynn',
 'Vanda',
 'Antwaun',
 'Gleda',
 'Shun',
 'Jesse-James',
 'Ceretha',
 'Evin',
 'Rusti',
 'Sudesh',
 'Latrinda',
 'Vibiana',
 'Marcelles',
 'Arhiana',
 'Neraj',
 'Romio',
 'Marianth',
 'Arliss',
 'Fanniemae',
 'Sofya',
 'Shaarn',
 'Merida',
 'Duangdara',
 'Vattanveer',
 'Chandermani',
 'Yohanan',
 'Hiltje',
 'Hillory',
 'Irielle',
 'Emelye',
 'Ryana',
 'Leonora',
 'Rembrandt',
 'Kiffany',
 'Samsida',
 'Kaneki',
 ...]

In [12]:
# before joining again get array in df with longest length first
name_with_max = max(unique_train_names, key=lambda name: len(name.split('-')))
train_max_len = len(name_with_max.split('-'))
train_max_len

4

In [13]:
num_unique_train_names = len(unique_train_names)
num_unique_train_names

109292

In [14]:
num_unique_test_names = len(unique_test_names)
num_unique_test_names

28939

In [15]:
X_trains

2853        Kamden
143300       Qiang
111302    Evthokia
27499       Tasean
84175     Elysiana
            ...
41993       Adryel
97639       Caydan
95939     Sturgill
117952     Breonny
43567       Kinjal
Name: Name, Length: 117815, dtype: object

In [16]:
# omit split argument since the string column of the df is not a sentence 
# and is just a one word string which is a name
tokenizer = Tokenizer(num_words=num_unique_train_names, split=" ")
tokenizer.fit_on_texts(X_trains)

In [17]:
word_to_index = tokenizer.word_index
index_to_word = tokenizer.index_word

In [18]:
index_to_word

{1: 'lee',
 2: 'anne',
 3: 'rose',
 4: 'ann',
 5: 'marie',
 6: 'jane',
 7: 'louise',
 8: 'jade',
 9: 'maria',
 10: 'may',
 11: 'jo',
 12: 'james',
 13: 'john',
 14: 'leigh',
 15: 'anna',
 16: 'lea',
 17: 'jayne',
 18: 'mae',
 19: 'jean',
 20: 'grace',
 21: 'jay',
 22: 'kate',
 23: 'mary',
 24: 'maree',
 25: 'paul',
 26: 'joy',
 27: 'rae',
 28: 'sue',
 29: 'minh',
 30: 'lyn',
 31: 'emma',
 32: 'michelle',
 33: 'lily',
 34: 'skye',
 35: 'lisa',
 36: 'anthony',
 37: 'jae',
 38: 'kim',
 39: 'ella',
 40: 'amy',
 41: 'michael',
 42: 'smt',
 43: 'an',
 44: 'peter',
 45: 'thanh',
 46: 'anh',
 47: 'mark',
 48: 'angela',
 49: 'ruby',
 50: 'lynn',
 51: 'sarah',
 52: 'mia',
 53: 'jai',
 54: 'jayde',
 55: 'mai',
 56: 'elizabeth',
 57: 'renee',
 58: 'daniel',
 59: 'luke',
 60: 'leah',
 61: 'nicole',
 62: 'thuy',
 63: 'jaye',
 64: 'amanda',
 65: 'emily',
 66: 'ngoc',
 67: 'ellen',
 68: 'kelly',
 69: 'paige',
 70: 'andrew',
 71: 'laura',
 72: 'claire',
 73: 'hoang',
 74: 'dee',
 75: 'david',
 76: 'shae',
 77: 'billie',
 78: 'kay',
 79: 'tyler',
 80: 'jon',
 81: 'bella',
 82: 'jessie',
 83: 'sara',
 84: 'le',
 85: 'amber',
 86: 'ray',
 87: 'lou',
 88: 'joshua',
 89: 'joseph',
 90: 'jack',
 91: 'linda',
 92: 'sophie',
 93: 'jessica',
 94: 'yu',
 95: 'scott',
 96: 'hannah',
 97: 'phuong',
 98: 'linh',
 99: 'lilly',
 100: 'dean',
 101: 'george',
 102: 'olivia',
 103: 'susan',
 104: 'monique',
 105: 'eliza',
 106: 'jesse',
 107: 'amelia',
 108: 'chloe',
 109: 'jamie',
 110: 'toni',
 111: 'samantha',
 112: 'teresa',
 113: 'donna',
 114: 'li',
 115: 'su',
 116: 'tia',
 117: 'jason',
 118: 'joe',
 119: 'helen',
 120: 'william',
 121: 'kayla',
 122: 'melissa',
 123: 'hayley',
 124: 'ava',
 125: 'faye',
 126: 'thomas',
 127: 'casey',
 128: 'tara',
 129: 'thi',
 130: 'tayla',
 131: 'peta',
 132: 'sophia',
 133: 'ellie',
 134: 'han',
 135: 'brooke',
 136: 'zoe',
 137: 'christopher',
 138: 'lucy',
 139: 'kerry',
 140: 'j',
 141: 'holly',
 142: 'joanne',
 143: 'de',
 144: 'te',
 145: 'tracy',
 146: 'benjamin',
 147: 'billy',
 148: 'bianca',
 149: 'rebecca',
 150: 'sky',
 151: 'antonio',
 152: 'beth',
 153: 'georgia',
 154: 'chi',
 155: 'elle',
 156: 'nicholas',
 157: 'deborah',
 158: 'aimee',
 159: 'dan',
 160: 'krystal',
 161: 'leanne',
 162: 'vicki',
 163: 'kylie',
 164: 'thien',
 165: 'kaye',
 166: 'duy',
 167: 'jordan',
 168: 'taylor',
 169: 'kerri',
 170: 'robert',
 171: 'lara',
 172: 'felicity',
 173: 'ana',
 174: 'sally',
 175: 'bonnie',
 176: 'huy',
 177: 'bree',
 178: 'rita',
 179: 'cody',
 180: 'kara',
 181: 'ashley',
 182: 'anita',
 183: 'alexandra',
 184: 'kym',
 185: 'chelsea',
 186: 'belinda',
 187: 'alex',
 188: 'rosa',
 189: 'eva',
 190: 'tina',
 191: 'cassandra',
 192: 'trung',
 193: 'patrick',
 194: 'ashlee',
 195: 'ruth',
 196: 'karen',
 197: 'my',
 198: 'nguyen',
 199: 'van',
 200: 'adam',
 201: 'hong',
 202: 'ashleigh',
 203: 'charlie',
 204: 'katie',
 205: 'wayne',
 206: 'heidi',
 207: 'jenna',
 208: 'kristy',
 209: 'dawn',
 210: 'cheryl',
 211: 'alice',
 212: 'megan',
 213: 'patricia',
 214: 'tracey',
 215: 'cindy',
 216: 'yen',
 217: 'beau',
 218: 'steven',
 219: 'jenny',
 220: 'kai',
 221: 'frank',
 222: 'dylan',
 223: 'wendy',
 224: 'jasmine',
 225: 'faith',
 226: 'julia',
 227: 'ryan',
 228: 'kiara',
 229: 'madison',
 230: 'crystal',
 231: 'aurora',
 232: 'nadia',
 233: 'naomi',
 234: 'daisy',
 235: 'jennifer',
 236: 'debra',
 237: 'isabella',
 238: 'ivy',
 239: 'tanya',
 240: 'vinh',
 241: 'ross',
 242: 'jacob',
 243: 'charlotte',
 244: 'jan',
 245: 'shane',
 246: 'robyn',
 247: 'bich',
 248: 'natasha',
 249: 'paolo',
 250: 'hope',
 251: 'shannon',
 252: 'marc',
 253: 'aaron',
 254: 'thu',
 255: 'carol',
 256: 'kathy',
 257: 'evie',
 258: 'kasey',
 259: 'paula',
 260: 'alexander',
 261: 'mohd',
 262: 'jodi',
 263: 'jake',
 264: 'lorraine',
 265: 'eve',
 266: 'thao',
 267: 'charlee',
 268: 'alicia',
 269: 'shay',
 270: 'lynda',
 271: 'tiffany',
 272: 'kellie',
 273: 'alexis',
 274: 'yi',
 275: 'courtney',
 276: 'kelli',
 277: 'fay',
 278: 'rikki',
 279: 'sian',
 280: 'charles',
 281: 'melanie',
 282: 'jacqueline',
 283: 'corey',
 284: 'serena',
 285: 'yee',
 286: 'kerrie',
 287: 'mei',
 288: 'bradley',
 289: 'hai',
 290: 'willow',
 291: 'demi',
 292: 'brayden',
 293: 'tamara',
 294: 'vi',
 295: 'lesley',
 296: 'jodie',
 297: 'adrian',
 298: 'matthew',
 299: 'lan',
 300: 'danielle',
 301: 'elise',
 302: 'huynh',
 303: 'natalie',
 304: 'tiana',
 305: 'terri',
 306: 'sienna',
 307: 'sheree',
 308: 'edward',
 309: 'stephanie',
 310: 'vu',
 311: 'indi',
 312: 'tyson',
 313: 'betty',
 314: 'michaela',
 315: 'cherie',
 316: 'elena',
 317: 'riley',
 318: 'deanna',
 319: 'vy',
 320: 'xuan',
 321: 'craig',
 322: 'ha',
 323: 'nhu',
 324: 'gia',
 325: 'sharon',
 326: 'noah',
 327: 'samuel',
 328: 'kira',
 329: 'yan',
 330: 'bobby',
 331: 'maddison',
 332: 'arna',
 333: 'andrea',
 334: 'dinh',
 335: 'la',
 336: 'abdul',
 337: 'alana',
 338: 'christina',
 339: 'simone',
 340: 'carla',
 341: 'tai',
 342: 'lin',
 343: 'abbey',
 344: 'nhi',
 345: 'kyra',
 346: 'claudia',
 347: 'thai',
 348: 'caroline',
 349: 'antony',
 350: 'karl',
 351: 'kirstie',
 352: 'kirsty',
 353: 'annette',
 354: 'lynne',
 355: 'tran',
 356: 'ebony',
 357: 'louisa',
 358: 'belle',
 359: 'sean',
 360: 'min',
 361: 'sasha',
 362: 'ricky',
 363: 'micheal',
 364: 'shari',
 365: 'elisabeth',
 366: 'tania',
 367: 'lucia',
 368: 'fiona',
 369: 'roberto',
 370: 'pamela',
 371: 'antonia',
 372: 'harmony',
 373: 'debbie',
 374: 'stacey',
 375: 'hanna',
 376: 'erin',
 377: 'summer',
 378: 'duc',
 379: 'el',
 380: 'gracie',
 381: 'roy',
 382: 'vicky',
 383: 'kane',
 384: 'renae',
 385: 'sonia',
 386: 'nam',
 387: 'monu',
 388: 'tammy',
 389: 'julie',
 390: 'phi',
 391: 'lachlan',
 392: 'tu',
 393: 'laila',
 394: 'clare',
 395: 'layla',
 396: 'chantelle',
 397: 'junior',
 398: 'celeste',
 399: 'cassie',
 400: 'truc',
 401: 'brodie',
 402: 'ty',
 403: 'margaret',
 404: 'alyssa',
 405: 'stephen',
 406: 'mari',
 407: 'wei',
 408: 'zara',
 409: 'daniela',
 410: 'ngan',
 411: 'vanessa',
 412: 'hien',
 413: 'zi',
 414: 'therese',
 415: 'kathryn',
 416: 'nina',
 417: 'hans',
 418: 'brigitte',
 419: 'sherie',
 420: 'blake',
 421: 'caitlin',
 422: 'annie',
 423: 'diana',
 424: 'pierre',
 425: 'joyce',
 426: 'kristi',
 427: 'yasmin',
 428: 'rachel',
 429: 'jose',
 430: 'suzanne',
 431: 'angel',
 432: 'pooja',
 433: 'tony',
 434: 'josephine',
 435: 'rene',
 436: 'joel',
 437: 'shayne',
 438: 'lu',
 439: 'tian',
 440: 'lena',
 441: 'lilli',
 442: 'roger',
 443: 'long',
 444: 'janet',
 445: 'tamika',
 446: 'pia',
 447: 'joan',
 448: 'huyen',
 449: 'jody',
 450: 'ash',
 451: 'christine',
 452: 'harper',
 453: 'melinda',
 454: 'leo',
 455: 'kaylee',
 456: 'lloyd',
 457: 'antoni',
 458: 'bo',
 459: 'asha',
 460: 'taylah',
 461: 'leesa',
 462: 'carmen',
 463: 'maya',
 464: 'lillie',
 465: 'di',
 466: 'lauren',
 467: 'quang',
 468: 'brittany',
 469: 'sandra',
 470: 'patrizia',
 471: 'harley',
 472: 'khoa',
 473: 'leila',
 474: 'levi',
 475: 'huong',
 476: 'amie',
 477: 'bailey',
 478: 'hieu',
 479: 'ly',
 480: 'thy',
 481: 'oliver',
 482: 'jayden',
 483: 'poppy',
 484: 'ku',
 485: 'zhen',
 486: 'hao',
 487: 'mollie',
 488: 'hung',
 489: 'tonia',
 490: 'barbara',
 491: 'francesco',
 492: 'richard',
 493: 'harry',
 494: 'jackson',
 495: 'madeline',
 496: 'daniele',
 497: 'kyle',
 498: 'april',
 499: 'khanh',
 500: 'glenn',
 501: 'alyce',
 502: 'damien',
 503: 'jen',
 504: 'md',
 505: 'luca',
 506: 'veronica',
 507: 'diem',
 508: 'trinity',
 509: 'louis',
 510: 'rachael',
 511: 'gabrielle',
 512: 'katherine',
 513: 'judy',
 514: 'tahlia',
 515: 'shanna',
 516: 'kristie',
 517: 'kristen',
 518: 'trent',
 519: 'simon',
 520: 'lucas',
 521: 'en',
 522: 'shai',
 523: 'josie',
 524: 'danni',
 525: 'andreas',
 526: 'nathan',
 527: 'bao',
 528: 'cara',
 529: 'xi',
 530: 'ling',
 531: 'brandon',
 532: 'esther',
 533: 'quynh',
 534: 'mariah',
 535: 'jin',
 536: 'tuan',
 537: 'tyron',
 538: 'jaine',
 539: 'luc',
 540: 'ja',
 541: 'cathy',
 542: 'dianne',
 543: 'sharna',
 544: 'phu',
 545: 'hayden',
 546: 'san',
 547: 'eric',
 548: 'christian',
 549: 'o',
 550: 'abby',
 551: 'p',
 552: 'molly',
 553: 'kevin',
 554: 'bobbi',
 555: 'joanna',
 556: 'arne',
 557: 'cosimo',
 558: 'sharni',
 559: 'ida',
 560: 'star',
 561: 'stevie',
 562: 'viet',
 563: 'aria',
 564: 'hua',
 565: 'toby',
 566: 'sheri',
 567: 'mathew',
 568: 'jenni',
 569: 'francesca',
 570: 'teri',
 571: 'andre',
 572: 'nicky',
 573: 'franco',
 574: 'jaime',
 575: 'juliet',
 576: 'carly',
 577: 'elsie',
 578: 'erica',
 579: 'aaliyah',
 580: 'sonya',
 581: 'nikki',
 582: 'marree',
 583: 'gian',
 584: 'mira',
 585: 'natalia',
 586: 'brie',
 587: 'danny',
 588: 'soo',
 589: 'denise',
 590: 'june',
 591: 'liana',
 592: 'montana',
 593: 'holli',
 594: 'marco',
 595: 'trudy',
 596: 'monica',
 597: 'gaye',
 598: 'radha',
 599: 'sofia',
 600: 'ben',
 601: 'ying',
 602: 'dang',
 603: 'judith',
 604: 'timothy',
 605: 'theresa',
 606: 'lana',
 607: 'km',
 608: 'lacey',
 609: 'kelsey',
 610: 'liza',
 611: 'jaide',
 612: 'ken',
 613: 'lam',
 614: 'luis',
 615: 'michele',
 616: 'nikita',
 617: 'jayda',
 618: 'max',
 619: 'inge',
 620: 'tegan',
 621: 'becky',
 622: 'jacinta',
 623: 'tri',
 624: 'jaymee',
 625: 'vincent',
 626: 'bernadette',
 627: 'eden',
 628: 'willem',
 629: 'tuyet',
 630: 'indiana',
 631: 'sang',
 632: 'mya',
 633: 'violet',
 634: 'mario',
 635: 'alan',
 636: 'bethany',
 637: 'hazel',
 638: 'alisha',
 639: 'young',
 640: 'sherri',
 641: 'sha',
 642: 'penny',
 643: 'quoc',
 644: 'aubree',
 645: 'lei',
 646: 'francis',
 647: 'jayme',
 648: 'phoebe',
 649: 'marina',
 650: 'marija',
 651: 'ali',
 652: 'shakira',
 653: 'charli',
 654: 'adriana',
 655: 'allen',
 656: 'jonathan',
 657: 'stella',
 658: 'kingsley',
 659: 'troy',
 660: 'tori',
 661: 'katy',
 662: 'scarlett',
 663: 'lawrence',
 664: 'ivan',
 665: 'brianna',
 666: 'macey',
 667: 'sung',
 668: 'karin',
 669: 'aidan',
 670: 'luan',
 671: 'kristian',
 672: 'gabriella',
 673: 'daniella',
 674: 'hailey',
 675: 'pearl',
 676: 'rainer',
 677: 'hae',
 678: 'grant',
 679: 'elsa',
 680: 'chau',
 681: 'deanne',
 682: 'yin',
 683: 'paola',
 684: 'luise',
 685: 'catherine',
 686: 'ada',
 687: 'victoria',
 688: 'savannah',
 689: 'kyla',
 690: 'brenda',
 691: 'walter',
 692: 'phong',
 693: 'a',
 694: 'barry',
 695: 'al',
 696: 'rosemary',
 697: 'todd',
 698: 'tam',
 699: 'tabitha',
 700: 'marisa',
 701: 'shauna',
 702: 'toya',
 703: 'marry',
 704: 'destiny',
 705: 'christie',
 706: 'marli',
 707: 'tylah',
 708: 'lani',
 709: 'peggy',
 710: 'amity',
 711: 'alexia',
 712: 'rai',
 713: 'katina',
 714: 'jamey',
 715: 'tyrone',
 716: 'mi',
 717: 'marley',
 718: 'phung',
 719: 'oisin',
 720: 'gemma',
 721: 'kar',
 722: 'britt',
 723: 'ti',
 724: 'rhianna',
 725: 'dennis',
 726: 'frances',
 727: 'alba',
 728: 'taya',
 729: 'mika',
 730: 'sherrie',
 731: 'elisa',
 732: 'emilie',
 733: 'marika',
 734: 'bruce',
 735: 'starr',
 736: 'elly',
 737: 'janice',
 738: 'brock',
 739: 'rickie',
 740: 'susana',
 741: 'lori',
 742: 'kendall',
 743: 'tuong',
 744: 'b',
 745: 'ami',
 746: 'lili',
 747: 'luella',
 748: 'tiger',
 749: 'krishna',
 750: 'seth',
 751: 'coco',
 752: 'sonu',
 753: 'tianna',
 754: 'ching',
 755: 'brooklyn',
 756: 'fotini',
 757: 'karly',
 758: 'joylene',
 759: 'charley',
 760: 'jeanne',
 761: 'bess',
 762: 'indie',
 763: 'frederick',
 764: 'albert',
 765: 'rosie',
 766: 'brian',
 767: 'vera',
 768: 'petra',
 769: 'giuliana',
 770: 'salvatore',
 771: 'oscar',
 772: 'johnathon',
 773: 'jaymie',
 774: 'aleksandar',
 775: 'umberto',
 776: 'lia',
 777: 'tasha',
 778: 'shara',
 779: 'nadine',
 780: 'ivanka',
 781: 'chun',
 782: 'chantal',
 783: 'mikayla',
 784: 'matilda',
 785: 'callie',
 786: 'marni',
 787: 'vikki',
 788: 'meng',
 789: 'marta',
 790: 'hui',
 791: 'thuan',
 792: 'storm',
 793: 'henry',
 794: 'ky',
 795: 'cheyenne',
 796: 'talia',
 797: 'katrina',
 798: 'rhiannon',
 799: 'gene',
 800: 'adrianna',
 801: 'cong',
 802: 'd',
 803: 'arn',
 804: 'jaimee',
 805: 'keri',
 806: 'glen',
 807: 'larissa',
 808: 'sam',
 809: 'beverly',
 810: 'jasmin',
 811: 'st',
 812: 'sheryl',
 813: 'bessie',
 814: 'justin',
 815: 'ry',
 816: 'fred',
 817: 'justine',
 818: 'kelley',
 819: 'omar',
 820: 'clarissa',
 821: 'breanna',
 822: 'erik',
 823: 'shah',
 824: 'gloria',
 825: 'helena',
 826: 'manoj',
 827: 'caterina',
 828: 'allan',
 829: 'isa',
 830: 'dakota',
 831: 'ivana',
 832: 'elijah',
 833: 'nhat',
 834: 'kaitlyn',
 835: 'gabriele',
 836: 'ralph',
 837: 'jaymes',
 838: 'elliott',
 839: 'jemma',
 840: 'jian',
 841: 'markus',
 842: 'pablo',
 843: 'maci',
 844: 'carmel',
 845: 'byron',
 846: 'laurel',
 847: 'angelique',
 848: 'morgan',
 849: 'dai',
 850: 'petar',
 851: 'ramona',
 852: 'neville',
 853: 'gay',
 854: 'khang',
 855: 'dianna',
 856: 'amal',
 857: 'tricia',
 858: 'macie',
 859: 'kha',
 860: 'connie',
 861: 'tien',
 862: 'candice',
 863: 'hoa',
 864: 'diamond',
 865: 'blaize',
 866: 'jaie',
 867: 'anastasia',
 868: 'kayden',
 869: 'thang',
 870: 'meegan',
 871: 'blu',
 872: 'tah',
 873: 'alma',
 874: 'samara',
 875: 'kirsten',
 876: 'rubi',
 877: 'ashton',
 878: 'carmela',
 879: 'sami',
 880: 'luisa',
 881: 'tae',
 882: 'irena',
 883: 'christy',
 884: 'lyla',
 885: 'trudi',
 886: 'georg',
 887: 'christa',
 888: 'jessi',
 889: 'son',
 890: 'agnes',
 891: 'shania',
 892: 'khloe',
 893: 'che',
 894: 'brenton',
 895: 'gabriel',
 896: 'brook',
 897: 'wallace',
 898: 'rosemarie',
 899: 'isla',
 900: 'cee',
 901: 'kien',
 902: 'lyndon',
 903: 'kahli',
 904: 'sarina',
 905: 'douglas',
 906: 'darren',
 907: 'archie',
 908: 'sheila',
 909: 'phuc',
 910: 'sunil',
 911: 'joey',
 912: 'payton',
 913: 'ki',
 914: 'kye',
 915: 'paris',
 916: 'tyla',
 917: 'sh',
 918: 'lucinda',
 919: 'y',
 920: 'miriam',
 921: 'jada',
 922: 'sri',
 923: 'cooper',
 924: 'pax',
 925: 'ethan',
 926: 'kobe',
 927: 'jun',
 928: 'kajal',
 929: 'haylee',
 930: 'coby',
 931: 'ho',
 932: 'dion',
 933: 'hollie',
 934: 'brody',
 935: 'chantel',
 936: 'gypsy',
 937: 'sandy',
 938: 'shea',
 939: 'darcy',
 940: 'caitlyn',
 941: 'shelley',
 942: 'noel',
 943: 'kathleen',
 944: 'yun',
 945: 'eleni',
 946: 'mina',
 947: 'ai',
 948: 'kristin',
 949: 'bang',
 950: 'jie',
 951: 'billi',
 952: 'torie',
 953: 'nicola',
 954: 'xian',
 955: 'hailie',
 956: 'khiem',
 957: 'clara',
 958: 'jaimi',
 959: 'angie',
 960: 'deng',
 961: 'carey',
 962: 'meagan',
 963: 'monika',
 964: 'addison',
 965: 'kari',
 966: 'ricki',
 967: 'anton',
 968: 'heather',
 969: 'yvonne',
 970: 'damian',
 971: 'sei',
 972: 'elias',
 973: 'lewis',
 974: 'india',
 975: 'eleanor',
 976: 'dung',
 977: 'codie',
 978: 'dieu',
 979: 'otto',
 980: 'janis',
 981: 'hang',
 982: 'theodore',
 983: 'shaylee',
 984: 'ingrid',
 985: 'georgie',
 986: 'martin',
 987: 'nikolas',
 988: 'kimberley',
 989: 'tuyen',
 990: 'torri',
 991: 'davina',
 992: 'trinh',
 993: 'bj',
 994: 'scarlet',
 995: 'harlow',
 996: 'lila',
 997: 'luna',
 998: 'raye',
 999: 'regan',
 1000: 'kae',
 ...}

In [19]:
word_to_index

{'lee': 1,
 'anne': 2,
 'rose': 3,
 'ann': 4,
 'marie': 5,
 'jane': 6,
 'louise': 7,
 'jade': 8,
 'maria': 9,
 'may': 10,
 'jo': 11,
 'james': 12,
 'john': 13,
 'leigh': 14,
 'anna': 15,
 'lea': 16,
 'jayne': 17,
 'mae': 18,
 'jean': 19,
 'grace': 20,
 'jay': 21,
 'kate': 22,
 'mary': 23,
 'maree': 24,
 'paul': 25,
 'joy': 26,
 'rae': 27,
 'sue': 28,
 'minh': 29,
 'lyn': 30,
 'emma': 31,
 'michelle': 32,
 'lily': 33,
 'skye': 34,
 'lisa': 35,
 'anthony': 36,
 'jae': 37,
 'kim': 38,
 'ella': 39,
 'amy': 40,
 'michael': 41,
 'smt': 42,
 'an': 43,
 'peter': 44,
 'thanh': 45,
 'anh': 46,
 'mark': 47,
 'angela': 48,
 'ruby': 49,
 'lynn': 50,
 'sarah': 51,
 'mia': 52,
 'jai': 53,
 'jayde': 54,
 'mai': 55,
 'elizabeth': 56,
 'renee': 57,
 'daniel': 58,
 'luke': 59,
 'leah': 60,
 'nicole': 61,
 'thuy': 62,
 'jaye': 63,
 'amanda': 64,
 'emily': 65,
 'ngoc': 66,
 'ellen': 67,
 'kelly': 68,
 'paige': 69,
 'andrew': 70,
 'laura': 71,
 'claire': 72,
 'hoang': 73,
 'dee': 74,
 'david': 75,
 'shae': 76,
 'billie': 77,
 'kay': 78,
 'tyler': 79,
 'jon': 80,
 'bella': 81,
 'jessie': 82,
 'sara': 83,
 'le': 84,
 'amber': 85,
 'ray': 86,
 'lou': 87,
 'joshua': 88,
 'joseph': 89,
 'jack': 90,
 'linda': 91,
 'sophie': 92,
 'jessica': 93,
 'yu': 94,
 'scott': 95,
 'hannah': 96,
 'phuong': 97,
 'linh': 98,
 'lilly': 99,
 'dean': 100,
 'george': 101,
 'olivia': 102,
 'susan': 103,
 'monique': 104,
 'eliza': 105,
 'jesse': 106,
 'amelia': 107,
 'chloe': 108,
 'jamie': 109,
 'toni': 110,
 'samantha': 111,
 'teresa': 112,
 'donna': 113,
 'li': 114,
 'su': 115,
 'tia': 116,
 'jason': 117,
 'joe': 118,
 'helen': 119,
 'william': 120,
 'kayla': 121,
 'melissa': 122,
 'hayley': 123,
 'ava': 124,
 'faye': 125,
 'thomas': 126,
 'casey': 127,
 'tara': 128,
 'thi': 129,
 'tayla': 130,
 'peta': 131,
 'sophia': 132,
 'ellie': 133,
 'han': 134,
 'brooke': 135,
 'zoe': 136,
 'christopher': 137,
 'lucy': 138,
 'kerry': 139,
 'j': 140,
 'holly': 141,
 'joanne': 142,
 'de': 143,
 'te': 144,
 'tracy': 145,
 'benjamin': 146,
 'billy': 147,
 'bianca': 148,
 'rebecca': 149,
 'sky': 150,
 'antonio': 151,
 'beth': 152,
 'georgia': 153,
 'chi': 154,
 'elle': 155,
 'nicholas': 156,
 'deborah': 157,
 'aimee': 158,
 'dan': 159,
 'krystal': 160,
 'leanne': 161,
 'vicki': 162,
 'kylie': 163,
 'thien': 164,
 'kaye': 165,
 'duy': 166,
 'jordan': 167,
 'taylor': 168,
 'kerri': 169,
 'robert': 170,
 'lara': 171,
 'felicity': 172,
 'ana': 173,
 'sally': 174,
 'bonnie': 175,
 'huy': 176,
 'bree': 177,
 'rita': 178,
 'cody': 179,
 'kara': 180,
 'ashley': 181,
 'anita': 182,
 'alexandra': 183,
 'kym': 184,
 'chelsea': 185,
 'belinda': 186,
 'alex': 187,
 'rosa': 188,
 'eva': 189,
 'tina': 190,
 'cassandra': 191,
 'trung': 192,
 'patrick': 193,
 'ashlee': 194,
 'ruth': 195,
 'karen': 196,
 'my': 197,
 'nguyen': 198,
 'van': 199,
 'adam': 200,
 'hong': 201,
 'ashleigh': 202,
 'charlie': 203,
 'katie': 204,
 'wayne': 205,
 'heidi': 206,
 'jenna': 207,
 'kristy': 208,
 'dawn': 209,
 'cheryl': 210,
 'alice': 211,
 'megan': 212,
 'patricia': 213,
 'tracey': 214,
 'cindy': 215,
 'yen': 216,
 'beau': 217,
 'steven': 218,
 'jenny': 219,
 'kai': 220,
 'frank': 221,
 'dylan': 222,
 'wendy': 223,
 'jasmine': 224,
 'faith': 225,
 'julia': 226,
 'ryan': 227,
 'kiara': 228,
 'madison': 229,
 'crystal': 230,
 'aurora': 231,
 'nadia': 232,
 'naomi': 233,
 'daisy': 234,
 'jennifer': 235,
 'debra': 236,
 'isabella': 237,
 'ivy': 238,
 'tanya': 239,
 'vinh': 240,
 'ross': 241,
 'jacob': 242,
 'charlotte': 243,
 'jan': 244,
 'shane': 245,
 'robyn': 246,
 'bich': 247,
 'natasha': 248,
 'paolo': 249,
 'hope': 250,
 'shannon': 251,
 'marc': 252,
 'aaron': 253,
 'thu': 254,
 'carol': 255,
 'kathy': 256,
 'evie': 257,
 'kasey': 258,
 'paula': 259,
 'alexander': 260,
 'mohd': 261,
 'jodi': 262,
 'jake': 263,
 'lorraine': 264,
 'eve': 265,
 'thao': 266,
 'charlee': 267,
 'alicia': 268,
 'shay': 269,
 'lynda': 270,
 'tiffany': 271,
 'kellie': 272,
 'alexis': 273,
 'yi': 274,
 'courtney': 275,
 'kelli': 276,
 'fay': 277,
 'rikki': 278,
 'sian': 279,
 'charles': 280,
 'melanie': 281,
 'jacqueline': 282,
 'corey': 283,
 'serena': 284,
 'yee': 285,
 'kerrie': 286,
 'mei': 287,
 'bradley': 288,
 'hai': 289,
 'willow': 290,
 'demi': 291,
 'brayden': 292,
 'tamara': 293,
 'vi': 294,
 'lesley': 295,
 'jodie': 296,
 'adrian': 297,
 'matthew': 298,
 'lan': 299,
 'danielle': 300,
 'elise': 301,
 'huynh': 302,
 'natalie': 303,
 'tiana': 304,
 'terri': 305,
 'sienna': 306,
 'sheree': 307,
 'edward': 308,
 'stephanie': 309,
 'vu': 310,
 'indi': 311,
 'tyson': 312,
 'betty': 313,
 'michaela': 314,
 'cherie': 315,
 'elena': 316,
 'riley': 317,
 'deanna': 318,
 'vy': 319,
 'xuan': 320,
 'craig': 321,
 'ha': 322,
 'nhu': 323,
 'gia': 324,
 'sharon': 325,
 'noah': 326,
 'samuel': 327,
 'kira': 328,
 'yan': 329,
 'bobby': 330,
 'maddison': 331,
 'arna': 332,
 'andrea': 333,
 'dinh': 334,
 'la': 335,
 'abdul': 336,
 'alana': 337,
 'christina': 338,
 'simone': 339,
 'carla': 340,
 'tai': 341,
 'lin': 342,
 'abbey': 343,
 'nhi': 344,
 'kyra': 345,
 'claudia': 346,
 'thai': 347,
 'caroline': 348,
 'antony': 349,
 'karl': 350,
 'kirstie': 351,
 'kirsty': 352,
 'annette': 353,
 'lynne': 354,
 'tran': 355,
 'ebony': 356,
 'louisa': 357,
 'belle': 358,
 'sean': 359,
 'min': 360,
 'sasha': 361,
 'ricky': 362,
 'micheal': 363,
 'shari': 364,
 'elisabeth': 365,
 'tania': 366,
 'lucia': 367,
 'fiona': 368,
 'roberto': 369,
 'pamela': 370,
 'antonia': 371,
 'harmony': 372,
 'debbie': 373,
 'stacey': 374,
 'hanna': 375,
 'erin': 376,
 'summer': 377,
 'duc': 378,
 'el': 379,
 'gracie': 380,
 'roy': 381,
 'vicky': 382,
 'kane': 383,
 'renae': 384,
 'sonia': 385,
 'nam': 386,
 'monu': 387,
 'tammy': 388,
 'julie': 389,
 'phi': 390,
 'lachlan': 391,
 'tu': 392,
 'laila': 393,
 'clare': 394,
 'layla': 395,
 'chantelle': 396,
 'junior': 397,
 'celeste': 398,
 'cassie': 399,
 'truc': 400,
 'brodie': 401,
 'ty': 402,
 'margaret': 403,
 'alyssa': 404,
 'stephen': 405,
 'mari': 406,
 'wei': 407,
 'zara': 408,
 'daniela': 409,
 'ngan': 410,
 'vanessa': 411,
 'hien': 412,
 'zi': 413,
 'therese': 414,
 'kathryn': 415,
 'nina': 416,
 'hans': 417,
 'brigitte': 418,
 'sherie': 419,
 'blake': 420,
 'caitlin': 421,
 'annie': 422,
 'diana': 423,
 'pierre': 424,
 'joyce': 425,
 'kristi': 426,
 'yasmin': 427,
 'rachel': 428,
 'jose': 429,
 'suzanne': 430,
 'angel': 431,
 'pooja': 432,
 'tony': 433,
 'josephine': 434,
 'rene': 435,
 'joel': 436,
 'shayne': 437,
 'lu': 438,
 'tian': 439,
 'lena': 440,
 'lilli': 441,
 'roger': 442,
 'long': 443,
 'janet': 444,
 'tamika': 445,
 'pia': 446,
 'joan': 447,
 'huyen': 448,
 'jody': 449,
 'ash': 450,
 'christine': 451,
 'harper': 452,
 'melinda': 453,
 'leo': 454,
 'kaylee': 455,
 'lloyd': 456,
 'antoni': 457,
 'bo': 458,
 'asha': 459,
 'taylah': 460,
 'leesa': 461,
 'carmen': 462,
 'maya': 463,
 'lillie': 464,
 'di': 465,
 'lauren': 466,
 'quang': 467,
 'brittany': 468,
 'sandra': 469,
 'patrizia': 470,
 'harley': 471,
 'khoa': 472,
 'leila': 473,
 'levi': 474,
 'huong': 475,
 'amie': 476,
 'bailey': 477,
 'hieu': 478,
 'ly': 479,
 'thy': 480,
 'oliver': 481,
 'jayden': 482,
 'poppy': 483,
 'ku': 484,
 'zhen': 485,
 'hao': 486,
 'mollie': 487,
 'hung': 488,
 'tonia': 489,
 'barbara': 490,
 'francesco': 491,
 'richard': 492,
 'harry': 493,
 'jackson': 494,
 'madeline': 495,
 'daniele': 496,
 'kyle': 497,
 'april': 498,
 'khanh': 499,
 'glenn': 500,
 'alyce': 501,
 'damien': 502,
 'jen': 503,
 'md': 504,
 'luca': 505,
 'veronica': 506,
 'diem': 507,
 'trinity': 508,
 'louis': 509,
 'rachael': 510,
 'gabrielle': 511,
 'katherine': 512,
 'judy': 513,
 'tahlia': 514,
 'shanna': 515,
 'kristie': 516,
 'kristen': 517,
 'trent': 518,
 'simon': 519,
 'lucas': 520,
 'en': 521,
 'shai': 522,
 'josie': 523,
 'danni': 524,
 'andreas': 525,
 'nathan': 526,
 'bao': 527,
 'cara': 528,
 'xi': 529,
 'ling': 530,
 'brandon': 531,
 'esther': 532,
 'quynh': 533,
 'mariah': 534,
 'jin': 535,
 'tuan': 536,
 'tyron': 537,
 'jaine': 538,
 'luc': 539,
 'ja': 540,
 'cathy': 541,
 'dianne': 542,
 'sharna': 543,
 'phu': 544,
 'hayden': 545,
 'san': 546,
 'eric': 547,
 'christian': 548,
 'o': 549,
 'abby': 550,
 'p': 551,
 'molly': 552,
 'kevin': 553,
 'bobbi': 554,
 'joanna': 555,
 'arne': 556,
 'cosimo': 557,
 'sharni': 558,
 'ida': 559,
 'star': 560,
 'stevie': 561,
 'viet': 562,
 'aria': 563,
 'hua': 564,
 'toby': 565,
 'sheri': 566,
 'mathew': 567,
 'jenni': 568,
 'francesca': 569,
 'teri': 570,
 'andre': 571,
 'nicky': 572,
 'franco': 573,
 'jaime': 574,
 'juliet': 575,
 'carly': 576,
 'elsie': 577,
 'erica': 578,
 'aaliyah': 579,
 'sonya': 580,
 'nikki': 581,
 'marree': 582,
 'gian': 583,
 'mira': 584,
 'natalia': 585,
 'brie': 586,
 'danny': 587,
 'soo': 588,
 'denise': 589,
 'june': 590,
 'liana': 591,
 'montana': 592,
 'holli': 593,
 'marco': 594,
 'trudy': 595,
 'monica': 596,
 'gaye': 597,
 'radha': 598,
 'sofia': 599,
 'ben': 600,
 'ying': 601,
 'dang': 602,
 'judith': 603,
 'timothy': 604,
 'theresa': 605,
 'lana': 606,
 'km': 607,
 'lacey': 608,
 'kelsey': 609,
 'liza': 610,
 'jaide': 611,
 'ken': 612,
 'lam': 613,
 'luis': 614,
 'michele': 615,
 'nikita': 616,
 'jayda': 617,
 'max': 618,
 'inge': 619,
 'tegan': 620,
 'becky': 621,
 'jacinta': 622,
 'tri': 623,
 'jaymee': 624,
 'vincent': 625,
 'bernadette': 626,
 'eden': 627,
 'willem': 628,
 'tuyet': 629,
 'indiana': 630,
 'sang': 631,
 'mya': 632,
 'violet': 633,
 'mario': 634,
 'alan': 635,
 'bethany': 636,
 'hazel': 637,
 'alisha': 638,
 'young': 639,
 'sherri': 640,
 'sha': 641,
 'penny': 642,
 'quoc': 643,
 'aubree': 644,
 'lei': 645,
 'francis': 646,
 'jayme': 647,
 'phoebe': 648,
 'marina': 649,
 'marija': 650,
 'ali': 651,
 'shakira': 652,
 'charli': 653,
 'adriana': 654,
 'allen': 655,
 'jonathan': 656,
 'stella': 657,
 'kingsley': 658,
 'troy': 659,
 'tori': 660,
 'katy': 661,
 'scarlett': 662,
 'lawrence': 663,
 'ivan': 664,
 'brianna': 665,
 'macey': 666,
 'sung': 667,
 'karin': 668,
 'aidan': 669,
 'luan': 670,
 'kristian': 671,
 'gabriella': 672,
 'daniella': 673,
 'hailey': 674,
 'pearl': 675,
 'rainer': 676,
 'hae': 677,
 'grant': 678,
 'elsa': 679,
 'chau': 680,
 'deanne': 681,
 'yin': 682,
 'paola': 683,
 'luise': 684,
 'catherine': 685,
 'ada': 686,
 'victoria': 687,
 'savannah': 688,
 'kyla': 689,
 'brenda': 690,
 'walter': 691,
 'phong': 692,
 'a': 693,
 'barry': 694,
 'al': 695,
 'rosemary': 696,
 'todd': 697,
 'tam': 698,
 'tabitha': 699,
 'marisa': 700,
 'shauna': 701,
 'toya': 702,
 'marry': 703,
 'destiny': 704,
 'christie': 705,
 'marli': 706,
 'tylah': 707,
 'lani': 708,
 'peggy': 709,
 'amity': 710,
 'alexia': 711,
 'rai': 712,
 'katina': 713,
 'jamey': 714,
 'tyrone': 715,
 'mi': 716,
 'marley': 717,
 'phung': 718,
 'oisin': 719,
 'gemma': 720,
 'kar': 721,
 'britt': 722,
 'ti': 723,
 'rhianna': 724,
 'dennis': 725,
 'frances': 726,
 'alba': 727,
 'taya': 728,
 'mika': 729,
 'sherrie': 730,
 'elisa': 731,
 'emilie': 732,
 'marika': 733,
 'bruce': 734,
 'starr': 735,
 'elly': 736,
 'janice': 737,
 'brock': 738,
 'rickie': 739,
 'susana': 740,
 'lori': 741,
 'kendall': 742,
 'tuong': 743,
 'b': 744,
 'ami': 745,
 'lili': 746,
 'luella': 747,
 'tiger': 748,
 'krishna': 749,
 'seth': 750,
 'coco': 751,
 'sonu': 752,
 'tianna': 753,
 'ching': 754,
 'brooklyn': 755,
 'fotini': 756,
 'karly': 757,
 'joylene': 758,
 'charley': 759,
 'jeanne': 760,
 'bess': 761,
 'indie': 762,
 'frederick': 763,
 'albert': 764,
 'rosie': 765,
 'brian': 766,
 'vera': 767,
 'petra': 768,
 'giuliana': 769,
 'salvatore': 770,
 'oscar': 771,
 'johnathon': 772,
 'jaymie': 773,
 'aleksandar': 774,
 'umberto': 775,
 'lia': 776,
 'tasha': 777,
 'shara': 778,
 'nadine': 779,
 'ivanka': 780,
 'chun': 781,
 'chantal': 782,
 'mikayla': 783,
 'matilda': 784,
 'callie': 785,
 'marni': 786,
 'vikki': 787,
 'meng': 788,
 'marta': 789,
 'hui': 790,
 'thuan': 791,
 'storm': 792,
 'henry': 793,
 'ky': 794,
 'cheyenne': 795,
 'talia': 796,
 'katrina': 797,
 'rhiannon': 798,
 'gene': 799,
 'adrianna': 800,
 'cong': 801,
 'd': 802,
 'arn': 803,
 'jaimee': 804,
 'keri': 805,
 'glen': 806,
 'larissa': 807,
 'sam': 808,
 'beverly': 809,
 'jasmin': 810,
 'st': 811,
 'sheryl': 812,
 'bessie': 813,
 'justin': 814,
 'ry': 815,
 'fred': 816,
 'justine': 817,
 'kelley': 818,
 'omar': 819,
 'clarissa': 820,
 'breanna': 821,
 'erik': 822,
 'shah': 823,
 'gloria': 824,
 'helena': 825,
 'manoj': 826,
 'caterina': 827,
 'allan': 828,
 'isa': 829,
 'dakota': 830,
 'ivana': 831,
 'elijah': 832,
 'nhat': 833,
 'kaitlyn': 834,
 'gabriele': 835,
 'ralph': 836,
 'jaymes': 837,
 'elliott': 838,
 'jemma': 839,
 'jian': 840,
 'markus': 841,
 'pablo': 842,
 'maci': 843,
 'carmel': 844,
 'byron': 845,
 'laurel': 846,
 'angelique': 847,
 'morgan': 848,
 'dai': 849,
 'petar': 850,
 'ramona': 851,
 'neville': 852,
 'gay': 853,
 'khang': 854,
 'dianna': 855,
 'amal': 856,
 'tricia': 857,
 'macie': 858,
 'kha': 859,
 'connie': 860,
 'tien': 861,
 'candice': 862,
 'hoa': 863,
 'diamond': 864,
 'blaize': 865,
 'jaie': 866,
 'anastasia': 867,
 'kayden': 868,
 'thang': 869,
 'meegan': 870,
 'blu': 871,
 'tah': 872,
 'alma': 873,
 'samara': 874,
 'kirsten': 875,
 'rubi': 876,
 'ashton': 877,
 'carmela': 878,
 'sami': 879,
 'luisa': 880,
 'tae': 881,
 'irena': 882,
 'christy': 883,
 'lyla': 884,
 'trudi': 885,
 'georg': 886,
 'christa': 887,
 'jessi': 888,
 'son': 889,
 'agnes': 890,
 'shania': 891,
 'khloe': 892,
 'che': 893,
 'brenton': 894,
 'gabriel': 895,
 'brook': 896,
 'wallace': 897,
 'rosemarie': 898,
 'isla': 899,
 'cee': 900,
 'kien': 901,
 'lyndon': 902,
 'kahli': 903,
 'sarina': 904,
 'douglas': 905,
 'darren': 906,
 'archie': 907,
 'sheila': 908,
 'phuc': 909,
 'sunil': 910,
 'joey': 911,
 'payton': 912,
 'ki': 913,
 'kye': 914,
 'paris': 915,
 'tyla': 916,
 'sh': 917,
 'lucinda': 918,
 'y': 919,
 'miriam': 920,
 'jada': 921,
 'sri': 922,
 'cooper': 923,
 'pax': 924,
 'ethan': 925,
 'kobe': 926,
 'jun': 927,
 'kajal': 928,
 'haylee': 929,
 'coby': 930,
 'ho': 931,
 'dion': 932,
 'hollie': 933,
 'brody': 934,
 'chantel': 935,
 'gypsy': 936,
 'sandy': 937,
 'shea': 938,
 'darcy': 939,
 'caitlyn': 940,
 'shelley': 941,
 'noel': 942,
 'kathleen': 943,
 'yun': 944,
 'eleni': 945,
 'mina': 946,
 'ai': 947,
 'kristin': 948,
 'bang': 949,
 'jie': 950,
 'billi': 951,
 'torie': 952,
 'nicola': 953,
 'xian': 954,
 'hailie': 955,
 'khiem': 956,
 'clara': 957,
 'jaimi': 958,
 'angie': 959,
 'deng': 960,
 'carey': 961,
 'meagan': 962,
 'monika': 963,
 'addison': 964,
 'kari': 965,
 'ricki': 966,
 'anton': 967,
 'heather': 968,
 'yvonne': 969,
 'damian': 970,
 'sei': 971,
 'elias': 972,
 'lewis': 973,
 'india': 974,
 'eleanor': 975,
 'dung': 976,
 'codie': 977,
 'dieu': 978,
 'otto': 979,
 'janis': 980,
 'hang': 981,
 'theodore': 982,
 'shaylee': 983,
 'ingrid': 984,
 'georgie': 985,
 'martin': 986,
 'nikolas': 987,
 'kimberley': 988,
 'tuyen': 989,
 'torri': 990,
 'davina': 991,
 'trinh': 992,
 'bj': 993,
 'scarlet': 994,
 'harlow': 995,
 'lila': 996,
 'luna': 997,
 'raye': 998,
 'regan': 999,
 'kae': 1000,
 ...}

In [20]:
word_to_index["kamden"]

1865

In [21]:
index_to_word[1865]

'kamden'

In [22]:
train_seqs = tokenizer.texts_to_sequences(X_trains)
train_seqs[:10]

[[1865],
 [10249],
 [10250],
 [1866],
 [10251],
 [10252],
 [10253],
 [10254],
 [10255],
 [10256]]

In [23]:
test_seqs = tokenizer.texts_to_sequences(X_tests)
test_seqs[:10]

[[417, 548], [], [18700], [], [58156], [], [], [], [], []]

In [24]:
# post means place padding of 0's on the tail or ending of the sequence
# and truncating removes the values of a sequence that is greater than the max length given
train_seqs_padded = pad_sequences(train_seqs, maxlen=train_max_len, padding='post', truncating='post')
train_seqs_padded

array([[  1865,      0,      0,      0],
       [ 10249,      0,      0,      0],
       [ 10250,      0,      0,      0],
       ...,
       [104215,      0,      0,      0],
       [104216,      0,      0,      0],
       [104217,      0,      0,      0]], dtype=int32)

In [25]:
# post means place padding of 0's on the tail or ending of the sequence
# and truncating removes the values of a sequence that is greater than the max length given
test_seqs_padded = pad_sequences(test_seqs, maxlen=train_max_len, padding='post', truncating='post')
test_seqs_padded

array([[  417,   548,     0,     0],
       [    0,     0,     0,     0],
       [18700,     0,     0,     0],
       ...,
       [    0,     0,     0,     0],
       [    0,     0,     0,     0],
       [    0,     0,     0,     0]], dtype=int32)

In [26]:
Y_trains

2853      0
143300    0
111302    1
27499     0
84175     1
         ..
41993     0
97639     1
95939     0
117952    1
43567     1
Name: Gender, Length: 117815, dtype: int64

In [27]:
# at the same time one hot encode the y labels/classes
# and retrieve the number of unique labels of y
train_unique_labels = Y_trains.unique()
len_train_unique_labels = len(train_unique_labels)
len_train_unique_labels
# train_Y_oh = one_hot(Y_trains, depth=len_train_unique_labels).numpy()
# train_Y_oh

2

In [28]:
# at the same time one hot encode the y labels/classes
# and retrieve the number of unique labels of y
test_unique_labels = Y_tests.unique()
len_test_unique_labels = len(test_unique_labels)
len_test_unique_labels
# test_Y_oh = one_hot(Y_tests, depth=len_test_unique_labels).numpy()
# test_Y_oh

2

In [36]:
test_unique_labels

array([0, 1])

In [99]:
# includes oov words
vocab_len = len(word_to_index) + 1
# emb_dict, emb_vec_len = construct_embedding_dict('./embeddings/glove.twitter.27B.50d.txt', word_to_index)
# emb_matrix = construct_embedding_matrix(word_to_index, emb_dict, emb_vec_len)
lstm_model = load_lstm_model(train_max_len, vocab_len)

input shape: 4

In [100]:
# emb_matrix.shape

In [101]:
# emb_matrix.any(axis=1).sum()

In [102]:
lstm_model.summary()

Model: "fil-name-gender-lstm"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding-layer (Embedding)     │ (None, 4, 256)         │    26,679,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_20                │ (None, 256)            │       394,240 │
│ (Bidirectional)                 │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_20 (Dropout)            │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_21 (Dense)                │ (None, 1)              │           257 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_20 (Activation)      │ (None, 1)              │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 27,074,305 (103.28 MB)

 Trainable params: 27,074,305 (103.28 MB)

 Non-trainable params: 0 (0.00 B)

In [103]:
lstm_model.get_layer('embedding-layer').trainable

True

In [104]:
train_seqs_padded

array([[  1865,      0,      0,      0],
       [ 10249,      0,      0,      0],
       [ 10250,      0,      0,      0],
       ...,
       [104215,      0,      0,      0],
       [104216,      0,      0,      0],
       [104217,      0,      0,      0]], dtype=int32)

https://www.kaggle.com/code/shrikrishnaparab/gender-prediction-based-on-name-using-lstm

In [106]:
lstm_history = lstm_model.fit(
    train_seqs_padded, Y_trains,
    batch_size=64,
    epochs=10,
    validation_split=0.2,
)

Epoch 1/10
 110/1473 ━━━━━━━━━━━━━━━━━━━━ 2:45 121ms/step - auc_9: 0.5000 - binary_accuracy: 0.6077 - binary_crossentropy: 9.7545 - f1_score: 0.7560 - loss: 0.2464 - precision_9: 0.6077 - recall_9: 1.0000

KeyboardInterrupt:

In [ ]:
lstm_history