In [160]:
import pandas as pd
import os
import tensorflow as tf
import numpy as np

from utilities.preprocessors import preprocess, assign_gender, map_value_to_index
from utilities.visualizers import view_rows
from utilities.loaders import load_file, load_meta_data, load_lookup_array
from models.fil_lstm_glove import load_lstm_model

from dotenv import load_dotenv
from pathlib import Path

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [161]:
# load environment variables path
env_dir = Path('../').resolve()
load_dotenv(os.path.join(env_dir, '.env'))

Python-dotenv could not parse statement starting at line 53
Python-dotenv could not parse statement starting at line 57
Python-dotenv could not parse statement starting at line 63
Python-dotenv could not parse statement starting at line 64
Python-dotenv could not parse statement starting at line 66
Python-dotenv could not parse statement starting at line 68
Python-dotenv could not parse statement starting at line 70
Python-dotenv could not parse statement starting at line 74
Python-dotenv could not parse statement starting at line 75
Python-dotenv could not parse statement starting at line 77
Python-dotenv could not parse statement starting at line 83
Python-dotenv could not parse statement starting at line 84
Python-dotenv could not parse statement starting at line 85
Python-dotenv could not parse statement starting at line 86
Python-dotenv could not parse statement starting at line 89
Python-dotenv could not parse statement starting at line 90
Python-dotenv could not parse statement starting at line 92
Python-dotenv could not parse statement starting at line 96
Python-dotenv could not parse statement starting at line 97
Python-dotenv could not parse statement starting at line 103
Python-dotenv could not parse statement starting at line 104
Python-dotenv could not parse statement starting at line 105
Python-dotenv could not parse statement starting at line 106
Python-dotenv could not parse statement starting at line 107
Python-dotenv could not parse statement starting at line 110
Python-dotenv could not parse statement starting at line 111
Python-dotenv could not parse statement starting at line 113
Python-dotenv could not parse statement starting at line 119
Python-dotenv could not parse statement starting at line 120
Python-dotenv could not parse statement starting at line 121
Python-dotenv could not parse statement starting at line 124
Python-dotenv could not parse statement starting at line 125
Python-dotenv could not parse statement starting at line 127
Python-dotenv could not parse statement starting at line 129
Python-dotenv could not parse statement starting at line 135
Python-dotenv could not parse statement starting at line 136
Python-dotenv could not parse statement starting at line 138
Python-dotenv could not parse statement starting at line 140
Python-dotenv could not parse statement starting at line 142
Python-dotenv could not parse statement starting at line 146
Python-dotenv could not parse statement starting at line 147
Python-dotenv could not parse statement starting at line 149
Python-dotenv could not parse statement starting at line 151
Python-dotenv could not parse statement starting at line 155
Python-dotenv could not parse statement starting at line 156
Python-dotenv could not parse statement starting at line 158
Python-dotenv could not parse statement starting at line 160
Python-dotenv could not parse statement starting at line 162
Python-dotenv could not parse statement starting at line 164
Python-dotenv could not parse statement starting at line 166
Python-dotenv could not parse statement starting at line 170
Python-dotenv could not parse statement starting at line 171
Python-dotenv could not parse statement starting at line 173
Python-dotenv could not parse statement starting at line 175
Python-dotenv could not parse statement starting at line 177
Python-dotenv could not parse statement starting at line 179
Python-dotenv could not parse statement starting at line 185
Python-dotenv could not parse statement starting at line 186
Python-dotenv could not parse statement starting at line 188
Python-dotenv could not parse statement starting at line 190
Python-dotenv could not parse statement starting at line 191
Python-dotenv could not parse statement starting at line 192
Python-dotenv could not parse statement starting at line 194
Python-dotenv could not parse statement starting at line 195
Python-dotenv could not parse statement starting at line 197
Python-dotenv could not parse statement starting at line 198
Python-dotenv could not parse statement starting at line 200
Python-dotenv could not parse statement starting at line 201
Python-dotenv could not parse statement starting at line 203
Python-dotenv could not parse statement starting at line 205
Python-dotenv could not parse statement starting at line 207
Python-dotenv could not parse statement starting at line 209
Python-dotenv could not parse statement starting at line 211
Python-dotenv could not parse statement starting at line 213
Python-dotenv could not parse statement starting at line 216
Python-dotenv could not parse statement starting at line 221
Python-dotenv could not parse statement starting at line 222
Python-dotenv could not parse statement starting at line 227
Python-dotenv could not parse statement starting at line 230
Python-dotenv could not parse statement starting at line 231
Python-dotenv could not parse statement starting at line 233
Python-dotenv could not parse statement starting at line 235
Python-dotenv could not parse statement starting at line 237
Python-dotenv could not parse statement starting at line 243
Python-dotenv could not parse statement starting at line 244
Python-dotenv could not parse statement starting at line 245
Python-dotenv could not parse statement starting at line 247
Python-dotenv could not parse statement starting at line 249
Python-dotenv could not parse statement starting at line 251
Python-dotenv could not parse statement starting at line 252
Python-dotenv could not parse statement starting at line 253
Python-dotenv could not parse statement starting at line 254
Python-dotenv could not parse statement starting at line 256
Python-dotenv could not parse statement starting at line 257
Python-dotenv could not parse statement starting at line 258
Python-dotenv could not parse statement starting at line 259
Python-dotenv could not parse statement starting at line 260
Python-dotenv could not parse statement starting at line 261
Python-dotenv could not parse statement starting at line 262
Python-dotenv could not parse statement starting at line 263
Python-dotenv could not parse statement starting at line 264
Python-dotenv could not parse statement starting at line 265
Python-dotenv could not parse statement starting at line 266
Python-dotenv could not parse statement starting at line 271
Python-dotenv could not parse statement starting at line 272
Python-dotenv could not parse statement starting at line 274
Python-dotenv could not parse statement starting at line 281
Python-dotenv could not parse statement starting at line 284
Python-dotenv could not parse statement starting at line 289
Python-dotenv could not parse statement starting at line 292
Python-dotenv could not parse statement starting at line 296
Python-dotenv could not parse statement starting at line 299
Python-dotenv could not parse statement starting at line 304
Python-dotenv could not parse statement starting at line 307

True

# load dataframe

In [162]:
conn_info = pd.read_csv('../documents/conn_info.csv', index_col=0)
conn_info

,email,mobile_no,company_name,conn_link,conn_name,gender,salutation
0,paulinomarcus2914@gmail.com,0,Dyson · Full-time,https://www.linkedin.com/in/paulinomarcus/,Marcus Paulino,male,NaN
1,jhericksid15@gmail.com,09294383786 (Home),Cielo Talent · Full-time,https://www.linkedin.com/in/jhericksid/,Jherick Sid Celestial,male,NaN
2,EvanJake.Montano@libertymutual.com,+639260328119 (Mobile),Tata Consultancy Services · Full-time,https://www.linkedin.com/in/evanjakesorianomon...,Evan Jake Soriano Montano,male,NaN
3,capiorheg@gmail.com,0,JBW Managed Services and Consulting Corp · Ful...,https://www.linkedin.com/in/reggielee-capio-a4...,Reggielee Capio,male,NaN
4,johncarlotadeo18@gmail.com,+639432681245 (Mobile),Trojan Recruitment Group · Full-time,https://www.linkedin.com/in/john-carlo-tadeo-2...,John Carlo Tadeo,male,NaN
...,...,...,...,...,...,...,...
1065,NaN,0,transcosmos Asia Philippines Inc. · Full-time,https://www.linkedin.com/in/jamie-rose-cleofas...,Jamie Rose Cleofas,NaN,NaN
1066,jovitfrias@gmail.com,0,RCM Health Care Services · Full-time,https://www.linkedin.com/in/jovit-frias-06a561...,Jovit Frias,NaN,NaN
1067,danlopezatwork@gmail.com,0,Abacus Service Corporation · Full-time,https://www.linkedin.com/in/danlopezprofessional/,Mark Daniel Lopez,NaN,NaN
1068,dmrc_06@yahoo.com,09983696222 (Mobile),RingCentral · Full-time,https://www.linkedin.com/in/daena-michaela-roy...,Daena Michaela Ceria,NaN,NaN
1069,reyes.joanamace10@gmail.com,09672 182668 (Mobile),iQor Philippines,https://www.linkedin.com/in/joana-mace-reyes-b...,Joana Mace Reyes,NaN,NaN

In [163]:
conn_info.dtypes

email            object
mobile_no        object
company_name     object
conn_link        object
conn_name        object
gender           object
salutation      float64
dtype: object

In [164]:
conn_info = conn_info.astype('category')
conn_info

,email,mobile_no,company_name,conn_link,conn_name,gender,salutation
0,paulinomarcus2914@gmail.com,0,Dyson · Full-time,https://www.linkedin.com/in/paulinomarcus/,Marcus Paulino,male,NaN
1,jhericksid15@gmail.com,09294383786 (Home),Cielo Talent · Full-time,https://www.linkedin.com/in/jhericksid/,Jherick Sid Celestial,male,NaN
2,EvanJake.Montano@libertymutual.com,+639260328119 (Mobile),Tata Consultancy Services · Full-time,https://www.linkedin.com/in/evanjakesorianomon...,Evan Jake Soriano Montano,male,NaN
3,capiorheg@gmail.com,0,JBW Managed Services and Consulting Corp · Ful...,https://www.linkedin.com/in/reggielee-capio-a4...,Reggielee Capio,male,NaN
4,johncarlotadeo18@gmail.com,+639432681245 (Mobile),Trojan Recruitment Group · Full-time,https://www.linkedin.com/in/john-carlo-tadeo-2...,John Carlo Tadeo,male,NaN
...,...,...,...,...,...,...,...
1065,NaN,0,transcosmos Asia Philippines Inc. · Full-time,https://www.linkedin.com/in/jamie-rose-cleofas...,Jamie Rose Cleofas,NaN,NaN
1066,jovitfrias@gmail.com,0,RCM Health Care Services · Full-time,https://www.linkedin.com/in/jovit-frias-06a561...,Jovit Frias,NaN,NaN
1067,danlopezatwork@gmail.com,0,Abacus Service Corporation · Full-time,https://www.linkedin.com/in/danlopezprofessional/,Mark Daniel Lopez,NaN,NaN
1068,dmrc_06@yahoo.com,09983696222 (Mobile),RingCentral · Full-time,https://www.linkedin.com/in/daena-michaela-roy...,Daena Michaela Ceria,NaN,NaN
1069,reyes.joanamace10@gmail.com,09672 182668 (Mobile),iQor Philippines,https://www.linkedin.com/in/joana-mace-reyes-b...,Joana Mace Reyes,NaN,NaN

In [165]:
conn_info['mobile_no'] == "0"

0        True
1       False
2       False
3        True
4       False
        ...
1065     True
1066     True
1067     True
1068    False
1069    False
Name: mobile_no, Length: 1070, dtype: bool

In [166]:
conn_info['gender'].dtype

CategoricalDtype(categories=['female', 'male'], ordered=False, categories_dtype=object)

In [167]:
pd.isnull(conn_info['gender'])

0       False
1       False
2       False
3       False
4       False
        ...
1065     True
1066     True
1067     True
1068     True
1069     True
Name: gender, Length: 1070, dtype: bool

In [168]:
conn_info['gender'].unique()

['male', 'female', NaN]
Categories (2, object): ['female', 'male']

In [169]:
conn_info['conn_name'] = conn_info['conn_name'].apply(preprocess)
conn_info.head()

Aaron Mitchel Ancheta
Aaron Penaco
Aaron Santos
Abegail Jean Bañez
Abigail Baliwang
Abigail Lyle Arquero
Adrian Joseph
Adriane Valderrama
Aerdan Joseph Lacson
Agot Reyes
Aimeh Grace Nono Lazaro
Aira Batang
Aira Danielle Cacho
Aira Magallon
Airene Ramilo
Airizh Criztal Santos
Aisha Locsin Red
Aishwarya Tanwar
Aiza Ricohermoso
Al Christian Agngarayngay
Al D.
Al John Ezekiel Udtuhan
Al Valencia
Aldrin Astrande
Alecks Alamo
Alecs Rodriguez
Alfred Tolentino
Allan Repalda
Allen Dionio
Allexa Contreras
Alliza Mendoza
Allyssa Reyes
Aloha Ferrer
Aloicius Justine Kochensparger
Alvin Troy Catacutan
Alyanna Monica Coladilla
Alyssa Bela Ong
Alyssa Christa Cunanan
Alyssa Jean Sonza
Alyssa Kirra Macarilay
Alyssa Marie Lansangan
Alyssa Marie Reyes
Alyssa Solitario
Ameera Valdez
Amiel Ayroso
Ana Kathleen Adoc
Ana Marie Simbajon
Anabelle Millena
Andrea Bianca Punzal
Andrea Jabat
Andrea Justiniano
Andrea Mae Austria
Andrea Martinez
Andrea Nicole Odones
Andrea Vasily Gallardo
Angel Amosin
Angel P. Figueras Lpt
Angela Alcantara
Angelica Bula
Angelica Fernandez
Angelica Kolambil
Angelica Mamaid
Angelica Marie Wida
Angelica Salandanan
Angelicca Sadanguel
Angelika Barriga
Angelique Benemerito
Angello Poblete
Angelo Dipay
Angelo Hernandez
Angely May Parel
Anjelica Joice Pantig Amparo
Anjelica Matabalan
Ann Caroline Tablada Domasin
Ann Josenen Regencia
Ann Marimar Porquez
Anna Carmela Macam
Anne Camino
Anne Mariano
Anthony Autor
Anthony Louissetien Morales
April Bautista
April Bea Entac
April Mimi Marcelo
April Pie Tayong
Arbaz Hussain
Archie Laranang
Arci Glodove
Arden Caparas
Arguelito Solpico Jr.
Ariane Sampaga
Arianne Amio
Arianne Faith Pagapulan
Ariel Cole
Arissa Miles Rodriguez
Arline Joannah Suniga
Arra Thea Alagad
Arvin Joseph De Leon
Ashley Sadine Djandaghi Bautista
Aubrey Lou Maldonado
Audrea Marie Boto
Ave May Mallari
Avi O
Axel Pambid
Ayla Paguio
Az Cabrera Chrp
Baby Jean Arandia
Beatrice Umila
Beejey Jarabe
Benilda Diaz
Bernadette Esteban
Beverly Hawksworth
Beverly Lariosa
Beverly Monungolh
Blessilda Catap
Bran Cruz
Bryan Drexler Azarcon
Bryan Pattaui
Calleene Gabe Pascual
Camelle Villarin
Camille Catigay
Camille Eloisa Mendoza
Camille Gandol
Camille Inovio
Camille Sunga
Cams Cabungcal
Carl Javier
Carl Kenneth Alzaga
Carla Antonia Montelibano
Carla Chavez
Carla Lubuguin
Carla Mico
Carlin Therese Tatad
Carlo Angelo Baniaga
Carlo Estoconing
Carmelo P. Litanon Ii
Casey Grandeza
Catherine "Khite" Cruz
Catherine Jane Alhambra
Catherine Lavadia
Catherine Mariano
Catherine Santos Magnaye
Cel Rodriguez
Celine Anne Buhain
Celine F
Cess Balbuena
Charina Ibo
Charisse Ivan De Leon
Charlene Artes
Charles Aquino
Charlize Aberdeen Villa
Charmaine Joy Quito
Chaster Joy Leones
Cherry Lou Haluag
Cheryl Dela Cruz
Chesca Benito
Cheska Tolosa
Chester Symon Fetalcorin
Chinnie Joy Obispo
Christabel San Gabriel Andres
Christell Nicole Barquin
Christian Alicog
Christian Cachola Chrp
Christian Gabriel Villegas
Christian Glendale Fernandez
Christian Joseph Garlitos
Christian Lumanog
Christian Mark Boñola
Christine Ariate
Christine Dianne Ortiz
Christine Isip Arci
Christine Joy Embodo
Christine Joyce Sapoco
Christine Mae Linatoc
Christine Marie Mendoza
Christopher Gonzalez
Christopher Villareal
Ciara Domingo
Cindy Caseda
Claire Anne Oliman
Clarisa Tallada
Clarissa Meneses Chrp
Clarisse Buenconsejo
Claudine Des
Clint Villanueva
Clyde Luis Tuazon
Coleen Gapas
Colene Joice De Leon
Corinne Supangan
Cp Diaz
Cristell Dioneda
Cristien Angel Mae Bernabe
Cristine Joy Marcial
Cristine Valdez
Criza May Beriong
Currie Orpiano
Cyrelle Rongavilla
Cyril Garcia
Czayra Gabrielle Reyes
Daena Michaela Ceria
Dagami Padillo
Daisy Jane Reas
Dale Gilbert Galindez
Dale Schofield
Danesa Sotomayor Pulido
Danica Valdoz
Daniel Binos
Daniel Sebastian
Daniella Mae B.
Danielle Dela Cruz
Danniel Tongol
Dariel Latoza
Darille Galleros
Darrel Baliwag
Darwin Gasacao
Daryl Anne Centura
David Hofer
Dea Cinco
Deanne Fernando
Debbie Anne Marie Ebol
Dee Marie Joy Dada
Del V.
Demirene Hentoloro
Dennis Concepcion
Dexter Dumlao
Dexter Tiamzon
Dhea Pineda
Diana Atienza
Diana Hilario
Diane Grace Dayap
Diane Olano
Dianna Marie Platero
Dianne Kristine Ansula
Dianne Ruth Malinao
Dianne Zaira Pingcas
Diojam Etcobanez
Diosdado Hawang
Doelsie Pagaran Torres
Don King Valdesco
Don Manongsong
Don Refuerzo
Dorina Faye Antonio Torres
Dyan Marie Bautista
Earl Florence Villanueva
Ed Christian Barrientos
Ed Patco
Eddie Jr Bacalla
Eduard Brazil
Efren Flores
Ehmilee Maye Garcia
El Batuna
Elaine Marion Edaño
Elaine Padilla
Elaine Rose Malayo
Elaine Villa Balatero
Elaiza Wileman
Elijah Gabrielle Malicdem
Eliza Joy Fran
Elizabeth Anne Cuvin King
Ella Tariman
Ellaine Jara
Ellaine Villa
Ellen Faye Javier
Ellyka Kischa Williams
Eloisa Porca
Elvin Eligado
Elyssa Joy Peraz
Emilyn Alonsagay
Emmanuel Alfonso Ciencia
Enrisa Lara
Entee Casanova
Equel N.
Eric Jayson Fombo
Erica Zhang
Ericka Mae Tubog
Ericson Ramos
Erika Ray Ramirez
Ermmellyn May Acupang
Ernell Carl Ampit
Ervic Jerel Japitana
Erwin Roy Lopez
Eumir Mondok
Eunice Bernadette Javier
Eunice Medina
Eunice Pamela Canilang
Evan Jake Soriano Montano
Evangeline Panganiban
Faith Joyce Martinez
Faye Emerald Dela Cruz
Felix Dulatre
Fernchesca Aquino
Florence Benette Gallego
Florence Hipolito
Folusho Olaniyan
France Mercado
Francesca Moralejo
Franchesca Oliman
Francis Mah
Francis Sicat
Francoise Bejasa
Frederick Almacen
Frisian Acebo
Fritzie Claire Apale
Gabby Jusoy
Gealyn Pafin
Gela Ga Ang
Gem Anonuevo
Gene Reinier Nieto
Gerald Jetro Abuyan
Gerald Renz Sevilla
Geraldine Mangune
Gerard Lorenzo Dizer Natividad
Geroel James Salvador
Gian Karlo Legaspi
Giancarlo Tobias
Giandro Pardilla
Gianne Denise Dueñas
Gilberly Joy Ablao
Gillian Adria Caballero
Gillian Cabello Laylo
Gimson Mendoza
Gine Garcia
Giza Marie Miciano
Glaiza Español
Glaiza Luna
Glen Kier Garcia Peña
Glen Marquez
Glenn De Guzman
Grace Baldovino
Grace Inosanto
Grace Ysabelle Pascual
Greg Canillas Reyes
Gretel Santos
Gybon Bajada
Hannah Alteza
Hannah Camille Santos
Hannah Coleen Nacion
Harsha Bachani
Hasel Francisco
Haunch Cristian Tumangan
Hazel Kelley
Hazelle Cenon
Hearthylyn Fiel
Hector Sumaoang
Helen Wong
Heljine E. Tusio
Herbert Joey Tuazon
Herschel Zamir Laminero
Hp Diaz
Ian Añonuevo
Icko Perez
Ilyn Oso
Ina Buena
Inez Alexandra Alvarez
Isabelita Wenceslao
Ishmael Joshua Tungol
Ivan Acuna
Ivan Villaflor
Ivee Po
Ivern Bernales
Ivy Paragas
Iza Elaine Rose Ellego
Jace Villamor
Jackie Belmonte
Jade Ancajas
Jaezelle Reyes
Jam Alcampado
Jam Marquez Diola
Jamaica Marie Gaytano
James Fernandez
James Madriaga
James Topacio
Jamie Jane Quijano Boneo
Jamie Rose Cleofas
Jan De Guzman
Jan Laurence Valerio
Jan Marie Beltran
Jan Marvin Miranda
Jan Maureen Ariota
Jan Oliver Dimaano
Jana Kristina Mendoza
Jane Bataan
Jane Sanchez
Janice Alvarez Piastro
Janine Alexis Javier
Janine Erika Manzala
Janine Espanol
Janna Tricia Gabriel
Jarrid Anne Remulta
Jason Palinis
Jastin Yap
Jay M Villareal
Jay Panilag
Jaya Maia Alcantara
Jayrah Cruzado
Jayson Callejo
Jayson Lugtu
Jazeinka Isabella Valdez Pineda
Jb Dela Cruz
Jc Consuelo
Je Ann Cuerbo
Jealyn Duyag Ibo
Jean Carlo Mozo
Jeanette O
Jeanne Jessan Aguilar
Jeff Macapobre
Jem Roche Ballesteros
Jema Flor Basilio
Jemel Lovino
Jenevieve Daz
Jenn Dioquino Lsswb
Jennelyn Meñoso
Jenny Magsino
Jera Aira Santiago
Jeramie Jane Roc
Jeremi Anne Ramos
Jerome Soriano
Jeryl Delaganar
Jess Soriao
Jessica Galang
Jessica Louise Saldaña
Jessicamae Mercado
Jester Dayao
Jethro Pamintuan
Jevelyn Borjal
Jewely Opon
Jex Ashley Antonio
Jezreel Czarina Saygo
Jhanina Inotorio
Jhayz Gratuito
Jherick Sid Celestial
Jhomer Diaz
Jhon Remilyn Unciano
Jia Doble
Jiezzete Ignacio
Jigs Ronquillo
Jijomer Dacoscos
Jill Marian
Jo O Paulo Cunanan
Joan Sakuma
Joana Mace Reyes
Joanna Custodio Estrada
Joanna Isabel Montealegre
Jobelyn Estrella
Joe Anne Donato
Joel Per
Joemari Rios
Joemarie Capistrano
Joey Agarao
Joey Rose Briñes
Jogar Bathan
Johanna Perez
John Bendix Mendoza
John Carlo Lim
John Carlo Martinez
John Carlo Sarcia
John Carlo Tadeo
John Christian Mateo
John Daven Torres Clsswb
John Dominic Ocampo
John Emil Adriano
John Jason Odquier
John Kervee Samonte
John Laurence Sarmiento
John Leignard Ragasa
John Louie Del Rosario
John Luther Bondoc
John Manicent Codiniera
John Marin Moreno Clsswb
John Padua
John Panganoron
John Paul Pormento
John Paulo Arciaga
John Reneeric Hernandez
John Rodulph Camizola
John Vincent Sy
John Vincent Tan
Jomar Lerios
Jon Axle Perez
Jona Torres Benzon
Jonalyn Ebit
Jophil Ann Perlado
Jorge Pitong
Jose Maria Galang
Jose Marie Mangalino
Joseph Joshua Donato
Josh Despuig
Joshua Juta
Joshua Kyle S.
Joshua Santiago
Jovit Frias
Joy Amio
Joy Marie Villa
Joy Solana
Joyce Ann Calica
Joyce Estrella
Joylyn Agan
Juan De Leon
Judy Cayabyab
Jules Macalalad
Julia Villaos
Julian Eric Damian
Julio Lecocq Chamorro
Julius Cesar Lomarda
Julius Lee Bacani
Justin Edward Fernandez
Justin Navarette
Justine Cunanan
Justine Dela Peña
Jv Nebres
Kaiser Antenor
Kako Usi
Kamilah Del Rosario
Kamille Gonzales
Kams Casas Rodriguez
Karen Elysse Ulpindo
Karina Manzanilla
Karisse Bernille Labarda
Karl Laurezo
Karl Marx Galado
Karl Monteclaro
Kate Collie Santos
Kate Santos
Katherine Talag
Kathleen Kate Odulio
Kathleen Limon
Kathleen Punzalan
Kathlyn Pagdanganan
Kathrina Telan
Kathrine Salvador
Katlene Kristia Galman
Katreena Marisse Dueñas
Katrina Angela Espiritu
Katrina Leyva
Katt Villapando
Kaye Palmiano
Kaye Peña
Kean Jardin
Keanne Samar
Kei Bryan Dusaban
Kenn Dominic Macarat
Kennah Bea Cambari
Kenneth Joy Loteyro
Kenneth Ramil
Kevin Brylle Santos
Khaye Banguis
Khea Ronette Noro
Khim Mariez Geronimo
Khris Jan Larce
Khristine Gutierrez
Khyle Zybille De Leon
Kiara Aldover
Kijo Menor
Kim An Marie Yap
Kim Elijah Domingo
Kim Ferrer
Kim Loriel Reyes
Kim Villamor
Kimberly Jane Marcial
Kimberly Maniti
Kimberly Pineda
Kirsten Effie Ezra Lachica
Kit Solis
Kj Chavez
Krissia Geramie Mapatac
Kristelle Ann Villalobos
Kristia C.
Kristian Riz Canama
Kristianne Ysabele Capiral
Kristine Angela Caguiat
Kristine Castilla
Kristine Obsioma
Krizzia Aldovino
Krizzia Mercado
Krystel Flores
Krystel Marie Santiago
Kryzel Ann Oja
Kyla Lalaine Hugo
Kyle Christopher Atilano
Kyle Dominique Agramon
Kyle Maverick Schaefer
Kyra Marco Luicco De Ynchausti
Lady Joan Cabilino
Lancel Jhon Aris Foster
Lara Jhecka Orga
Lawrence Gatpandan
Leila Isabel Villamor
Leoric Pabila
Leroid Manahan
Lerry Aquino
Leslie Ann Noche
Leslie Aquino
Leslie Saspa
Lester John Pacaco
Lester Lacsina
Liana Rosette Ramos
Lisette Jane Lumberio
Liz Cruz
Liza Margaret Caraos
Lloyd Bathan
Loralie Felin
Lorena Baez
Lorenzo Depone Ii
Lorie Loguenario
Lorraine Jean Sequina
Louise Faeldonea
Louise Lozano
Louisze Jhaede Sanchez
Lovely Lamptey
Lovely San Juan
Lovelyn Madriaga
Lyndon Ramo Jr
Ma Samantha Nicole Villanueva
Ma. Angela Lozada
Ma. Carmela De Juan
Ma. Danica Camacho
Ma. Elda Lorca
Ma. Faye Roz
Ma. Joyce Armia
Ma. Katrina Gracia Sedanto
Ma. Messy Carmona
Ma. Stephanie Nicole Lim
Ma. Thelma Flores
Maan Sestona
Mabel Perez
Mac Adornado
Mac Gilfred Uy
Madelaine Ann Bengero
Mae Dionson
Mae Mira
Marc Christian Palisoc
Marc Daniel Melotindos
Marc Jacob Artajos
Marc Stephen Reyes
Marco Caspillan
Marcus Ace Gaitan
Marcus Paulino
Marga Bonilla
Margarett Racho
Maria Anneli Rose Suarez
Maria Christinapaz Parker
Maria Clarissa Felipe
Maria Ignacia Quesada
Maria Katrina Cuenca
Maria Katrina Guiñares
Maria Kristina Monroy
Maria Lourdes Des Gomez Alem Chrp
Maria Rouchelle Manaig
Maria Zarina Antonio
Mariah Cristine Tamayo
Mariah Joy Masinda
Marialyn Real
Marianne Diocares
Marianne Valdez
Maricar B.
Maricel Torres
Maricris Cenal
Marie Centural
Marie Nazareno Reyes
Marie Rhona Maleen Carandang
Mariel Cyra Mendoza
Mariel Publico
Marielle Toribio
Maries Tan
Marih Jomoc
Mariko Miranda
Marinella Villanueva
Marissa Avila
Marissa Esmeria
Marjorie Fonseca
Mark Aldrin Cose
Mark Andrew Mercado
Mark Daniel Lopez
Mark Daniel Povadora
Mark Elliah M. Sanchez
Mark Florian Solano
Mark Kevin Garcia
Mark Pencer Inopiquez
Marlon De Mesa
Marlyn Mag Isa
Martin Aguilar
Marvee Juan
Marvic Marbb Calindro
Marvin Samaniego
Marvin Victoria
Mary Andrea Jugo
Mary Ann Leonida
Mary Bernalyn Therese Ignacio
Mary Claire Cabanda
Mary Diane Alcala
Mary Genova
Mary Grace Munoz
Mary Joy Antoc
Mary Joy Pagulayan
Mary Joy Zamudio
Mary Joyce Avendano
Mary Lou Gobrin
Mary Nole Hazel Padagdag
Mary Rose Balingit
Matthew De Catalina
Maurich Macatangay
Max Evangelista
May Buendia Palabrica
Mayca Merencillo
Maze Enrile Rivera
Megan Rivera
Mehjebin Khan
Meliza Anne Kionisala
Melvin Peralta
Meng Raymundo
Mereden Gamosa
Meredith Nichole Escario
Mia Alcantara
Mia Baylon
Miah Ibañez
Mica Baes
Mica Joy Remoquillo
Micah Cabuslay
Micah Viado
Mich Cendaña
Michelle C.
Michelle Matanguihan
Michelle Morales
Michelle Recaña
Micka Alcovindas
Mico Louis Mañalac
Micol Maglalang
Miggy Garcia
Miggy Sy
Miguel Arceo
Mikael John Paras
Mikaela Leigh Padrelanan
Mikee Del Prado
Mikee Torre
Mikhaela Malabanan
Miks Yalong
Mirachael Mendoza
Mitche Ajesta
Mj Visitacion
Moira Abesamis
Nadeth Marquez
Nadine Lacsamana
Naidinne Lee
Nairie Solante
Nancy Niu
Natasha Myrtle Sasaki
Nathaniel Sevilla
Neil Andrew Ynacis
Nemuel Pamplona
Nerissa Anne Ojales
Nic Golipapa
Nickie Rose Arpon
Nicole Algire Demonteverde
Nicole Capales
Nicole Limbo
Niela Centeno
Nikka Faola Valle
Nikko De La Cerna
Nilfe Mae Sumagaysay
Nina Cababa
Nina Lanante
Nirica Kathleen Mavotas
Niña Katrina Coronel
Niño July Mabilangan
Noel Gamalindo
Noel Tarranco
Noelle Barcenas
Noelle Noey Pangilinan
Nomer Calara
Nowrine Shiena Hossen
Oliver Gabuna
Oliver Sison
Pam Rico Map Cand.
Pamela Bianca Co
Pamela Nadine Alvaro Baldovino
Pamela Pamonag
Pamela Yasmin Buluran
Paola Teopiz
Paolo Gabriel Lanurias
Paolo Galve
Paolo Parayno
Paolo Rafael Hulog
Patricia Amor Pam
Patricia Berenguel
Patricia Kate Concepcion
Patricia Marie Bobadilla
Patrick Jovie Alaban
Patrick Malibunas
Patrixia Punzalan
Paul Andrew Taboada
Paul Gromglieng Grom Li Yeng
Paula Del Rosario Casas
Paula Marie Gallian
Paula Patricia Valentin
Paulene Hazelen Gornes
Paulo Gutierrez
Pearl D
Peavey Gail Santos
Peejay Adlawon
Phil Dael
Philip Azur
Philip Mercado
Pol Tahoynon
Prince Angelo Torres
Princess Dalumpines
Princess Helen Delos Santos
Princess Macatuggal
Princess Miñon
Princess Morfe
Princess Yobel Domingo
Quecel Therese Ordaniel
Queenie Onipa
Quin Lawrence Sibonga
Quincey Jugo
Quincy Erika Ramos
Racel Leihart Patricio
Rachelle Alfaro
Rachelle Suico
Racquel Abadiez
Rae Ramirez Chrp
Rafael Ryan Lloren
Raffy Jay Villapaña
Ragin Marie Baytan
Rain Acuesta Chrp
Raleen Aguilar
Ralph Marwin Loyola
Randell Cortez
Randy Marjalino
Raphael Bacaling
Raphael Ventura
Raquel Villafuerte
Raul Badon
Raven Cabidog
Raven Isaac
Raymond De Vera
Raymond Gatchalian
Rebekah Mabaet
Regan Villacastin
Regent Sula Gacusan
Reggie Pascual
Reggielee Capio
Regine Calibay
Regine Orozco
Reina Yago
Reiner Arcilla
Remegio Madarang Jr
Rence Maynes
Renel Tibo
Renz Cristina Garbin
Renz Martinez
Renzcy Mendoza
Renzo Reyes
Reselyn Jane Alonzo
Revin Aves Naing
Rhain De Dios
Rhina Hipolito
Rhoivin Mendoza Ilagan
Rhuff Danica Gambong
Rhuskine Dimla
Rica Niña Camangyan
Ricamay Ballad
Ricaport Casanayan
Rich Moscoso
Richard Justine Corporal
Richmond Babasa
Ricky Beatriz Agbanlog
Rinna Lizza
Riza Fortunato
Rizamae Milet Austria
Rizamelle Estil
Rizza Indig
Rizza Villanueva
Rizziane Frago
Robert Jethro Enriquez
Rochelle Bulan
Rochelle Miguela Angeles
Rochemey Ortiga
Rodalyn Orale
Rodella "Leng" Tolentino
Rodny Selorio
Rodolfo Cantongos
Roma Doria Panaligan
Roma Ramilo
Rome Benedicto
Romel Buenavista
Romel Sayomac
Romina Morallos
Rommel Yumang
Ron Mulleda
Ron Rachelle Catuiran
Ron Richard Ramirez
Rona Jamaica Geronimo
Ronald Ramas
Rory Rm
Roselle Allison Santiago
Roselyn Achas
Roselyn Montances
Rosh Joseph Gador
Rosmel Oropesa
Roy Alegado
Ruel Casane
Russell Rogan
Ruzzel Coronado Clsswb
Ry Lope
Ryan Gilbert Grefiel
Ryan Taboada
Rychelle Himongala
Rye Dizon
Ryssel Joy Tumayan
Sam S.A. Sornito
Samantha Gayle Lee
Sarah Jane Migueh
Sarah Jane Padayao
Sarah Mendoza
Sarheene Khattab
Sarrah Dulguime
Scott Vincent Nacua
Sean Paolo Elarco
Sergius Paulo Vidallon
Severly Suzie Oka
Shae Bernabe
Shainna Delgado
Shane Calub
Sheena Lee
Shekinah Cuevas
Sherilyn Bejar
Shermie Louize Bryan Herrera
Shiena Saballo
Shierlyn Curitana Panlilio
Shirly Ann Larroder
Siara Sangalang
Silviya Georgieva
Simon Kim Hirondo
Socorro Monique Zepeda
Sophia Mizon
Stefhanie Sapeda
Stephanie Anne Mariano
Stephany Orjuela
Talvy Kristine Mae R.
Tania Bondoc
Tedz Ligtvoet
Tel Cadiang
Teresa Hastings
Thea Marivee Rivera
Thea Martinez
Therese Ayra Malones
Therisa May Bagona
Thomas Bernabe
Tin Salmurin
Tina Caluya
Tine Kris
Tito Pascual
Tobit Ibañez Icyb
Toni Monreal
Tonichi Lamsen
Toty Ross Peregrino
Tracy Gregore
Trexx Gan
Tricia Gayle Famadico
Tricia Mae Guan
Triescia Capinpin
Trischia Mae Cabatuan
Trish Teodosio
Trisha Mae Borral
Trisha Marie Flores
Tristan Ivan Chong
Tristan Jerick Reyes
Van Cayabat
Venus Ozarraga
Veronica De Leon
Via Lhiz Cecille Romualdez
Via Margaret Bumatayo
Vic Angelo Flores
Vin Escalante
Vin Mendoza
Vincent Dan Mijares
Vincent Trovela
Von Christian Saret
Wendell Villareal Guidoriagao
Wilma Isidro
Winfred Louis Camello
Xavier Pascual
Yasmin Tubice
Yhing Miranda Manundo
Ynah Serrano
Yohan Nicole Aroja
Yuih Salvador
Yvette Lacson
Zaira Cadampog
Zarah Nicole Dela Vega
Zedrick Ross Paz
Zee Acaso
Zen Athena Magdasoc
Zhaira Andrea Manglo
Zhaira Cosep
Zion Resurreccion

,email,mobile_no,company_name,conn_link,conn_name,gender,salutation
0,paulinomarcus2914@gmail.com,0,Dyson · Full-time,https://www.linkedin.com/in/paulinomarcus/,Marcus Paulino,male,NaN
1,jhericksid15@gmail.com,09294383786 (Home),Cielo Talent · Full-time,https://www.linkedin.com/in/jhericksid/,Jherick Sid Celestial,male,NaN
2,EvanJake.Montano@libertymutual.com,+639260328119 (Mobile),Tata Consultancy Services · Full-time,https://www.linkedin.com/in/evanjakesorianomon...,Evan Jake Soriano Montano,male,NaN
3,capiorheg@gmail.com,0,JBW Managed Services and Consulting Corp · Ful...,https://www.linkedin.com/in/reggielee-capio-a4...,Reggielee Capio,male,NaN
4,johncarlotadeo18@gmail.com,+639432681245 (Mobile),Trojan Recruitment Group · Full-time,https://www.linkedin.com/in/john-carlo-tadeo-2...,John Carlo Tadeo,male,NaN

In [170]:
view_rows(conn_info, 'conn_name')

Marcus Paulino
Jherick Sid Celestial
Evan Jake Soriano Montano
Reggielee Capio
John Carlo Tadeo
Lorenzo Depone Ii
Jaya Maia Alcantara
Jan Laurence Valerio
Kimberly Pineda
nan
nan
Moira Abesamis
Rafael Ryan Lloren
Aishwarya Tanwar
Lerry Aquino
Camelle Villarin
Jules Macalalad
Bryan Drexler Azarcon
Christine Marie Mendoza
Nadine Lacsamana
Alecs Rodriguez
Gianne Denise Dueñas
Camille Eloisa Mendoza
Airizh Criztal Santos
Ericson Ramos
Felix Dulatre
Aaron Santos
Herschel Zamir Laminero
Corinne Supangan
Kathlyn Pagdanganan
Trisha Mae Borral
Noelle Barcenas
Ma. Angela Lozada
Vincent Dan Mijares
Kyle Christopher Atilano
Jhanina Inotorio
Giancarlo Tobias
nan
John Paul Pormento
Hazelle Cenon
Anne Camino
Arbaz Hussain
John Manicent Codiniera
Mia Alcantara
Allen Dionio
Erica Zhang
nan
Kenneth Joy Loteyro
Riza Fortunato
Aisha Locsin Red
Tedz Ligtvoet
Chesca Benito
Iza Elaine Rose Ellego
Kim Ferrer
Amiel Ayroso
Nicole Algire Demonteverde
Joy Marie Villa
Janna Tricia Gabriel
Ruzzel Coronado Clsswb
Ma. Stephanie Nicole Lim
nan
Tania Bondoc
Adriane Valderrama
Khea Ronette Noro
Kyla Lalaine Hugo
Kyra Marco Luicco De Ynchausti
France Mercado
Gabby Jusoy
Jethro Pamintuan
Inez Alexandra Alvarez
Rychelle Himongala
Ann Caroline Tablada Domasin
John Rodulph Camizola
nan
Paulo Gutierrez
Angelique Benemerito
Jenn Dioquino Lsswb
Eunice Medina
Alyssa Marie Reyes
Regine Orozco
Andrea Martinez
Agot Reyes
Rizza Villanueva
Maricris Cenal
Philip Mercado
Raphael Bacaling
Nirica Kathleen Mavotas
Ellen Faye Javier
Nicole Limbo
Nikka Faola Valle
Peejay Adlawon
Roselle Allison Santiago
Lorraine Jean Sequina
Scott Vincent Nacua
Kim Elijah Domingo
Paolo Parayno
Jean Carlo Mozo
Martin Aguilar
Jevelyn Borjal
Nemuel Pamplona
Randy Marjalino
nan
Isabelita Wenceslao
Francoise Bejasa
Zion Resurreccion
Chester Symon Fetalcorin
Evangeline Panganiban
Ermmellyn May Acupang
Daniel Sebastian
Heljine E. Tusio
Teresa Hastings
Gillian Cabello Laylo
Pearl D
Nilfe Mae Sumagaysay
Kaiser Antenor
Katt Villapando
Jophil Ann Perlado
nan
Jewely Opon
Angelica Bula
Nathaniel Sevilla
Catherine "Khite" Cruz
Kathleen Punzalan
Reina Yago
Ragin Marie Baytan
Maria Ignacia Quesada
Sarah Jane Padayao
Ellyka Kischa Williams
Jam Alcampado
Francis Sicat
Ruel Casane
Arden Caparas
Toni Monreal
Criza May Beriong
Angel P. Figueras Lpt
Mica Joy Remoquillo
John Luther Bondoc
Danielle Dela Cruz
Aimeh Grace Nono Lazaro
Doelsie Pagaran Torres
Karen Elysse Ulpindo
Jaezelle Reyes
Marvin Victoria
Daisy Jane Reas
Sheena Lee
Calleene Gabe Pascual
Fritzie Claire Apale
Maurich Macatangay
Aaron Penaco
Anjelica Matabalan
Melvin Peralta
Jia Doble
Nina Cababa
Arianne Amio
Ivee Po
Cyrelle Rongavilla
Rhuff Danica Gambong
Vin Mendoza
Arci Glodove
Reiner Arcilla
Paula Patricia Valentin
Geraldine Mangune
Charles Aquino
Jon Axle Perez
Shierlyn Curitana Panlilio
nan
Julius Cesar Lomarda
Rich Moscoso
Nadeth Marquez
Von Christian Saret
Andrea Mae Austria
Mark Aldrin Cose
Tracy Gregore
Justin Navarette
nan
Tonichi Lamsen
Ernell Carl Ampit
Mariko Miranda
Beverly Hawksworth
Carlin Therese Tatad
Clyde Luis Tuazon
Daniel Binos
Kathleen Limon
Rye Dizon
Renzo Reyes
Nic Golipapa
Faith Joyce Martinez
Jijomer Dacoscos
Mico Louis Mañalac
Renzcy Mendoza
Darille Galleros
Lancel Jhon Aris Foster
Julio Lecocq Chamorro
Anthony Autor
Mary Nole Hazel Padagdag
Angelo Hernandez
Kirsten Effie Ezra Lachica
Joyce Ann Calica
Samantha Gayle Lee
Glen Kier Garcia Peña
Marielle Toribio
Louise Lozano
Kim An Marie Yap
Pam Rico Map Cand.
Sarah Mendoza
Joe Anne Donato
Eddie Jr Bacalla
Jiezzete Ignacio
nan
Mary Diane Alcala
Ricky Beatriz Agbanlog
Glaiza Luna
Jc Consuelo
Mich Cendaña
Therisa May Bagona
Alyssa Bela Ong
Darrel Baliwag
Andrea Jabat
Erwin Roy Lopez
Debbie Anne Marie Ebol
Frisian Acebo
nan
Ellaine Villa
Celine Anne Buhain
Dianne Zaira Pingcas
Jane Bataan
Via Lhiz Cecille Romualdez
Joel Per
Jeremi Anne Ramos
Mary Bernalyn Therese Ignacio
Stephany Orjuela
Vincent Trovela
Grace Inosanto
Eunice Bernadette Javier
Patricia Marie Bobadilla
Hearthylyn Fiel
Catherine Santos Magnaye
Zedrick Ross Paz
Elijah Gabrielle Malicdem
Vic Angelo Flores
Mary Joy Antoc
Claudine Des
Jarrid Anne Remulta
Jana Kristina Mendoza
Dennis Concepcion
Liana Rosette Ramos
Mae Dionson
Thea Martinez
Kim Loriel Reyes
Ervic Jerel Japitana
Rizamelle Estil
Kathrine Salvador
Ed Christian Barrientos
Ron Rachelle Catuiran
Clarisa Tallada
Charmaine Joy Quito
Eduard Brazil
Jay Panilag
Miggy Garcia
Mark Elliah M. Sanchez
Paul Gromglieng Grom Li Yeng
Aerdan Joseph Lacson
Jennelyn Meñoso
Ma. Carmela De Juan
Racquel Abadiez
James Fernandez
Dariel Latoza
Mary Joyce Avendano
Ave May Mallari
Carla Antonia Montelibano
Micah Viado
Alyssa Christa Cunanan
Marga Bonilla
Allyssa Reyes
Charlene Artes
Raffy Jay Villapaña
Matthew De Catalina
Adrian Joseph
Mikael John Paras
Mariah Cristine Tamayo
Camille Sunga
Camille Sunga
Quecel Therese Ordaniel
Je Ann Cuerbo
Daniella Mae B.
Miguel Arceo
Vin Escalante
Josh Despuig
Rachelle Suico
Janice Alvarez Piastro
Kennah Bea Cambari
Kimberly Maniti
Jeramie Jane Roc
nan
Lester Lacsina
Maria Katrina Guiñares
Rome Benedicto
Rebekah Mabaet
Kim Villamor
Ariane Sampaga
Jealyn Duyag Ibo
Ryan Taboada
Nomer Calara
Don King Valdesco
Mayca Merencillo
nan
Christine Isip Arci
Rence Maynes
Via Margaret Bumatayo
Yuih Salvador
Marc Daniel Melotindos
nan
Stephanie Anne Mariano
Jessicamae Mercado
Catherine Jane Alhambra
Rory Rm
Ellaine Jara
Ronald Ramas
Mary Claire Cabanda
Lorie Loguenario
Princess Macatuggal
Princess Yobel Domingo
Jeanette O
Patrixia Punzalan
Rosmel Oropesa
Shekinah Cuevas
Dale Schofield
nan
Renz Martinez
Shermie Louize Bryan Herrera
Shirly Ann Larroder
Patricia Berenguel
Ricaport Casanayan
Neil Andrew Ynacis
Cristine Valdez
Folusho Olaniyan
Christabel San Gabriel Andres
Jan Marvin Miranda
Ry Lope
Yasmin Tubice
Krystel Flores
Gerard Lorenzo Dizer Natividad
Ynah Serrano
nan
Rosh Joseph Gador
Ivern Bernales
Giandro Pardilla
Dea Cinco
Christian Mark Boñola
John Paulo Arciaga
Arra Thea Alagad
Kj Chavez
nan
Dianna Marie Platero
Cams Cabungcal
Danniel Tongol
Kristia C.
Lorena Baez
Roma Doria Panaligan
nan
Jose Marie Mangalino
Christopher Gonzalez
Rodella "Leng" Tolentino
John Marin Moreno Clsswb
Ma. Joyce Armia
Jemel Lovino
Elaine Marion Edaño
Renel Tibo
Regine Calibay
Kams Casas Rodriguez
Gem Anonuevo
Lisette Jane Lumberio
Aubrey Lou Maldonado
Maria Zarina Antonio
Ella Tariman
Audrea Marie Boto
Baby Jean Arandia
Abegail Jean Bañez
Jill Marian
John Dominic Ocampo
Oliver Sison
Jessica Galang
Kiara Aldover
Ariel Cole
Rodolfo Cantongos
Kei Bryan Dusaban
Krissia Geramie Mapatac
Reselyn Jane Alonzo
nan
Colene Joice De Leon
Siara Sangalang
Eunice Pamela Canilang
Karl Monteclaro
Catherine Lavadia
Anna Carmela Macam
Lovely Lamptey
Elvin Eligado
Janine Erika Manzala
Sarrah Dulguime
Zaira Cadampog
Jema Flor Basilio
Elaiza Wileman
Kean Jardin
Kenneth Ramil
Camille Catigay
nan
Zen Athena Magdasoc
nan
Jazeinka Isabella Valdez Pineda
Ma. Katrina Gracia Sedanto
El Batuna
Mark Kevin Garcia
Arissa Miles Rodriguez
Quincy Erika Ramos
Marco Caspillan
Lawrence Gatpandan
Anabelle Millena
Leila Isabel Villamor
Charisse Ivan De Leon
Raphael Ventura
Joylyn Agan
Rodalyn Orale
Tine Kris
Mac Gilfred Uy
Christine Mae Linatoc
Jackie Belmonte
Julian Eric Damian
Robert Jethro Enriquez
Mikaela Leigh Padrelanan
Jhon Remilyn Unciano
Jamie Jane Quijano Boneo
Prince Angelo Torres
Roselyn Achas
nan
nan
Enrisa Lara
Jade Ancajas
Currie Orpiano
Anjelica Joice Pantig Amparo
Marlon De Mesa
nan
Tin Salmurin
Russell Rogan
Karl Marx Galado
Mikee Torre
Kate Collie Santos
Trexx Gan
Az Cabrera Chrp
John Bendix Mendoza
Rain Acuesta Chrp
Ashley Sadine Djandaghi Bautista
Nowrine Shiena Hossen
nan
Carlo Estoconing
Simon Kim Hirondo
Carmelo P. Litanon Ii
Kako Usi
nan
Justine Cunanan
Jorge Pitong
Cherry Lou Haluag
Tristan Jerick Reyes
Patrick Malibunas
Cess Balbuena
Maria Christinapaz Parker
Don Refuerzo
Glenn De Guzman
Jv Nebres
Pol Tahoynon
Justin Edward Fernandez
John Laurence Sarmiento
nan
nan
Christian Joseph Garlitos
nan
nan
Paulene Hazelen Gornes
nan
Marianne Diocares
Louisze Jhaede Sanchez
Ryssel Joy Tumayan
April Pie Tayong
Revin Aves Naing
Kenn Dominic Macarat
Erika Ray Ramirez
Angelica Salandanan
Remegio Madarang Jr
Meliza Anne Kionisala
Pamela Pamonag
Ralph Marwin Loyola
Emilyn Alonsagay
Jayrah Cruzado
Helen Wong
Clarisse Buenconsejo
Sophia Mizon
Angelica Mamaid
Blessilda Catap
Equel N.
Kryzel Ann Oja
Princess Miñon
Justine Dela Peña
Christian Gabriel Villegas
Kyle Maverick Schaefer
Maricar B.
Kamille Gonzales
Joy Solana
Hannah Alteza
Anthony Louissetien Morales
Marjorie Fonseca
Rochelle Miguela Angeles
Mikhaela Malabanan
Rizamae Milet Austria
Tel Cadiang
Trisha Marie Flores
Jace Villamor
Abigail Lyle Arquero
Mary Grace Munoz
Stefhanie Sapeda
Shiena Saballo
Maria Katrina Cuenca
Yvette Lacson
Katrina Angela Espiritu
nan
Kristian Riz Canama
Lyndon Ramo Jr
Leslie Saspa
Kristine Castilla
Rizziane Frago
Angelica Marie Wida
Tina Caluya
Elaine Villa Balatero
Kristelle Ann Villalobos
Angel Amosin
Angely May Parel
Dhea Pineda
Karina Manzanilla
Kristine Obsioma
Joemari Rios
Angelika Barriga
nan
nan
Oliver Gabuna
Mae Mira
Megan Rivera
Mary Andrea Jugo
Cheska Tolosa
Zhaira Andrea Manglo
Zee Acaso
Jayson Lugtu
Ricamay Ballad
Marvic Marbb Calindro
Veronica De Leon
Rodny Selorio
Madelaine Ann Bengero
Anne Mariano
Mary Lou Gobrin
Glaiza Español
Micol Maglalang
Rochemey Ortiga
Jenny Magsino
Francis Mah
Yhing Miranda Manundo
Rhuskine Dimla
Kathleen Kate Odulio
Maria Rouchelle Manaig
nan
Xavier Pascual
Ana Kathleen Adoc
Rizza Indig
nan
Judy Cayabyab
nan
Nancy Niu
Khaye Banguis
nan
Chaster Joy Leones
Romina Morallos
Jem Roche Ballesteros
Harsha Bachani
Jess Soriao
Daryl Anne Centura
nan
Icko Perez
Beatrice Umila
nan
Reggie Pascual
Julia Villaos
Princess Dalumpines
Triescia Capinpin
Airene Ramilo
Trischia Mae Cabatuan
Alyssa Marie Lansangan
Joshua Kyle S.
nan
Arline Joannah Suniga
Kamilah Del Rosario
Ann Josenen Regencia
Jayson Callejo
Kyle Dominique Agramon
Ayla Paguio
Renz Cristina Garbin
Maricel Torres
Allexa Contreras
Joshua Juta
nan
Mj Visitacion
Romel Sayomac
Gerald Jetro Abuyan
Mary Rose Balingit
Ian Añonuevo
Herbert Joey Tuazon
Ma. Thelma Flores
nan
Marie Centural
Jan Marie Beltran
nan
Jonalyn Ebit
Del V.
Paolo Galve
Michelle Recaña
Joey Rose Briñes
Hazel Kelley
Roma Ramilo
Celine F
Karisse Bernille Labarda
Alvin Troy Catacutan
Claire Anne Oliman
Mark Florian Solano
Therese Ayra Malones
Mark Andrew Mercado
nan
Eliza Joy Fran
Ma. Danica Camacho
Zhaira Cosep
Ann Marimar Porquez
Casey Grandeza
Richard Justine Corporal
Joy Amio
Jeff Macapobre
Diane Grace Dayap
Hannah Camille Santos
Angelica Kolambil
Ed Patco
Roy Alegado
nan
Ivy Paragas
Czayra Gabrielle Reyes
Liz Cruz
Christine Joy Embodo
Sergius Paulo Vidallon
Paula Marie Gallian
Marissa Esmeria
Princess Helen Delos Santos
nan
John Louie Del Rosario
Lovelyn Madriaga
Jan De Guzman
Rica Niña Camangyan
Gian Karlo Legaspi
Diana Atienza
Catherine Mariano
Angelo Dipay
John Carlo Lim
nan
Loralie Felin
Darwin Gasacao
nan
Elyssa Joy Peraz
nan
Hector Sumaoang
Aira Magallon
Tito Pascual
Andrea Vasily Gallardo
Aldrin Astrande
Niela Centeno
nan
Kit Solis
Florence Hipolito
Ma. Elda Lorca
nan
Francesca Moralejo
nan
Raquel Villafuerte
John Emil Adriano
Wendell Villareal Guidoriagao
Ron Richard Ramirez
Raven Isaac
Kristianne Ysabele Capiral
Mac Adornado
Dianne Kristine Ansula
Paul Andrew Taboada
Jeryl Delaganar
Beverly Lariosa
Patricia Amor Pam
Maria Anneli Rose Suarez
Khim Mariez Geronimo
Beverly Monungolh
Rhina Hipolito
Nina Lanante
Khris Jan Larce
Diane Olano
Ana Marie Simbajon
Jb Dela Cruz
Bernadette Esteban
Randell Cortez
Maze Enrile Rivera
Marialyn Real
Nicole Capales
April Mimi Marcelo
Eric Jayson Fombo
Juan De Leon
Richmond Babasa
Regan Villacastin
Ishmael Joshua Tungol
Al Christian Agngarayngay
John Carlo Sarcia
Faye Emerald Dela Cruz
Kijo Menor
Gerald Renz Sevilla
Niña Katrina Coronel
Allan Repalda
Paola Teopiz
Quin Lawrence Sibonga
Ivan Acuna
Joan Sakuma
Venus Ozarraga
Alyssa Kirra Macarilay
Clarissa Meneses Chrp
John Jason Odquier
Rochelle Bulan
Van Cayabat
Noel Gamalindo
Ameera Valdez
nan
Patrick Jovie Alaban
Ericka Mae Tubog
Patricia Kate Concepcion
John Vincent Tan
Leroid Manahan
Silviya Georgieva
Jam Marquez Diola
Kate Santos
Christian Lumanog
Mary Genova
Dexter Tiamzon
Elizabeth Anne Cuvin King
nan
Giza Marie Miciano
Camille Gandol
Ma Samantha Nicole Villanueva
Bryan Pattaui
John Reneeric Hernandez
Entee Casanova
Jex Ashley Antonio
Rae Ramirez Chrp
nan
Jenevieve Daz
Alfred Tolentino
Christopher Villareal
Raymond De Vera
Joshua Santiago
Michelle Morales
Aiza Ricohermoso
Sam S.A. Sornito
Rommel Yumang
Roselyn Montances
Tristan Ivan Chong
Regent Sula Gacusan
Jhomer Diaz
Emmanuel Alfonso Ciencia
Mary Ann Leonida
Christine Dianne Ortiz
Ciara Domingo
nan
Miks Yalong
Hp Diaz
Marie Nazareno Reyes
Alyssa Jean Sonza
Camille Inovio
Thea Marivee Rivera
Marc Stephen Reyes
Meredith Nichole Escario
Christian Alicog
Florence Benette Gallego
Diosdado Hawang
Racel Leihart Patricio
Karl Laurezo
Jeanne Jessan Aguilar
Max Evangelista
John Leignard Ragasa
Ma. Messy Carmona
Hannah Coleen Nacion
Marlyn Mag Isa
Toty Ross Peregrino
Dyan Marie Bautista
Al D.
Ma. Faye Roz
Louise Faeldonea
Thomas Bernabe
Niño July Mabilangan
Dianne Ruth Malinao
Princess Morfe
nan
nan
nan
Noelle Noey Pangilinan
John Kervee Samonte
Cristell Dioneda
Pamela Nadine Alvaro Baldovino
Leslie Aquino
Joanna Custodio Estrada
Gilberly Joy Ablao
nan
May Buendia Palabrica
Mark Daniel Povadora
Jona Torres Benzon
Elaine Rose Malayo
Krizzia Aldovino
Angelica Fernandez
Carla Mico
Joanna Isabel Montealegre
Michelle C.
Rhoivin Mendoza Ilagan
Ron Mulleda
Rinna Lizza
nan
Lester John Pacaco
Pamela Bianca Co
Alyanna Monica Coladilla
Arguelito Solpico Jr.
Angello Poblete
Quincey Jugo
Severly Suzie Oka
Angela Alcantara
Maria Lourdes Des Gomez Alem Chrp
Carl Javier
Aira Danielle Cacho
Nickie Rose Arpon
Mikee Del Prado
Kathrina Telan
Andrea Nicole Odones
Leoric Pabila
Tricia Gayle Famadico
Jomar Lerios
Krizzia Mercado
Noel Tarranco
Kimberly Jane Marcial
Ina Buena
Marvee Juan
Clint Villanueva
Gybon Bajada
Jerome Soriano
Sarah Jane Migueh
Cindy Caseda
Margarett Racho
Dale Gilbert Galindez
John Vincent Sy
Marc Jacob Artajos
Katreena Marisse Dueñas
Meng Raymundo
Nikko De La Cerna
Jezreel Czarina Saygo
Janine Alexis Javier
Marie Rhona Maleen Carandang
Elaine Padilla
Jessica Louise Saldaña
Ivan Villaflor
Don Manongsong
Paula Del Rosario Casas
Lloyd Bathan
Gela Ga Ang
Marc Christian Palisoc
Krystel Marie Santiago
Andrea Bianca Punzal
Queenie Onipa
Philip Azur
Natasha Myrtle Sasaki
Sherilyn Bejar
Frederick Almacen
Maries Tan
David Hofer
Franchesca Oliman
Jogar Bathan
Charina Ibo
nan
Tobit Ibañez Icyb
nan
John Panganoron
nan
Maria Clarissa Felipe
Geroel James Salvador
Andrea Justiniano
Christian Glendale Fernandez
Dee Marie Joy Dada
Aloha Ferrer
Cel Rodriguez
Mirachael Mendoza
Miggy Sy
Arianne Faith Pagapulan
Gillian Adria Caballero
Jamaica Marie Gaytano
Paolo Rafael Hulog
Eumir Mondok
Cheryl Dela Cruz
Lovely San Juan
Pamela Yasmin Buluran
Deanne Fernando
Joey Agarao
Micka Alcovindas
Fernchesca Aquino
Diojam Etcobanez
Jose Maria Galang
Coleen Gapas
Bran Cruz
Mary Joy Pagulayan
Mabel Perez
Marvin Samaniego
Shane Calub
Wilma Isidro
Shae Bernabe
Carlo Angelo Baniaga
Ilyn Oso
Hasel Francisco
Raleen Aguilar
Aira Batang
Aaron Mitchel Ancheta
Janine Espanol
James Madriaga
Jhayz Gratuito
Sean Paolo Elarco
Jera Aira Santiago
Romel Buenavista
Christell Nicole Barquin
Shainna Delgado
Sarheene Khattab
Joseph Joshua Donato
Marcus Ace Gaitan
Marih Jomoc
Kristine Angela Caguiat
Gine Garcia
Mia Baylon
Al Valencia
Michelle Matanguihan
Danesa Sotomayor Pulido
John Carlo Martinez
Jan Maureen Ariota
Liza Margaret Caraos
Carla Chavez
Demirene Hentoloro
nan
Arvin Joseph De Leon
Beejey Jarabe
Jobelyn Estrella
nan
Maan Sestona
John Christian Mateo
Nerissa Anne Ojales
Diana Hilario
Lady Joan Cabilino
Trish Teodosio
Nairie Solante
Johanna Perez
Cristien Angel Mae Bernabe
Gene Reinier Nieto
Christine Joyce Sapoco
Kaye Peña
John Padua
Khyle Zybille De Leon
Greg Canillas Reyes
Mehjebin Khan
Dagami Padillo
nan
Christian Cachola Chrp
Benilda Diaz
Yohan Nicole Aroja
Julius Lee Bacani
Angelicca Sadanguel
Avi O
Raul Badon
Cyril Garcia
Jason Palinis
Efren Flores
Mary Joy Zamudio
James Topacio
Grace Ysabelle Pascual
Gealyn Pafin
Mitche Ajesta
Katrina Leyva
Archie Laranang
Aloicius Justine Kochensparger
Raymond Gatchalian
Kaye Palmiano
Kevin Brylle Santos
Al John Ezekiel Udtuhan
Glen Marquez
Gimson Mendoza
Talvy Kristine Mae R.
Naidinne Lee
Mereden Gamosa
Miah Ibañez
Alliza Mendoza
Alecks Alamo
Khristine Gutierrez
Rachelle Alfaro
Grace Baldovino
Tricia Mae Guan
Ryan Gilbert Grefiel
Mark Pencer Inopiquez
nan
Haunch Cristian Tumangan
Keanne Samar
Marianne Valdez
Jester Dayao
Peavey Gail Santos
Rona Jamaica Geronimo
Katherine Talag
Phil Dael
Jay M Villareal
Jan Oliver Dimaano
Carl Kenneth Alzaga
Alyssa Solitario
Cp Diaz
April Bea Entac
Christine Ariate
Joemarie Capistrano
Mariel Cyra Mendoza
Charlize Aberdeen Villa
Marissa Avila
Mariah Joy Masinda
Winfred Louis Camello
Maria Kristina Monroy
Katlene Kristia Galman
Chinnie Joy Obispo
Lara Jhecka Orga
Jastin Yap
Socorro Monique Zepeda
Zarah Nicole Dela Vega
Mica Baes
Abigail Baliwang
Rhain De Dios
Jo O Paulo Cunanan
Carla Lubuguin
Ehmilee Maye Garcia
John Daven Torres Clsswb
Jigs Ronquillo
Dorina Faye Antonio Torres
April Bautista
Micah Cabuslay
Cristine Joy Marcial
Jane Sanchez
nan
Leslie Ann Noche
nan
Paolo Gabriel Lanurias
nan
Joyce Estrella
Eloisa Porca
Mariel Publico
Dexter Dumlao
Marinella Villanueva
Gretel Santos
Axel Pambid
Earl Florence Villanueva
Raven Cabidog
Danica Valdoz
Jamie Rose Cleofas
Jovit Frias
Mark Daniel Lopez
Daena Michaela Ceria
Joana Mace Reyes

In [171]:
conn_info

,email,mobile_no,company_name,conn_link,conn_name,gender,salutation
0,paulinomarcus2914@gmail.com,0,Dyson · Full-time,https://www.linkedin.com/in/paulinomarcus/,Marcus Paulino,male,NaN
1,jhericksid15@gmail.com,09294383786 (Home),Cielo Talent · Full-time,https://www.linkedin.com/in/jhericksid/,Jherick Sid Celestial,male,NaN
2,EvanJake.Montano@libertymutual.com,+639260328119 (Mobile),Tata Consultancy Services · Full-time,https://www.linkedin.com/in/evanjakesorianomon...,Evan Jake Soriano Montano,male,NaN
3,capiorheg@gmail.com,0,JBW Managed Services and Consulting Corp · Ful...,https://www.linkedin.com/in/reggielee-capio-a4...,Reggielee Capio,male,NaN
4,johncarlotadeo18@gmail.com,+639432681245 (Mobile),Trojan Recruitment Group · Full-time,https://www.linkedin.com/in/john-carlo-tadeo-2...,John Carlo Tadeo,male,NaN
...,...,...,...,...,...,...,...
1065,NaN,0,transcosmos Asia Philippines Inc. · Full-time,https://www.linkedin.com/in/jamie-rose-cleofas...,Jamie Rose Cleofas,NaN,NaN
1066,jovitfrias@gmail.com,0,RCM Health Care Services · Full-time,https://www.linkedin.com/in/jovit-frias-06a561...,Jovit Frias,NaN,NaN
1067,danlopezatwork@gmail.com,0,Abacus Service Corporation · Full-time,https://www.linkedin.com/in/danlopezprofessional/,Mark Daniel Lopez,NaN,NaN
1068,dmrc_06@yahoo.com,09983696222 (Mobile),RingCentral · Full-time,https://www.linkedin.com/in/daena-michaela-roy...,Daena Michaela Ceria,NaN,NaN
1069,reyes.joanamace10@gmail.com,09672 182668 (Mobile),iQor Philippines,https://www.linkedin.com/in/joana-mace-reyes-b...,Joana Mace Reyes,NaN,NaN

In [172]:
conn_info.dtypes

email           category
mobile_no       category
company_name    category
conn_link       category
conn_name       category
gender          category
salutation      category
dtype: object

In [173]:
# temp = conn_info.apply(assign_gender, args=(os.environ['GENDER_API_KEY'], ), axis=1)
# temp

In [174]:
# temp.unique()

In [175]:
# conn_info['gender'] = temp

In [176]:
# conn_info.dtypes

In [177]:
# conn_info.to_csv('../documents/conn_info.csv')

In [178]:
hyper_params = load_meta_data('./saved/misc/fil_name_gender_lstm_hyper_params.json')
hyper_params

{'input_shape': 21,
 'vocab_len': 29,
 'emb_dim': 256,
 'emb_matrix': None,
 'n_a': 128,
 'rnn_drop_prob': 0.2,
 'dense_drop_prob': 0.2,
 'n_units': 1}

In [179]:
lstm_model = load_lstm_model(**hyper_params)
lstm_model

input shape: 21

In [180]:
lstm_model.summary()

Model: "fil-name-gender-lstm"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding-layer (Embedding)     │ (None, 21, 256)        │         7,424 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_4 (Bidirectional) │ (None, 256)            │       394,240 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │           257 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ activation_4 (Activation)       │ (None, 1)              │             0 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 401,921 (1.53 MB)

 Trainable params: 401,921 (1.53 MB)

 Non-trainable params: 0 (0.00 B)

In [181]:
lstm_model.load_weights('./saved/weights/fil_name_gender_lstm_10_0.8914.weights.keras')

In [182]:
chars = load_lookup_array('./saved/misc/fil_name_gender_lstm_lookup.txt')
chars

['0',
 '8',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [183]:
char_to_idx = map_value_to_index(chars)
idx_to_char = map_value_to_index(chars, inverted=True)

In [184]:
char_to_idx.get_vocabulary()

['[UNK]',
 np.str_('0'),
 np.str_('8'),
 np.str_('a'),
 np.str_('b'),
 np.str_('c'),
 np.str_('d'),
 np.str_('e'),
 np.str_('f'),
 np.str_('g'),
 np.str_('h'),
 np.str_('i'),
 np.str_('j'),
 np.str_('k'),
 np.str_('l'),
 np.str_('m'),
 np.str_('n'),
 np.str_('o'),
 np.str_('p'),
 np.str_('q'),
 np.str_('r'),
 np.str_('s'),
 np.str_('t'),
 np.str_('u'),
 np.str_('v'),
 np.str_('w'),
 np.str_('x'),
 np.str_('y'),
 np.str_('z')]

# encode names into numerical format using the mapper you used eariler

In [185]:
names = ["mikhail", "leonidas", "maria"]
seqs = [[char_to_idx(char).numpy().tolist() for char in name] for name in names]
seqs_padded = tf.keras.preprocessing.sequence.pad_sequences(seqs, maxlen=hyper_params["input_shape"], padding='post', truncating='post')
seqs_padded

array([[15, 11, 13, 10,  3, 11, 14,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0],
       [14,  7, 17, 16, 11,  6,  3, 21,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0],
       [15,  3, 20, 11,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0]], dtype=int32)

In [186]:
probs = lstm_model.predict(seqs_padded)
probs

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 240ms/step

array([[0.04733736],
       [0.20695764],
       [0.9556533 ]], dtype=float32)

In [187]:
labels = (probs >= 0.5).astype('int').reshape(-1)
labels

array([0, 0, 1])

In [188]:
v_func = np.vectorize(lambda label: "male" if label == 0 else "female")
decoded_labels = v_func(labels)

In [189]:
decoded_labels.tolist()

['male', 'male', 'female']

In [196]:
def predict_gender(row):
     # extract gender if any
    gender = row["gender"]
    name = row["conn_name"]
    print(f"name: {name}")
    print(f"gender: {gender}")

    # check if null
    if pd.isnull(gender) and not pd.isnull(name) :

        # if split names is ["first name", "last name"]
        # get the first name by split_names[0] if ["first name 1", ..., "first name n", "last name"]
        # get the first name/s by split_names[]
        split_names = name.split()
        print(f"split names: {split_names}")

        if len(split_names) > 2:
            first_names = split_names[:-1]

            # map first names chars to indeces then pad
            seqs = [[char_to_idx(char).numpy().tolist() for char in name] for name in first_names]
            seqs_padded = tf.keras.preprocessing.sequence.pad_sequences(seqs, maxlen=hyper_params["input_shape"], padding='post', truncating='post')
            
            # use padded sequences as input to predictive model
            probs = lstm_model.predict(seqs_padded)

            # calculate the mean probability
            mean_prob = np.mean(probs)
            
            # use preidcted probabilities to convert to scalar values 0 and 1
            label = (mean_prob >= 0.5).astype('int')

            decoded_label = "male" if label == 0 else "female"
            
            print(f"decoded label: {decoded_label}")
            return decoded_label

        # response = requests.post(f"https://genderapi.io/api/?key={api_key}&name={name}")
        # headers = response.headers
        # data = response.json()
        # print(data)
        # print(headers)
        # # data = {}

        # # if request gives a request limit reached error
        # # thus returning a json without hte gender key, just
        # # use an alternative return value of the null value 
        # # of the empty cell
        # return data.get('gender', gender)
    else:
        return row['gender']

In [197]:
temp = conn_info.apply(predict_gender, axis=1)

name: Marcus Paulino
gender: male
name: Jherick Sid Celestial
gender: male
name: Evan Jake Soriano Montano
gender: male
name: Reggielee Capio
gender: male
name: John Carlo Tadeo
gender: male
name: Lorenzo Depone Ii
gender: male
name: Jaya Maia Alcantara
gender: female
name: Jan Laurence Valerio
gender: male
name: Kimberly Pineda
gender: female
name: nan
gender: female
name: nan
gender: female
name: Moira Abesamis
gender: female
name: Rafael Ryan Lloren
gender: male
name: Aishwarya Tanwar
gender: female
name: Lerry Aquino
gender: male
name: Camelle Villarin
gender: female
name: Jules Macalalad
gender: male
name: Bryan Drexler Azarcon
gender: male
name: Christine Marie Mendoza
gender: female
name: Nadine Lacsamana
gender: female
name: Alecs Rodriguez
gender: male
name: Gianne Denise Dueñas
gender: female
name: Camille Eloisa Mendoza
gender: female
name: Airizh Criztal Santos
gender: male
name: Ericson Ramos
gender: male
name: Felix Dulatre
gender: male
name: Aaron Santos
gender: male
name: Herschel Zamir Laminero
gender: male
name: Corinne Supangan
gender: female
name: Kathlyn Pagdanganan
gender: female
name: Trisha Mae Borral
gender: female
name: Noelle Barcenas
gender: female
name: Ma. Angela Lozada
gender: female
name: Vincent Dan Mijares
gender: male
name: Kyle Christopher Atilano
gender: male
name: Jhanina Inotorio
gender: female
name: Giancarlo Tobias
gender: male
name: nan
gender: female
name: John Paul Pormento
gender: male
name: Hazelle Cenon
gender: female
name: Anne Camino
gender: female
name: Arbaz Hussain
gender: male
name: John Manicent Codiniera
gender: male
name: Mia Alcantara
gender: female
name: Allen Dionio
gender: male
name: Erica Zhang
gender: female
name: nan
gender: female
name: Kenneth Joy Loteyro
gender: male
name: Riza Fortunato
gender: male
name: Aisha Locsin Red
gender: female
name: Tedz Ligtvoet
gender: male
name: Chesca Benito
gender: male
name: Iza Elaine Rose Ellego
gender: female
name: Kim Ferrer
gender: female
name: Amiel Ayroso
gender: male
name: Nicole Algire Demonteverde
gender: female
name: Joy Marie Villa
gender: female
name: Janna Tricia Gabriel
gender: male
name: Ruzzel Coronado Clsswb
gender: male
name: Ma. Stephanie Nicole Lim
gender: female
name: nan
gender: female
name: Tania Bondoc
gender: female
name: Adriane Valderrama
gender: female
name: Khea Ronette Noro
gender: male
name: Kyla Lalaine Hugo
gender: male
name: Kyra Marco Luicco De Ynchausti
gender: male
name: France Mercado
gender: female
name: Gabby Jusoy
gender: female
name: Jethro Pamintuan
gender: male
name: Inez Alexandra Alvarez
gender: female
name: Rychelle Himongala
gender: female
name: Ann Caroline Tablada Domasin
gender: female
name: John Rodulph Camizola
gender: male
name: nan
gender: female
name: Paulo Gutierrez
gender: male
name: Angelique Benemerito
gender: female
name: Jenn Dioquino Lsswb
gender: female
name: Eunice Medina
gender: female
name: Alyssa Marie Reyes
gender: female
name: Regine Orozco
gender: female
name: Andrea Martinez
gender: female
name: Agot Reyes
gender: male
name: Rizza Villanueva
gender: female
name: Maricris Cenal
gender: female
name: Philip Mercado
gender: male
name: Raphael Bacaling
gender: male
name: Nirica Kathleen Mavotas
gender: female
name: Ellen Faye Javier
gender: male
name: Nicole Limbo
gender: female
name: Nikka Faola Valle
gender: female
name: Peejay Adlawon
gender: male
name: Roselle Allison Santiago
gender: female
name: Lorraine Jean Sequina
gender: male
name: Scott Vincent Nacua
gender: male
name: Kim Elijah Domingo
gender: female
name: Paolo Parayno
gender: male
name: Jean Carlo Mozo
gender: male
name: Martin Aguilar
gender: male
name: Jevelyn Borjal
gender: female
name: Nemuel Pamplona
gender: male
name: Randy Marjalino
gender: male
name: nan
gender: female
name: Isabelita Wenceslao
gender: male
name: Francoise Bejasa
gender: female
name: Zion Resurreccion
gender: male
name: Chester Symon Fetalcorin
gender: male
name: Evangeline Panganiban
gender: female
name: Ermmellyn May Acupang
gender: female
name: Daniel Sebastian
gender: male
name: Heljine E. Tusio
gender: nan
split names: ['Heljine', 'E.', 'Tusio']
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 254ms/step
decoded label: female
name: Teresa Hastings
gender: female
name: Gillian Cabello Laylo
gender: female
name: Pearl D
gender: female
name: Nilfe Mae Sumagaysay
gender: female
name: Kaiser Antenor
gender: male
name: Katt Villapando
gender: female
name: Jophil Ann Perlado
gender: female
name: nan
gender: female
name: Jewely Opon
gender: female
name: Angelica Bula
gender: female
name: Nathaniel Sevilla
gender: male
name: Catherine "Khite" Cruz
gender: female
name: Kathleen Punzalan
gender: female
name: Reina Yago
gender: male
name: Ragin Marie Baytan
gender: female
name: Maria Ignacia Quesada
gender: female
name: Sarah Jane Padayao
gender: female
name: Ellyka Kischa Williams
gender: male
name: Jam Alcampado
gender: female
name: Francis Sicat
gender: male
name: Ruel Casane
gender: male
name: Arden Caparas
gender: male
name: Toni Monreal
gender: male
name: Criza May Beriong
gender: female
name: Angel P. Figueras Lpt
gender: male
name: Mica Joy Remoquillo
gender: female
name: John Luther Bondoc
gender: male
name: Danielle Dela Cruz
gender: female
name: Aimeh Grace Nono Lazaro
gender: female
name: Doelsie Pagaran Torres
gender: male
name: Karen Elysse Ulpindo
gender: female
name: Jaezelle Reyes
gender: male
name: Marvin Victoria
gender: female
name: Daisy Jane Reas
gender: female
name: Sheena Lee
gender: male
name: Calleene Gabe Pascual
gender: male
name: Fritzie Claire Apale
gender: female
name: Maurich Macatangay
gender: male
name: Aaron Penaco
gender: male
name: Anjelica Matabalan
gender: female
name: Melvin Peralta
gender: male
name: Jia Doble
gender: female
name: Nina Cababa
gender: female
name: Arianne Amio
gender: female
name: Ivee Po
gender: female
name: Cyrelle Rongavilla
gender: female
name: Rhuff Danica Gambong
gender: female
name: Vin Mendoza
gender: male
name: Arci Glodove
gender: male
name: Reiner Arcilla
gender: male
name: Paula Patricia Valentin
gender: female
name: Geraldine Mangune
gender: female
name: Charles Aquino
gender: male
name: Jon Axle Perez
gender: male
name: Shierlyn Curitana Panlilio
gender: female
name: nan
gender: female
name: Julius Cesar Lomarda
gender: male
name: Rich Moscoso
gender: male
name: Nadeth Marquez
gender: male
name: Von Christian Saret
gender: male
name: Andrea Mae Austria
gender: female
name: Mark Aldrin Cose
gender: male
name: Tracy Gregore
gender: female
name: Justin Navarette
gender: male
name: nan
gender: female
name: Tonichi Lamsen
gender: male
name: Ernell Carl Ampit
gender: male
name: Mariko Miranda
gender: female
name: Beverly Hawksworth
gender: female
name: Carlin Therese Tatad
gender: female
name: Clyde Luis Tuazon
gender: male
name: Daniel Binos
gender: male
name: Kathleen Limon
gender: female
name: Rye Dizon
gender: male
name: Renzo Reyes
gender: male
name: Nic Golipapa
gender: male
name: Faith Joyce Martinez
gender: female
name: Jijomer Dacoscos
gender: nan
split names: ['Jijomer', 'Dacoscos']
name: Mico Louis Mañalac
gender: male
name: Renzcy Mendoza
gender: male
name: Darille Galleros
gender: female
name: Lancel Jhon Aris Foster
gender: male
name: Julio Lecocq Chamorro
gender: male
name: Anthony Autor
gender: male
name: Mary Nole Hazel Padagdag
gender: female
name: Angelo Hernandez
gender: male
name: Kirsten Effie Ezra Lachica
gender: female
name: Joyce Ann Calica
gender: female
name: Samantha Gayle Lee
gender: female
name: Glen Kier Garcia Peña
gender: male
name: Marielle Toribio
gender: female
name: Louise Lozano
gender: female
name: Kim An Marie Yap
gender: female
name: Pam Rico Map Cand.
gender: female
name: Sarah Mendoza
gender: female
name: Joe Anne Donato
gender: male
name: Eddie Jr Bacalla
gender: male
name: Jiezzete Ignacio
gender: male
name: nan
gender: female
name: Mary Diane Alcala
gender: female
name: Ricky Beatriz Agbanlog
gender: female
name: Glaiza Luna
gender: female
name: Jc Consuelo
gender: female
name: Mich Cendaña
gender: female
name: Therisa May Bagona
gender: female
name: Alyssa Bela Ong
gender: female
name: Darrel Baliwag
gender: male
name: Andrea Jabat
gender: female
name: Erwin Roy Lopez
gender: male
name: Debbie Anne Marie Ebol
gender: female
name: Frisian Acebo
gender: female
name: nan
gender: female
name: Ellaine Villa
gender: male
name: Celine Anne Buhain
gender: female
name: Dianne Zaira Pingcas
gender: female
name: Jane Bataan
gender: female
name: Via Lhiz Cecille Romualdez
gender: female
name: Joel Per
gender: male
name: Jeremi Anne Ramos
gender: female
name: Mary Bernalyn Therese Ignacio
gender: female
name: Stephany Orjuela
gender: female
name: Vincent Trovela
gender: male
name: Grace Inosanto
gender: female
name: Eunice Bernadette Javier
gender: male
name: Patricia Marie Bobadilla
gender: female
name: Hearthylyn Fiel
gender: male
name: Catherine Santos Magnaye
gender: female
name: Zedrick Ross Paz
gender: male
name: Elijah Gabrielle Malicdem
gender: female
name: Vic Angelo Flores
gender: male
name: Mary Joy Antoc
gender: female
name: Claudine Des
gender: female
name: Jarrid Anne Remulta
gender: female
name: Jana Kristina Mendoza
gender: female
name: Dennis Concepcion
gender: male
name: Liana Rosette Ramos
gender: female
name: Mae Dionson
gender: female
name: Thea Martinez
gender: female
name: Kim Loriel Reyes
gender: female
name: Ervic Jerel Japitana
gender: male
name: Rizamelle Estil
gender: male
name: Kathrine Salvador
gender: male
name: Ed Christian Barrientos
gender: male
name: Ron Rachelle Catuiran
gender: male
name: Clarisa Tallada
gender: female
name: Charmaine Joy Quito
gender: female
name: Eduard Brazil
gender: male
name: Jay Panilag
gender: male
name: Miggy Garcia
gender: male
name: Mark Elliah M. Sanchez
gender: male
name: Paul Gromglieng Grom Li Yeng
gender: male
name: Aerdan Joseph Lacson
gender: male
name: Jennelyn Meñoso
gender: female
name: Ma. Carmela De Juan
gender: male
name: Racquel Abadiez
gender: female
name: James Fernandez
gender: male
name: Dariel Latoza
gender: male
name: Mary Joyce Avendano
gender: female
name: Ave May Mallari
gender: female
name: Carla Antonia Montelibano
gender: female
name: Micah Viado
gender: male
name: Alyssa Christa Cunanan
gender: female
name: Marga Bonilla
gender: female
name: Allyssa Reyes
gender: male
name: Charlene Artes
gender: female
name: Raffy Jay Villapaña
gender: male
name: Matthew De Catalina
gender: male
name: Adrian Joseph
gender: male
name: Mikael John Paras
gender: male
name: Mariah Cristine Tamayo
gender: female
name: Camille Sunga
gender: female
name: Camille Sunga
gender: female
name: Quecel Therese Ordaniel
gender: female
name: Je Ann Cuerbo
gender: female
name: Daniella Mae B.
gender: female
name: Miguel Arceo
gender: male
name: Vin Escalante
gender: male
name: Josh Despuig
gender: male
name: Rachelle Suico
gender: female
name: Janice Alvarez Piastro
gender: female
name: Kennah Bea Cambari
gender: female
name: Kimberly Maniti
gender: female
name: Jeramie Jane Roc
gender: female
name: nan
gender: female
name: Lester Lacsina
gender: male
name: Maria Katrina Guiñares
gender: female
name: Rome Benedicto
gender: male
name: Rebekah Mabaet
gender: female
name: Kim Villamor
gender: female
name: Ariane Sampaga
gender: female
name: Jealyn Duyag Ibo
gender: male
name: Ryan Taboada
gender: male
name: Nomer Calara
gender: male
name: Don King Valdesco
gender: male
name: Mayca Merencillo
gender: female
name: nan
gender: female
name: Christine Isip Arci
gender: female
name: Rence Maynes
gender: male
name: Via Margaret Bumatayo
gender: female
name: Yuih Salvador
gender: male
name: Marc Daniel Melotindos
gender: male
name: nan
gender: female
name: Stephanie Anne Mariano
gender: female
name: Jessicamae Mercado
gender: male
name: Catherine Jane Alhambra
gender: female
name: Rory Rm
gender: male
name: Ellaine Jara
gender: female
name: Ronald Ramas
gender: male
name: Mary Claire Cabanda
gender: female
name: Lorie Loguenario
gender: female
name: Princess Macatuggal
gender: female
name: Princess Yobel Domingo
gender: female
name: Jeanette O
gender: female
name: Patrixia Punzalan
gender: female
name: Rosmel Oropesa
gender: male
name: Shekinah Cuevas
gender: female
name: Dale Schofield
gender: male
name: nan
gender: female
name: Renz Martinez
gender: male
name: Shermie Louize Bryan Herrera
gender: male
name: Shirly Ann Larroder
gender: female
name: Patricia Berenguel
gender: female
name: Ricaport Casanayan
gender: nan
split names: ['Ricaport', 'Casanayan']
name: Neil Andrew Ynacis
gender: male
name: Cristine Valdez
gender: female
name: Folusho Olaniyan
gender: male
name: Christabel San Gabriel Andres
gender: male
name: Jan Marvin Miranda
gender: male
name: Ry Lope
gender: male
name: Yasmin Tubice
gender: female
name: Krystel Flores
gender: female
name: Gerard Lorenzo Dizer Natividad
gender: male
name: Ynah Serrano
gender: female
name: nan
gender: female
name: Rosh Joseph Gador
gender: male
name: Ivern Bernales
gender: male
name: Giandro Pardilla
gender: male
name: Dea Cinco
gender: female
name: Christian Mark Boñola
gender: male
name: John Paulo Arciaga
gender: male
name: Arra Thea Alagad
gender: female
name: Kj Chavez
gender: male
name: nan
gender: female
name: Dianna Marie Platero
gender: female
name: Cams Cabungcal
gender: female
name: Danniel Tongol
gender: male
name: Kristia C.
gender: female
name: Lorena Baez
gender: female
name: Roma Doria Panaligan
gender: male
name: nan
gender: female
name: Jose Marie Mangalino
gender: male
name: Christopher Gonzalez
gender: male
name: Rodella "Leng" Tolentino
gender: male
name: John Marin Moreno Clsswb
gender: male
name: Ma. Joyce Armia
gender: female
name: Jemel Lovino
gender: male
name: Elaine Marion Edaño
gender: female
name: Renel Tibo
gender: male
name: Regine Calibay
gender: female
name: Kams Casas Rodriguez
gender: male
name: Gem Anonuevo
gender: female
name: Lisette Jane Lumberio
gender: female
name: Aubrey Lou Maldonado
gender: male
name: Maria Zarina Antonio
gender: female
name: Ella Tariman
gender: female
name: Audrea Marie Boto
gender: female
name: Baby Jean Arandia
gender: male
name: Abegail Jean Bañez
gender: male
name: Jill Marian
gender: female
name: John Dominic Ocampo
gender: male
name: Oliver Sison
gender: male
name: Jessica Galang
gender: female
name: Kiara Aldover
gender: female
name: Ariel Cole
gender: male
name: Rodolfo Cantongos
gender: male
name: Kei Bryan Dusaban
gender: male
name: Krissia Geramie Mapatac
gender: female
name: Reselyn Jane Alonzo
gender: female
name: nan
gender: female
name: Colene Joice De Leon
gender: male
name: Siara Sangalang
gender: female
name: Eunice Pamela Canilang
gender: female
name: Karl Monteclaro
gender: male
name: Catherine Lavadia
gender: female
name: Anna Carmela Macam
gender: female
name: Lovely Lamptey
gender: female
name: Elvin Eligado
gender: male
name: Janine Erika Manzala
gender: female
name: Sarrah Dulguime
gender: female
name: Zaira Cadampog
gender: female
name: Jema Flor Basilio
gender: female
name: Elaiza Wileman
gender: female
name: Kean Jardin
gender: male
name: Kenneth Ramil
gender: male
name: Camille Catigay
gender: female
name: nan
gender: female
name: Zen Athena Magdasoc
gender: female
name: nan
gender: female
name: Jazeinka Isabella Valdez Pineda
gender: female
name: Ma. Katrina Gracia Sedanto
gender: female
name: El Batuna
gender: male
name: Mark Kevin Garcia
gender: male
name: Arissa Miles Rodriguez
gender: male
name: Quincy Erika Ramos
gender: female
name: Marco Caspillan
gender: male
name: Lawrence Gatpandan
gender: male
name: Anabelle Millena
gender: female
name: Leila Isabel Villamor
gender: female
name: Charisse Ivan De Leon
gender: male
name: Raphael Ventura
gender: male
name: Joylyn Agan
gender: male
name: Rodalyn Orale
gender: female
name: Tine Kris
gender: male
name: Mac Gilfred Uy
gender: male
name: Christine Mae Linatoc
gender: female
name: Jackie Belmonte
gender: female
name: Julian Eric Damian
gender: male
name: Robert Jethro Enriquez
gender: male
name: Mikaela Leigh Padrelanan
gender: female
name: Jhon Remilyn Unciano
gender: male
name: Jamie Jane Quijano Boneo
gender: female
name: Prince Angelo Torres
gender: male
name: Roselyn Achas
gender: female
name: nan
gender: female
name: nan
gender: female
name: Enrisa Lara
gender: female
name: Jade Ancajas
gender: female
name: Currie Orpiano
gender: female
name: Anjelica Joice Pantig Amparo
gender: female
name: Marlon De Mesa
gender: male
name: nan
gender: female
name: Tin Salmurin
gender: female
name: Russell Rogan
gender: male
name: Karl Marx Galado
gender: male
name: Mikee Torre
gender: female
name: Kate Collie Santos
gender: female
name: Trexx Gan
gender: male
name: Az Cabrera Chrp
gender: male
name: John Bendix Mendoza
gender: male
name: Rain Acuesta Chrp
gender: male
name: Ashley Sadine Djandaghi Bautista
gender: female
name: Nowrine Shiena Hossen
gender: female
name: nan
gender: female
name: Carlo Estoconing
gender: male
name: Simon Kim Hirondo
gender: female
name: Carmelo P. Litanon Ii
gender: male
name: Kako Usi
gender: male
name: nan
gender: female
name: Justine Cunanan
gender: female
name: Jorge Pitong
gender: male
name: Cherry Lou Haluag
gender: female
name: Tristan Jerick Reyes
gender: male
name: Patrick Malibunas
gender: male
name: Cess Balbuena
gender: female
name: Maria Christinapaz Parker
gender: female
name: Don Refuerzo
gender: male
name: Glenn De Guzman
gender: male
name: Jv Nebres
gender: nan
split names: ['Jv', 'Nebres']
name: Pol Tahoynon
gender: male
name: Justin Edward Fernandez
gender: male
name: John Laurence Sarmiento
gender: male
name: nan
gender: female
name: nan
gender: female
name: Christian Joseph Garlitos
gender: male
name: nan
gender: female
name: nan
gender: female
name: Paulene Hazelen Gornes
gender: female
name: nan
gender: female
name: Marianne Diocares
gender: female
name: Louisze Jhaede Sanchez
gender: male
name: Ryssel Joy Tumayan
gender: female
name: April Pie Tayong
gender: female
name: Revin Aves Naing
gender: male
name: Kenn Dominic Macarat
gender: male
name: Erika Ray Ramirez
gender: female
name: Angelica Salandanan
gender: female
name: Remegio Madarang Jr
gender: male
name: Meliza Anne Kionisala
gender: female
name: Pamela Pamonag
gender: female
name: Ralph Marwin Loyola
gender: male
name: Emilyn Alonsagay
gender: female
name: Jayrah Cruzado
gender: female
name: Helen Wong
gender: female
name: Clarisse Buenconsejo
gender: female
name: Sophia Mizon
gender: female
name: Angelica Mamaid
gender: female
name: Blessilda Catap
gender: female
name: Equel N.
gender: female
name: Kryzel Ann Oja
gender: female
name: Princess Miñon
gender: female
name: Justine Dela Peña
gender: female
name: Christian Gabriel Villegas
gender: male
name: Kyle Maverick Schaefer
gender: male
name: Maricar B.
gender: female
name: Kamille Gonzales
gender: female
name: Joy Solana
gender: female
name: Hannah Alteza
gender: female
name: Anthony Louissetien Morales
gender: male
name: Marjorie Fonseca
gender: female
name: Rochelle Miguela Angeles
gender: female
name: Mikhaela Malabanan
gender: female
name: Rizamae Milet Austria
gender: female
name: Tel Cadiang
gender: female
name: Trisha Marie Flores
gender: female
name: Jace Villamor
gender: male
name: Abigail Lyle Arquero
gender: female
name: Mary Grace Munoz
gender: female
name: Stefhanie Sapeda
gender: female
name: Shiena Saballo
gender: female
name: Maria Katrina Cuenca
gender: female
name: Yvette Lacson
gender: female
name: Katrina Angela Espiritu
gender: female
name: nan
gender: female
name: Kristian Riz Canama
gender: male
name: Lyndon Ramo Jr
gender: male
name: Leslie Saspa
gender: female
name: Kristine Castilla
gender: female
name: Rizziane Frago
gender: male
name: Angelica Marie Wida
gender: female
name: Tina Caluya
gender: female
name: Elaine Villa Balatero
gender: female
name: Kristelle Ann Villalobos
gender: female
name: Angel Amosin
gender: male
name: Angely May Parel
gender: female
name: Dhea Pineda
gender: female
name: Karina Manzanilla

In [199]:
temp.value_counts()

female    476
male      326
Name: count, dtype: int64

In [200]:
conn_info['gender'] = temp

In [201]:
conn_info.to_csv('../documents/conn_info.csv')