In [29]:
import pandas as pd
from utilities.preprocessors import preprocess

# load dataframe

In [30]:
profiles_dump = pd.read_csv('../documents/profiles_dump.csv', index_col=0)
profiles_dump.tail()

,conn_link,conn_name
441,https://www.linkedin.com/in/gealynpafin/,Gealyn Pafin
442,https://www.linkedin.com/in/mitche-ajesta-rpm-...,"Mitche Ajesta, RPm"
443,https://www.linkedin.com/in/katrina-leyva-997b...,Katrina Leyva
444,https://www.linkedin.com/in/archie-laranang-54...,Archie Laranang
445,https://www.linkedin.com/in/aloicius-justine-k...,Aloicius Justine Kochensparger

In [31]:
profiles_dump['conn_name'] = profiles_dump['conn_name'].apply(preprocess)
profiles_dump.head()

,conn_link,conn_name
0,https://www.linkedin.com/in/mary-andrea-jugo-8...,"[Mary, Andrea, Jugo]"
1,https://www.linkedin.com/in/cheska-tolosa-6044...,"[Cheska, Tolosa]"
2,https://www.linkedin.com/in/zhaira-andrea-mang...,"[Zhaira, Andrea, Manglo,, CRSP]"
3,https://www.linkedin.com/in/zoan-cris-acaso-81...,"[Zoan, Cris, Acaso]"
4,https://www.linkedin.com/in/jayson-lugtu-05655...,"[Jayson, Lugtu]"

In [32]:
profiles_dump.iloc[2]

conn_link    https://www.linkedin.com/in/zhaira-andrea-mang...
conn_name                      [Zhaira, Andrea, Manglo,, CRSP]
Name: 2, dtype: object

In [33]:
for _, row in profiles_dump.iterrows():
    print(row['conn_name'])

TypeError: tuple indices must be integers or slices, not str