In [100]:
import pandas as pd
from utilities.preprocessors import preprocess, assign_gender
from utilities.visualizers import view_rows
from utilities.loaders import load_file

import os
from dotenv import load_dotenv
from pathlib import Path

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [101]:
# load environment variables path
env_dir = Path('../').resolve()
load_dotenv(os.path.join(env_dir, '.env'))

Python-dotenv could not parse statement starting at line 48
Python-dotenv could not parse statement starting at line 54
Python-dotenv could not parse statement starting at line 55
Python-dotenv could not parse statement starting at line 57
Python-dotenv could not parse statement starting at line 59
Python-dotenv could not parse statement starting at line 61
Python-dotenv could not parse statement starting at line 65
Python-dotenv could not parse statement starting at line 66
Python-dotenv could not parse statement starting at line 68
Python-dotenv could not parse statement starting at line 74
Python-dotenv could not parse statement starting at line 75
Python-dotenv could not parse statement starting at line 76
Python-dotenv could not parse statement starting at line 77
Python-dotenv could not parse statement starting at line 80
Python-dotenv could not parse statement starting at line 81
Python-dotenv could not parse statement starting at line 83
Python-dotenv could not parse statement starting at line 87
Python-dotenv could not parse statement starting at line 88
Python-dotenv could not parse statement starting at line 94
Python-dotenv could not parse statement starting at line 95
Python-dotenv could not parse statement starting at line 96
Python-dotenv could not parse statement starting at line 97
Python-dotenv could not parse statement starting at line 98
Python-dotenv could not parse statement starting at line 101
Python-dotenv could not parse statement starting at line 102
Python-dotenv could not parse statement starting at line 104
Python-dotenv could not parse statement starting at line 110
Python-dotenv could not parse statement starting at line 111
Python-dotenv could not parse statement starting at line 112
Python-dotenv could not parse statement starting at line 115
Python-dotenv could not parse statement starting at line 116
Python-dotenv could not parse statement starting at line 118
Python-dotenv could not parse statement starting at line 120
Python-dotenv could not parse statement starting at line 126
Python-dotenv could not parse statement starting at line 127
Python-dotenv could not parse statement starting at line 129
Python-dotenv could not parse statement starting at line 131
Python-dotenv could not parse statement starting at line 133
Python-dotenv could not parse statement starting at line 137
Python-dotenv could not parse statement starting at line 138
Python-dotenv could not parse statement starting at line 140
Python-dotenv could not parse statement starting at line 142
Python-dotenv could not parse statement starting at line 146
Python-dotenv could not parse statement starting at line 147
Python-dotenv could not parse statement starting at line 149
Python-dotenv could not parse statement starting at line 151
Python-dotenv could not parse statement starting at line 153
Python-dotenv could not parse statement starting at line 155
Python-dotenv could not parse statement starting at line 157
Python-dotenv could not parse statement starting at line 161
Python-dotenv could not parse statement starting at line 162
Python-dotenv could not parse statement starting at line 164
Python-dotenv could not parse statement starting at line 166
Python-dotenv could not parse statement starting at line 168
Python-dotenv could not parse statement starting at line 170
Python-dotenv could not parse statement starting at line 176
Python-dotenv could not parse statement starting at line 177
Python-dotenv could not parse statement starting at line 179
Python-dotenv could not parse statement starting at line 181
Python-dotenv could not parse statement starting at line 182
Python-dotenv could not parse statement starting at line 183
Python-dotenv could not parse statement starting at line 185
Python-dotenv could not parse statement starting at line 186
Python-dotenv could not parse statement starting at line 188
Python-dotenv could not parse statement starting at line 189
Python-dotenv could not parse statement starting at line 191
Python-dotenv could not parse statement starting at line 192
Python-dotenv could not parse statement starting at line 194
Python-dotenv could not parse statement starting at line 196
Python-dotenv could not parse statement starting at line 198
Python-dotenv could not parse statement starting at line 200
Python-dotenv could not parse statement starting at line 202
Python-dotenv could not parse statement starting at line 204
Python-dotenv could not parse statement starting at line 207
Python-dotenv could not parse statement starting at line 212
Python-dotenv could not parse statement starting at line 213
Python-dotenv could not parse statement starting at line 217
Python-dotenv could not parse statement starting at line 220
Python-dotenv could not parse statement starting at line 221
Python-dotenv could not parse statement starting at line 223
Python-dotenv could not parse statement starting at line 225
Python-dotenv could not parse statement starting at line 227

True

# load dataframe

In [ ]:
conn_info = pd.read_csv('../documents/conn_info.csv', index_col=0)
conn_info

,email,mobile_no,company_name,conn_link,conn_name,gender,salutation
0,paulinomarcus2914@gmail.com,0,Dyson · Full-time,https://www.linkedin.com/in/paulinomarcus/,Marcus Paulino,NaN,NaN
1,jhericksid15@gmail.com,09294383786 (Home),Cielo Talent · Full-time,https://www.linkedin.com/in/jhericksid/,Jherick Sid Celestial,NaN,NaN
2,EvanJake.Montano@libertymutual.com,+639260328119 (Mobile),Tata Consultancy Services · Full-time,https://www.linkedin.com/in/evanjakesorianomon...,Evan Jake Soriano Montano,NaN,NaN
3,capiorheg@gmail.com,0,JBW Managed Services and Consulting Corp · Ful...,https://www.linkedin.com/in/reggielee-capio-a4...,Reggielee Capio,NaN,NaN
4,johncarlotadeo18@gmail.com,+639432681245 (Mobile),Trojan Recruitment Group · Full-time,https://www.linkedin.com/in/john-carlo-tadeo-2...,John Carlo Tadeo,NaN,NaN
...,...,...,...,...,...,...,...
1065,NaN,0,NaN,NaN,NaN,NaN,NaN
1066,NaN,0,NaN,NaN,NaN,NaN,NaN
1067,NaN,0,NaN,NaN,NaN,NaN,NaN
1068,NaN,0,NaN,NaN,NaN,NaN,NaN
1069,NaN,0,NaN,NaN,NaN,NaN,NaN

In [103]:
conn_info.dtypes

email            object
mobile_no        object
company_name     object
conn_link        object
conn_name        object
gender          float64
salutation      float64
dtype: object

In [104]:
conn_info = conn_info.astype('category')
conn_info

,email,mobile_no,company_name,conn_link,conn_name,gender,salutation
0,paulinomarcus2914@gmail.com,0,Dyson · Full-time,https://www.linkedin.com/in/paulinomarcus/,Marcus Paulino,NaN,NaN
1,jhericksid15@gmail.com,09294383786 (Home),Cielo Talent · Full-time,https://www.linkedin.com/in/jhericksid/,Jherick Sid Celestial,NaN,NaN
2,EvanJake.Montano@libertymutual.com,+639260328119 (Mobile),Tata Consultancy Services · Full-time,https://www.linkedin.com/in/evanjakesorianomon...,Evan Jake Soriano Montano,NaN,NaN
3,capiorheg@gmail.com,0,JBW Managed Services and Consulting Corp · Ful...,https://www.linkedin.com/in/reggielee-capio-a4...,Reggielee Capio,NaN,NaN
4,johncarlotadeo18@gmail.com,+639432681245 (Mobile),Trojan Recruitment Group · Full-time,https://www.linkedin.com/in/john-carlo-tadeo-2...,John Carlo Tadeo,NaN,NaN
...,...,...,...,...,...,...,...
1065,NaN,0,NaN,NaN,NaN,NaN,NaN
1066,NaN,0,NaN,NaN,NaN,NaN,NaN
1067,NaN,0,NaN,NaN,NaN,NaN,NaN
1068,NaN,0,NaN,NaN,NaN,NaN,NaN
1069,NaN,0,NaN,NaN,NaN,NaN,NaN

In [105]:
conn_info['mobile_no'] == "0"

0        True
1       False
2       False
3        True
4       False
        ...
1065     True
1066     True
1067     True
1068     True
1069     True
Name: mobile_no, Length: 1070, dtype: bool

In [106]:
conn_info['gender'].dtype

CategoricalDtype(categories=[], ordered=False, categories_dtype=float64)

In [107]:
pd.isnull(conn_info['gender'])

0       True
1       True
2       True
3       True
4       True
        ...
1065    True
1066    True
1067    True
1068    True
1069    True
Name: gender, Length: 1070, dtype: bool

In [108]:
conn_info['gender'].unique()

[NaN]
Categories (0, float64): []

In [109]:
conn_info['conn_name'] = conn_info['conn_name'].apply(preprocess)
conn_info.head()

Aiza Ricohermoso
Aaron Mitchel Ancheta
Aaron Penaco
Aaron Santos
Abegail Jean Bañez
Abigail Baliwang
Abigail Lyle Arquero
Adrian Joseph
Adriane Valderrama
Aerdan Joseph Lacson
Agot Reyes
Aimeh Grace Nono Lazaro
Aira Batang
Aira Danielle Cacho
Aira Magallon
Airene Ramilo
Airizh Criztal Santos
Aisha Locsin Red
Aishwarya Tanwar
Al Christian Agngarayngay
Al D.
Al John Ezekiel Udtuhan
Al Valencia
Aldrin Astrande
Alecks Alamo
Alecs Rodriguez
Alfred Tolentino
Allan Repalda
Allen Dionio
Allexa Contreras
Alliza Mendoza
Allyssa Reyes
Aloha Ferrer
Aloicius Justine Kochensparger
Alvin Troy Catacutan
Alyanna Monica Coladilla
Alyssa Bela Ong
Alyssa Christa Cunanan
Alyssa Jean Sonza
Alyssa Kirra Macarilay
Alyssa Marie Lansangan
Alyssa Marie Reyes
Alyssa Solitario
Ameera Valdez
Amiel Ayroso
Ana Kathleen Adoc
Ana Marie Simbajon
Anabelle Millena
Andrea Bianca Punzal
Andrea Jabat
Andrea Justiniano
Andrea Mae Austria
Andrea Martinez
Andrea Nicole Odones
Andrea Vasily Gallardo
Angel Amosin
Angel P. Figueras Lpt
Angela Alcantara
Angelica Bula
Angelica Fernandez
Angelica Kolambil
Angelica Mamaid
Angelica Marie Wida
Angelica Salandanan
Angelicca Sadanguel
Angelika Barriga
Angelique Benemerito
Angello Poblete
Angelo Dipay
Angelo Hernandez
Angely May Parel
Anjelica Joice Pantig Amparo
Anjelica Matabalan
Ann Caroline Tablada Domasin
Ann Josenen Regencia
Ann Marimar Porquez
Anna Carmela Macam
Anne Camino
Anne Mariano
Anthony Autor
Anthony Louissetien Morales
April Bautista
April Bea Entac
April Mimi Marcelo
April Pie Tayong
Arbaz Hussain
Archie Laranang
Arci Glodove
Arden Caparas
Arguelito Solpico Jr.
Ariane Sampaga
Arianne Amio
Arianne Faith Pagapulan
Ariel Cole
Arissa Miles Rodriguez
Arline Joannah Suniga
Arra Thea Alagad
Arvin Joseph De Leon
Ashley Sadine Djandaghi Bautista
Aubrey Lou Maldonado
Audrea Marie Boto
Ave May Mallari
Avi O
Az Cabrera Chrp
Benilda Diaz
Baby Jean Arandia
Beatrice Umila
Beejey Jarabe
Bernadette Esteban
Beverly Hawksworth
Beverly Lariosa
Beverly Monungolh
Blessilda Catap
Bran Cruz
Bryan Drexler Azarcon
Bryan Pattaui
Cp Diaz
Calleene Gabe Pascual
Camelle Villarin
Camille Catigay
Camille Eloisa Mendoza
Camille Gandol
Camille Inovio
Camille Sunga
Cams Cabungcal
Carl Javier
Carl Kenneth Alzaga
Carla Antonia Montelibano
Carla Chavez
Carla Lubuguin
Carla Mico
Carlin Therese Tatad
Carlo Angelo Baniaga
Carlo Estoconing
Carmelo P. Litanon Ii
Casey Grandeza
Catherine "Khite" Cruz
Catherine Jane Alhambra
Catherine Lavadia
Catherine Mariano
Catherine Santos Magnaye
Cel Rodriguez
Celine Anne Buhain
Celine F
Cess Balbuena
Charina Ibo
Charisse Ivan De Leon
Charlene Artes
Charles Aquino
Charlize Aberdeen Villa
Charmaine Joy Quito
Chaster Joy Leones
Cherry Lou Haluag
Cheryl Dela Cruz
Chesca Benito
Cheska Tolosa
Chester Symon Fetalcorin
Chinnie Joy Obispo
Christabel San Gabriel Andres
Christell Nicole Barquin
Christian Alicog
Christian Cachola Chrp
Christian Gabriel Villegas
Christian Glendale Fernandez
Christian Joseph Garlitos
Christian Lumanog
Christian Mark Boñola
Christine Ariate
Christine Dianne Ortiz
Christine Isip Arci
Christine Joy Embodo
Christine Joyce Sapoco
Christine Mae Linatoc
Christine Marie Mendoza
Christopher Gonzalez
Christopher Villareal
Ciara Domingo
Cindy Caseda
Claire Anne Oliman
Clarisa Tallada
Clarissa Meneses Chrp
Clarisse Buenconsejo
Claudine Des
Clint Villanueva
Clyde Luis Tuazon
Coleen Gapas
Colene Joice De Leon
Corinne Supangan
Cristell Dioneda
Cristien Angel Mae Bernabe
Cristine Valdez
Criza May Beriong
Currie Orpiano
Cyrelle Rongavilla
Cyril Garcia
Czayra Gabrielle Reyes
David Hofer
Dagami Padillo
Daisy Jane Reas
Dale Gilbert Galindez
Dale Schofield
Danesa Sotomayor Pulido
Daniel Binos
Daniel Sebastian
Daniella Mae B.
Danielle Dela Cruz
Danniel Tongol
Dariel Latoza
Darille Galleros
Darrel Baliwag
Darwin Gasacao
Daryl Anne Centura
Dea Cinco
Deanne Fernando
Debbie Anne Marie Ebol
Dee Marie Joy Dada
Del V.
Demirene Hentoloro
Dennis Concepcion
Dexter Tiamzon
Dhea Pineda
Diana Atienza
Diana Hilario
Diane Grace Dayap
Diane Olano
Dianna Marie Platero
Dianne Kristine Ansula
Dianne Ruth Malinao
Dianne Zaira Pingcas
Diojam Etcobanez
Diosdado Hawang
Doelsie Pagaran Torres
Don King Valdesco
Don Manongsong
Don Refuerzo
Dorina Faye Antonio Torres
Dyan Marie Bautista
Ed Christian Barrientos
Ed Patco
Eddie Jr Bacalla
Eduard Brazil
Efren Flores
Ehmilee Maye Garcia
El Batuna
Elaine Marion Edaño
Elaine Padilla
Elaine Rose Malayo
Elaine Villa Balatero
Elaiza Wileman
Elijah Gabrielle Malicdem
Eliza Joy Fran
Elizabeth Anne Cuvin King
Ella Tariman
Ellaine Jara
Ellaine Villa
Ellen Faye Javier
Ellyka Kischa Williams
Elvin Eligado
Elyssa Joy Peraz
Emilyn Alonsagay
Emmanuel Alfonso Ciencia
Enrisa Lara
Entee Casanova
Equel N.
Eric Jayson Fombo
Erica Zhang
Ericka Mae Tubog
Ericson Ramos
Erika Ray Ramirez
Ermmellyn May Acupang
Ernell Carl Ampit
Ervic Jerel Japitana
Erwin Roy Lopez
Eumir Mondok
Eunice Bernadette Javier
Eunice Medina
Eunice Pamela Canilang
Evan Jake Soriano Montano
Evangeline Panganiban
Faith Joyce Martinez
Faye Emerald Dela Cruz
Felix Dulatre
Fernchesca Aquino
Florence Benette Gallego
Florence Hipolito
Folusho Olaniyan
France Mercado
Francesca Moralejo
Franchesca Oliman
Francis Mah
Francis Sicat
Francoise Bejasa
Frederick Almacen
Frisian Acebo
Fritzie Claire Apale
Gabby Jusoy
Gealyn Pafin
Gela Ga Ang
Gem Anonuevo
Gene Reinier Nieto
Gerald Jetro Abuyan
Gerald Renz Sevilla
Geraldine Mangune
Gerard Lorenzo Dizer Natividad
Geroel James Salvador
Gian Karlo Legaspi
Giancarlo Tobias
Giandro Pardilla
Gianne Denise Dueñas
Gilberly Joy Ablao
Gillian Adria Caballero
Gillian Cabello Laylo
Gimson Mendoza
Gine Garcia
Giza Marie Miciano
Glaiza Español
Glaiza Luna
Glen Kier Garcia Peña
Glen Marquez
Glenn De Guzman
Grace Baldovino
Grace Inosanto
Grace Ysabelle Pascual
Greg Canillas Reyes
Gybon Bajada
Haunch Cristian Tumangan
Hp Diaz
Hannah Alteza
Hannah Camille Santos
Hannah Coleen Nacion
Harsha Bachani
Hasel Francisco
Hazel Kelley
Hazelle Cenon
Hearthylyn Fiel
Hector Sumaoang
Helen Wong
Heljine E. Tusio
Herbert Joey Tuazon
Herschel Zamir Laminero
Ian Añonuevo
Icko Perez
Ilyn Oso
Ina Buena
Inez Alexandra Alvarez
Isabelita Wenceslao
Ishmael Joshua Tungol
Ivan Acuna
Ivan Villaflor
Ivee Po
Ivern Bernales
Ivy Paragas
Iza Elaine Rose Ellego
Jb Dela Cruz
Jace Villamor
Jackie Belmonte
Jade Ancajas
Jaezelle Reyes
Jam Alcampado
Jam Marquez Diola
Jamaica Marie Gaytano
James Fernandez
James Madriaga
James Topacio
Jamie Jane Quijano Boneo
Jan Laurence Valerio
Jan Marie Beltran
Jan Marvin Miranda
Jan Maureen Ariota
Jan Oliver Dimaano
Jan De Guzman
Jana Kristina Mendoza
Jane Bataan
Janice Alvarez Piastro
Janine Alexis Javier
Janine Erika Manzala
Janine Espanol
Janna Tricia Gabriel
Jarrid Anne Remulta
Jason Palinis
Jastin Yap
Jay Panilag
Jay M Villareal
Jaya Maia Alcantara
Jayrah Cruzado
Jayson Callejo
Jayson Lugtu
Jazeinka Isabella Valdez Pineda
Jc Consuelo
Je Ann Cuerbo
Jealyn Duyag Ibo
Jean Carlo Mozo
Jeanette O
Jeanne Jessan Aguilar
Jeff Macapobre
Jem Roche Ballesteros
Jema Flor Basilio
Jemel Lovino
Jenevieve Daz
Jenn Dioquino Lsswb
Jennelyn Meñoso
Jenny Magsino
Jera Aira Santiago
Jeramie Jane Roc
Jeremi Anne Ramos
Jerome Soriano
Jeryl Delaganar
Jess Soriao
Jessica Galang
Jessica Louise Saldaña
Jessicamae Mercado
Jester Dayao
Jethro Pamintuan
Jevelyn Borjal
Jewely Opon
Jex Ashley Antonio
Jezreel Czarina Saygo
Jhanina Inotorio
Jhayz Gratuito
Jherick Sid Celestial
Jhomer Diaz
Jhon Remilyn Unciano
Jia Doble
Jiezzete Ignacio
Jigs Ronquillo
Jijomer Dacoscos
Jill Marian
Joan Sakuma
Joanna Custodio Estrada
Joanna Isabel Montealegre
Jobelyn Estrella
Joe Anne Donato
Joel Per
Joemari Rios
Joemarie Capistrano
Joey Agarao
Joey Rose Briñes
Jogar Bathan
Johanna Perez
John Bendix Mendoza
John Carlo Lim
John Carlo Martinez
John Carlo Sarcia
John Carlo Tadeo
John Christian Mateo
John Daven Torres Clsswb
John Dominic Ocampo
John Emil Adriano
John Jason Odquier
John Kervee Samonte
John Laurence Sarmiento
John Leignard Ragasa
John Louie Del Rosario
John Luther Bondoc
John Manicent Codiniera
John Marin Moreno Clsswb
John Padua
John Panganoron
John Paul Pormento
John Paulo Arciaga
John Reneeric Hernandez
John Rodulph Camizola
John Vincent Sy
John Vincent Tan
Jomar Lerios
Jon Axle Perez
Jona Torres Benzon
Jonalyn Ebit
Jophil Ann Perlado
Jorge Pitong
Jose Maria Galang
Jose Marie Mangalino
Joseph Joshua Donato
Josh Despuig
Joshua Juta
Joshua Kyle S.
Joshua Santiago
Joy Amio
Joy Marie Villa
Joy Solana
Joyce Ann Calica
Joylyn Agan
Jo O Paulo Cunanan
Juan De Leon
Judy Cayabyab
Jules Macalalad
Julia Villaos
Julian Eric Damian
Julio Lecocq Chamorro
Julius Cesar Lomarda
Julius Lee Bacani
Justin Edward Fernandez
Justin Navarette
Justine Cunanan
Justine Dela Peña
Jv Nebres
Kaiser Antenor
Kako Usi
Kamilah Del Rosario
Kamille Gonzales
Kams Casas Rodriguez
Karen Elysse Ulpindo
Karina Manzanilla
Karisse Bernille Labarda
Karl Laurezo
Karl Marx Galado
Karl Monteclaro
Kate Collie Santos
Kate Santos
Katherine Talag
Kathleen Kate Odulio
Kathleen Limon
Kathleen Punzalan
Kathlyn Pagdanganan
Kathrina Telan
Kathrine Salvador
Katlene Kristia Galman
Katreena Marisse Dueñas
Katrina Angela Espiritu
Katrina Leyva
Katt Villapando
Kaye Palmiano
Kaye Peña
Kean Jardin
Keanne Samar
Kei Bryan Dusaban
Kenn Dominic Macarat
Kennah Bea Cambari
Kenneth Joy Loteyro
Kenneth Ramil
Kevin Brylle Santos
Khaye Banguis
Khea Ronette Noro
Khim Mariez Geronimo
Khris Jan Larce
Khristine Gutierrez
Khyle Zybille De Leon
Kiara Aldover
Kijo Menor
Kim An Marie Yap
Kim Elijah Domingo
Kim Ferrer
Kim Loriel Reyes
Kim Villamor
Kimberly Jane Marcial
Kimberly Maniti
Kimberly Pineda
Kirsten Effie Ezra Lachica
Kit Solis
Kj Chavez
Krissia Geramie Mapatac
Kristelle Ann Villalobos
Kristia C.
Kristian Riz Canama
Kristianne Ysabele Capiral
Kristine Angela Caguiat
Kristine Castilla
Kristine Obsioma
Krizzia Aldovino
Krizzia Mercado
Krystel Flores
Krystel Marie Santiago
Kryzel Ann Oja
Kyla Lalaine Hugo
Kyle Christopher Atilano
Kyle Dominique Agramon
Kyle Maverick Schaefer
Kyra Marco Luicco De Ynchausti
Lady Joan Cabilino
Lancel Jhon Aris Foster
Lara Jhecka Orga
Lawrence Gatpandan
Leila Isabel Villamor
Leoric Pabila
Leroid Manahan
Lerry Aquino
Leslie Aquino
Leslie Saspa
Lester John Pacaco
Lester Lacsina
Liana Rosette Ramos
Lisette Jane Lumberio
Liz Cruz
Liza Margaret Caraos
Lloyd Bathan
Loralie Felin
Lorena Baez
Lorenzo Depone Ii
Lorie Loguenario
Lorraine Jean Sequina
Louise Faeldonea
Louise Lozano
Louisze Jhaede Sanchez
Lovely Lamptey
Lovely San Juan
Lovelyn Madriaga
Lyndon Ramo Jr
Mj Visitacion
Ma Samantha Nicole Villanueva
Ma. Angela Lozada
Ma. Carmela De Juan
Ma. Danica Camacho
Ma. Elda Lorca
Ma. Faye Roz
Ma. Joyce Armia
Ma. Katrina Gracia Sedanto
Ma. Messy Carmona
Ma. Stephanie Nicole Lim
Ma. Thelma Flores
Maan Sestona
Mabel Perez
Mac Adornado
Mac Gilfred Uy
Madelaine Ann Bengero
Mae Dionson
Mae Mira
Marc Christian Palisoc
Marc Daniel Melotindos
Marc Jacob Artajos
Marc Stephen Reyes
Marco Caspillan
Marcus Ace Gaitan
Marcus Paulino
Marga Bonilla
Margarett Racho
Maria Anneli Rose Suarez
Maria Christinapaz Parker
Maria Clarissa Felipe
Maria Ignacia Quesada
Maria Katrina Cuenca
Maria Katrina Guiñares
Maria Kristina Monroy
Maria Lourdes Des Gomez Alem Chrp
Maria Rouchelle Manaig
Maria Zarina Antonio
Mariah Cristine Tamayo
Mariah Joy Masinda
Marialyn Real
Marianne Diocares
Marianne Valdez
Maricar B.
Maricel Torres
Maricris Cenal
Marie Centural
Marie Nazareno Reyes
Marie Rhona Maleen Carandang
Mariel Cyra Mendoza
Marielle Toribio
Maries Tan
Marih Jomoc
Mariko Miranda
Marissa Avila
Marissa Esmeria
Marjorie Fonseca
Mark Aldrin Cose
Mark Andrew Mercado
Mark Daniel Povadora
Mark Elliah M. Sanchez
Mark Florian Solano
Mark Kevin Garcia
Mark Pencer Inopiquez
Marlon De Mesa
Marlyn Mag Isa
Martin Aguilar
Marvee Juan
Marvic Marbb Calindro
Marvin Samaniego
Marvin Victoria
Mary Andrea Jugo
Mary Ann Leonida
Mary Bernalyn Therese Ignacio
Mary Claire Cabanda
Mary Diane Alcala
Mary Genova
Mary Grace Munoz
Mary Joy Antoc
Mary Joy Pagulayan
Mary Joy Zamudio
Mary Joyce Avendano
Mary Lou Gobrin
Mary Nole Hazel Padagdag
Mary Rose Balingit
Matthew De Catalina
Maurich Macatangay
Max Evangelista
May Buendia Palabrica
Mayca Merencillo
Maze Enrile Rivera
Megan Rivera
Mehjebin Khan
Meliza Anne Kionisala
Melvin Peralta
Meng Raymundo
Mereden Gamosa
Meredith Nichole Escario
Mia Alcantara
Mia Baylon
Miah Ibañez
Mica Baes
Mica Joy Remoquillo
Micah Viado
Mich Cendaña
Michelle C.
Michelle Matanguihan
Michelle Morales
Michelle Recaña
Micka Alcovindas
Mico Louis Mañalac
Micol Maglalang
Miggy Garcia
Miggy Sy
Miguel Arceo
Mikael John Paras
Mikaela Leigh Padrelanan
Mikee Torre
Mikee Del Prado
Mikhaela Malabanan
Miks Yalong
Mirachael Mendoza
Mitche Ajesta
Moira Abesamis
Noel Gamalindo
Nadeth Marquez
Nadine Lacsamana
Naidinne Lee
Nairie Solante
Nancy Niu
Natasha Myrtle Sasaki
Nathaniel Sevilla
Neil Andrew Ynacis
Nemuel Pamplona
Nerissa Anne Ojales
Nic Golipapa
Nickie Rose Arpon
Nicole Algire Demonteverde
Nicole Capales
Nicole Limbo
Niela Centeno
Nikka Faola Valle
Nikko De La Cerna
Nilfe Mae Sumagaysay
Nina Cababa
Nina Lanante
Nirica Kathleen Mavotas
Niña Katrina Coronel
Niño July Mabilangan
Noel Tarranco
Noelle Noey Pangilinan
Noelle Barcenas
Nomer Calara
Nowrine Shiena Hossen
Oliver Gabuna
Oliver Sison
Pam Rico Map Cand.
Pamela Bianca Co
Pamela Nadine Alvaro Baldovino
Pamela Pamonag
Pamela Yasmin Buluran
Paola Teopiz
Paolo Galve
Paolo Parayno
Paolo Rafael Hulog
Patricia Amor Pam
Patricia Berenguel
Patricia Kate Concepcion
Patricia Marie Bobadilla
Patrick Jovie Alaban
Patrick Malibunas
Patrixia Punzalan
Paul Andrew Taboada
Paul Gromglieng Grom Li Yeng
Paula Marie Gallian
Paula Patricia Valentin
Paula Del Rosario Casas
Paulene Hazelen Gornes
Paulo Gutierrez
Pearl D
Peavey Gail Santos
Peejay Adlawon
Phil Dael
Philip Azur
Philip Mercado
Pol Tahoynon
Prince Angelo Torres
Princess Dalumpines
Princess Helen Delos Santos
Princess Macatuggal
Princess Miñon
Princess Morfe
Princess Yobel Domingo
Quecel Therese Ordaniel
Queenie Onipa
Quin Lawrence Sibonga
Quincey Jugo
Quincy Erika Ramos
Racel Leihart Patricio
Rachelle Alfaro
Rachelle Suico
Racquel Abadiez
Rae Ramirez Chrp
Rafael Ryan Lloren
Raffy Jay Villapaña
Ragin Marie Baytan
Rain Acuesta Chrp
Raleen Aguilar
Ralph Marwin Loyola
Randell Cortez
Randy Marjalino
Raphael Bacaling
Raphael Ventura
Raquel Villafuerte
Raul Badon
Raven Isaac
Raymond De Vera
Raymond Gatchalian
Rebekah Mabaet
Regan Villacastin
Regent Sula Gacusan
Reggie Pascual
Reggielee Capio
Regine Calibay
Regine Orozco
Reina Yago
Reiner Arcilla
Remegio Madarang Jr
Rence Maynes
Renel Tibo
Renz Cristina Garbin
Renz Martinez
Renzcy Mendoza
Renzo Reyes
Reselyn Jane Alonzo
Revin Aves Naing
Rhain De Dios
Rhina Hipolito
Rhoivin Mendoza Ilagan
Rhuff Danica Gambong
Rhuskine Dimla
Rica Niña Camangyan
Ricamay Ballad
Ricaport Casanayan
Rich Moscoso
Richard Justine Corporal
Richmond Babasa
Ricky Beatriz Agbanlog
Rinna Lizza
Riza Fortunato
Rizamae Milet Austria
Rizamelle Estil
Rizza Indig
Rizza Villanueva
Rizziane Frago
Robert Jethro Enriquez
Rochelle Bulan
Rochelle Miguela Angeles
Rochemey Ortiga
Rodalyn Orale
Rodella "Leng" Tolentino
Rodny Selorio
Rodolfo Cantongos
Roma Doria Panaligan
Roma Ramilo
Rome Benedicto
Romel Buenavista
Romel Sayomac
Romina Morallos
Rommel Yumang
Ron Mulleda
Ron Rachelle Catuiran
Ron Richard Ramirez
Rona Jamaica Geronimo
Ronald Ramas
Rory Rm
Roselle Allison Santiago
Roselyn Achas
Roselyn Montances
Rosh Joseph Gador
Rosmel Oropesa
Roy Alegado
Ruel Casane
Russell Rogan
Ruzzel Coronado Clsswb
Ry Lope
Ryan Gilbert Grefiel
Ryan Taboada
Rychelle Himongala
Rye Dizon
Ryssel Joy Tumayan
Sam S.A. Sornito
Samantha Gayle Lee
Sarah Jane Migueh
Sarah Jane Padayao
Sarah Mendoza
Sarheene Khattab
Sarrah Dulguime
Scott Vincent Nacua
Sean Paolo Elarco
Sergius Paulo Vidallon
Severly Suzie Oka
Shae Bernabe
Shainna Delgado
Shane Calub
Sheena Lee
Shekinah Cuevas
Sherilyn Bejar
Shermie Louize Bryan Herrera
Shiena Saballo
Shierlyn Curitana Panlilio
Shirly Ann Larroder
Siara Sangalang
Silviya Georgieva
Simon Kim Hirondo
Socorro Monique Zepeda
Sophia Mizon
Stefhanie Sapeda
Stephanie Anne Mariano
Stephany Orjuela
Talvy Kristine Mae R.
Tania Bondoc
Tedz Ligtvoet
Tel Cadiang
Teresa Hastings
Thea Marivee Rivera
Thea Martinez
Therese Ayra Malones
Therisa May Bagona
Thomas Bernabe
Tin Salmurin
Tina Caluya
Tine Kris
Tito Pascual
Tobit Ibañez Icyb
Toni Monreal
Tonichi Lamsen
Toty Ross Peregrino
Tracy Gregore
Trexx Gan
Tricia Gayle Famadico
Tricia Mae Guan
Triescia Capinpin
Trischia Mae Cabatuan
Trish Teodosio
Trisha Mae Borral
Trisha Marie Flores
Tristan Ivan Chong
Tristan Jerick Reyes
Van Cayabat
Venus Ozarraga
Veronica De Leon
Via Lhiz Cecille Romualdez
Via Margaret Bumatayo
Vic Angelo Flores
Vin Escalante
Vin Mendoza
Vincent Dan Mijares
Vincent Trovela
Von Christian Saret
Wendell Villareal Guidoriagao
Wilma Isidro
Winfred Louis Camello
Xavier Pascual
Yasmin Tubice
Yhing Miranda Manundo
Ynah Serrano
Yohan Nicole Aroja
Yuih Salvador
Yvette Lacson
Zaira Cadampog
Zarah Nicole Dela Vega
Zedrick Ross Paz
Zee Acaso
Zen Athena Magdasoc
Zhaira Andrea Manglo
Zhaira Cosep
Zion Resurreccion
Ayla Paguio

,email,mobile_no,company_name,conn_link,conn_name,gender,salutation
0,paulinomarcus2914@gmail.com,0,Dyson · Full-time,https://www.linkedin.com/in/paulinomarcus/,Marcus Paulino,NaN,NaN
1,jhericksid15@gmail.com,09294383786 (Home),Cielo Talent · Full-time,https://www.linkedin.com/in/jhericksid/,Jherick Sid Celestial,NaN,NaN
2,EvanJake.Montano@libertymutual.com,+639260328119 (Mobile),Tata Consultancy Services · Full-time,https://www.linkedin.com/in/evanjakesorianomon...,Evan Jake Soriano Montano,NaN,NaN
3,capiorheg@gmail.com,0,JBW Managed Services and Consulting Corp · Ful...,https://www.linkedin.com/in/reggielee-capio-a4...,Reggielee Capio,NaN,NaN
4,johncarlotadeo18@gmail.com,+639432681245 (Mobile),Trojan Recruitment Group · Full-time,https://www.linkedin.com/in/john-carlo-tadeo-2...,John Carlo Tadeo,NaN,NaN

In [110]:
view_rows(conn_info, 'conn_name')

Marcus Paulino
Jherick Sid Celestial
Evan Jake Soriano Montano
Reggielee Capio
John Carlo Tadeo
Lorenzo Depone Ii
Jaya Maia Alcantara
Jan Laurence Valerio
Kimberly Pineda
nan
nan
Moira Abesamis
Rafael Ryan Lloren
Aishwarya Tanwar
Lerry Aquino
Camelle Villarin
Jules Macalalad
Bryan Drexler Azarcon
Christine Marie Mendoza
Nadine Lacsamana
Alecs Rodriguez
Gianne Denise Dueñas
Camille Eloisa Mendoza
Airizh Criztal Santos
Ericson Ramos
Felix Dulatre
Aaron Santos
Herschel Zamir Laminero
Corinne Supangan
Kathlyn Pagdanganan
Trisha Mae Borral
Noelle Barcenas
Ma. Angela Lozada
Vincent Dan Mijares
Kyle Christopher Atilano
Jhanina Inotorio
Giancarlo Tobias
nan
John Paul Pormento
Hazelle Cenon
Anne Camino
Arbaz Hussain
John Manicent Codiniera
Mia Alcantara
Allen Dionio
Erica Zhang
nan
Kenneth Joy Loteyro
Riza Fortunato
Aisha Locsin Red
Tedz Ligtvoet
Chesca Benito
Iza Elaine Rose Ellego
Kim Ferrer
Amiel Ayroso
Nicole Algire Demonteverde
Joy Marie Villa
Janna Tricia Gabriel
Ruzzel Coronado Clsswb
Ma. Stephanie Nicole Lim
nan
Tania Bondoc
Adriane Valderrama
Khea Ronette Noro
Kyla Lalaine Hugo
Kyra Marco Luicco De Ynchausti
France Mercado
Gabby Jusoy
Jethro Pamintuan
Inez Alexandra Alvarez
Rychelle Himongala
Ann Caroline Tablada Domasin
John Rodulph Camizola
nan
Paulo Gutierrez
Angelique Benemerito
Jenn Dioquino Lsswb
Eunice Medina
Alyssa Marie Reyes
Regine Orozco
Andrea Martinez
Agot Reyes
Rizza Villanueva
Maricris Cenal
Philip Mercado
Raphael Bacaling
Nirica Kathleen Mavotas
Ellen Faye Javier
Nicole Limbo
Nikka Faola Valle
Peejay Adlawon
Roselle Allison Santiago
Lorraine Jean Sequina
Scott Vincent Nacua
Kim Elijah Domingo
Paolo Parayno
Jean Carlo Mozo
Martin Aguilar
Jevelyn Borjal
Nemuel Pamplona
Randy Marjalino
nan
Isabelita Wenceslao
Francoise Bejasa
Zion Resurreccion
Chester Symon Fetalcorin
Evangeline Panganiban
Ermmellyn May Acupang
Daniel Sebastian
Heljine E. Tusio
Teresa Hastings
Gillian Cabello Laylo
Pearl D
Nilfe Mae Sumagaysay
Kaiser Antenor
Katt Villapando
Jophil Ann Perlado
nan
Jewely Opon
Angelica Bula
Nathaniel Sevilla
Catherine "Khite" Cruz
Kathleen Punzalan
Reina Yago
Ragin Marie Baytan
Maria Ignacia Quesada
Sarah Jane Padayao
Ellyka Kischa Williams
Jam Alcampado
Francis Sicat
Ruel Casane
Arden Caparas
Toni Monreal
Criza May Beriong
Angel P. Figueras Lpt
Mica Joy Remoquillo
John Luther Bondoc
Danielle Dela Cruz
Aimeh Grace Nono Lazaro
Doelsie Pagaran Torres
Karen Elysse Ulpindo
Jaezelle Reyes
Marvin Victoria
Daisy Jane Reas
Sheena Lee
Calleene Gabe Pascual
Fritzie Claire Apale
Maurich Macatangay
Aaron Penaco
Anjelica Matabalan
Melvin Peralta
Jia Doble
Nina Cababa
Arianne Amio
Ivee Po
Cyrelle Rongavilla
Rhuff Danica Gambong
Vin Mendoza
Arci Glodove
Reiner Arcilla
Paula Patricia Valentin
Geraldine Mangune
Charles Aquino
Jon Axle Perez
Shierlyn Curitana Panlilio
nan
Julius Cesar Lomarda
Rich Moscoso
Nadeth Marquez
Von Christian Saret
Andrea Mae Austria
Mark Aldrin Cose
Tracy Gregore
Justin Navarette
nan
Tonichi Lamsen
Ernell Carl Ampit
Mariko Miranda
Beverly Hawksworth
Carlin Therese Tatad
Clyde Luis Tuazon
Daniel Binos
Kathleen Limon
Rye Dizon
Renzo Reyes
Nic Golipapa
Faith Joyce Martinez
Jijomer Dacoscos
Mico Louis Mañalac
Renzcy Mendoza
Darille Galleros
Lancel Jhon Aris Foster
Julio Lecocq Chamorro
Anthony Autor
Mary Nole Hazel Padagdag
Angelo Hernandez
Kirsten Effie Ezra Lachica
Joyce Ann Calica
Samantha Gayle Lee
Glen Kier Garcia Peña
Marielle Toribio
Louise Lozano
Kim An Marie Yap
Pam Rico Map Cand.
Sarah Mendoza
Joe Anne Donato
Eddie Jr Bacalla
Jiezzete Ignacio
nan
Mary Diane Alcala
Ricky Beatriz Agbanlog
Glaiza Luna
Jc Consuelo
Mich Cendaña
Therisa May Bagona
Alyssa Bela Ong
Darrel Baliwag
Andrea Jabat
Erwin Roy Lopez
Debbie Anne Marie Ebol
Frisian Acebo
nan
Ellaine Villa
Celine Anne Buhain
Dianne Zaira Pingcas
Jane Bataan
Via Lhiz Cecille Romualdez
Joel Per
Jeremi Anne Ramos
Mary Bernalyn Therese Ignacio
Stephany Orjuela
Vincent Trovela
Grace Inosanto
Eunice Bernadette Javier
Patricia Marie Bobadilla
Hearthylyn Fiel
Catherine Santos Magnaye
Zedrick Ross Paz
Elijah Gabrielle Malicdem
Vic Angelo Flores
Mary Joy Antoc
Claudine Des
Jarrid Anne Remulta
Jana Kristina Mendoza
Dennis Concepcion
Liana Rosette Ramos
Mae Dionson
Thea Martinez
Kim Loriel Reyes
Ervic Jerel Japitana
Rizamelle Estil
Kathrine Salvador
Ed Christian Barrientos
Ron Rachelle Catuiran
Clarisa Tallada
Charmaine Joy Quito
Eduard Brazil
Jay Panilag
Miggy Garcia
Mark Elliah M. Sanchez
Paul Gromglieng Grom Li Yeng
Aerdan Joseph Lacson
Jennelyn Meñoso
Ma. Carmela De Juan
Racquel Abadiez
James Fernandez
Dariel Latoza
Mary Joyce Avendano
Ave May Mallari
Carla Antonia Montelibano
Micah Viado
Alyssa Christa Cunanan
Marga Bonilla
Allyssa Reyes
Charlene Artes
Raffy Jay Villapaña
Matthew De Catalina
Adrian Joseph
Mikael John Paras
Mariah Cristine Tamayo
Camille Sunga
Camille Sunga
Quecel Therese Ordaniel
Je Ann Cuerbo
Daniella Mae B.
Miguel Arceo
Vin Escalante
Josh Despuig
Rachelle Suico
Janice Alvarez Piastro
Kennah Bea Cambari
Kimberly Maniti
Jeramie Jane Roc
nan
Lester Lacsina
Maria Katrina Guiñares
Rome Benedicto
Rebekah Mabaet
Kim Villamor
Ariane Sampaga
Jealyn Duyag Ibo
Ryan Taboada
Nomer Calara
Don King Valdesco
Mayca Merencillo
nan
Christine Isip Arci
Rence Maynes
Via Margaret Bumatayo
Yuih Salvador
Marc Daniel Melotindos
nan
Stephanie Anne Mariano
Jessicamae Mercado
Catherine Jane Alhambra
Rory Rm
Ellaine Jara
Ronald Ramas
Mary Claire Cabanda
Lorie Loguenario
Princess Macatuggal
Princess Yobel Domingo
Jeanette O
Patrixia Punzalan
Rosmel Oropesa
Shekinah Cuevas
Dale Schofield
nan
Renz Martinez
Shermie Louize Bryan Herrera
Shirly Ann Larroder
Patricia Berenguel
Ricaport Casanayan
Neil Andrew Ynacis
Cristine Valdez
Folusho Olaniyan
Christabel San Gabriel Andres
Jan Marvin Miranda
Ry Lope
Yasmin Tubice
Krystel Flores
Gerard Lorenzo Dizer Natividad
Ynah Serrano
nan
Rosh Joseph Gador
Ivern Bernales
Giandro Pardilla
Dea Cinco
Christian Mark Boñola
John Paulo Arciaga
Arra Thea Alagad
Kj Chavez
nan
Dianna Marie Platero
Cams Cabungcal
Danniel Tongol
Kristia C.
Lorena Baez
Roma Doria Panaligan
nan
Jose Marie Mangalino
Christopher Gonzalez
Rodella "Leng" Tolentino
John Marin Moreno Clsswb
Ma. Joyce Armia
Jemel Lovino
Elaine Marion Edaño
Renel Tibo
Regine Calibay
Kams Casas Rodriguez
Gem Anonuevo
Lisette Jane Lumberio
Aubrey Lou Maldonado
Maria Zarina Antonio
Ella Tariman
Audrea Marie Boto
Baby Jean Arandia
Abegail Jean Bañez
Jill Marian
John Dominic Ocampo
Oliver Sison
Jessica Galang
Kiara Aldover
Ariel Cole
Rodolfo Cantongos
Kei Bryan Dusaban
Krissia Geramie Mapatac
Reselyn Jane Alonzo
nan
Colene Joice De Leon
Siara Sangalang
Eunice Pamela Canilang
Karl Monteclaro
Catherine Lavadia
Anna Carmela Macam
Lovely Lamptey
Elvin Eligado
Janine Erika Manzala
Sarrah Dulguime
Zaira Cadampog
Jema Flor Basilio
Elaiza Wileman
Kean Jardin
Kenneth Ramil
Camille Catigay
nan
Zen Athena Magdasoc
nan
Jazeinka Isabella Valdez Pineda
Ma. Katrina Gracia Sedanto
El Batuna
Mark Kevin Garcia
Arissa Miles Rodriguez
Quincy Erika Ramos
Marco Caspillan
Lawrence Gatpandan
Anabelle Millena
Leila Isabel Villamor
Charisse Ivan De Leon
Raphael Ventura
Joylyn Agan
Rodalyn Orale
Tine Kris
Mac Gilfred Uy
Christine Mae Linatoc
Jackie Belmonte
Julian Eric Damian
Robert Jethro Enriquez
Mikaela Leigh Padrelanan
Jhon Remilyn Unciano
Jamie Jane Quijano Boneo
Prince Angelo Torres
Roselyn Achas
nan
nan
Enrisa Lara
Jade Ancajas
Currie Orpiano
Anjelica Joice Pantig Amparo
Marlon De Mesa
nan
Tin Salmurin
Russell Rogan
Karl Marx Galado
Mikee Torre
Kate Collie Santos
Trexx Gan
Az Cabrera Chrp
John Bendix Mendoza
Rain Acuesta Chrp
Ashley Sadine Djandaghi Bautista
Nowrine Shiena Hossen
nan
Carlo Estoconing
Simon Kim Hirondo
Carmelo P. Litanon Ii
Kako Usi
nan
Justine Cunanan
Jorge Pitong
Cherry Lou Haluag
Tristan Jerick Reyes
Patrick Malibunas
Cess Balbuena
Maria Christinapaz Parker
Don Refuerzo
Glenn De Guzman
Jv Nebres
Pol Tahoynon
Justin Edward Fernandez
John Laurence Sarmiento
nan
nan
Christian Joseph Garlitos
nan
nan
Paulene Hazelen Gornes
nan
Marianne Diocares
Louisze Jhaede Sanchez
Ryssel Joy Tumayan
April Pie Tayong
Revin Aves Naing
Kenn Dominic Macarat
Erika Ray Ramirez
Angelica Salandanan
Remegio Madarang Jr
Meliza Anne Kionisala
Pamela Pamonag
Ralph Marwin Loyola
Emilyn Alonsagay
Jayrah Cruzado
Helen Wong
Clarisse Buenconsejo
Sophia Mizon
Angelica Mamaid
Blessilda Catap
Equel N.
Kryzel Ann Oja
Princess Miñon
Justine Dela Peña
Christian Gabriel Villegas
Kyle Maverick Schaefer
Maricar B.
Kamille Gonzales
Joy Solana
Hannah Alteza
Anthony Louissetien Morales
Marjorie Fonseca
Rochelle Miguela Angeles
Mikhaela Malabanan
Rizamae Milet Austria
Tel Cadiang
Trisha Marie Flores
Jace Villamor
Abigail Lyle Arquero
Mary Grace Munoz
Stefhanie Sapeda
Shiena Saballo
Maria Katrina Cuenca
Yvette Lacson
Katrina Angela Espiritu
nan
Kristian Riz Canama
Lyndon Ramo Jr
Leslie Saspa
Kristine Castilla
Rizziane Frago
Angelica Marie Wida
Tina Caluya
Elaine Villa Balatero
Kristelle Ann Villalobos
Angel Amosin
Angely May Parel
Dhea Pineda
Karina Manzanilla
Kristine Obsioma
Joemari Rios
Angelika Barriga
nan
nan
Oliver Gabuna
Mae Mira
Megan Rivera
Mary Andrea Jugo
Cheska Tolosa
Zhaira Andrea Manglo
Zee Acaso
Jayson Lugtu
Ricamay Ballad
Marvic Marbb Calindro
Veronica De Leon
Rodny Selorio
Madelaine Ann Bengero
Anne Mariano
Mary Lou Gobrin
Glaiza Español
Micol Maglalang
Rochemey Ortiga
Jenny Magsino
Francis Mah
Yhing Miranda Manundo
Rhuskine Dimla
Kathleen Kate Odulio
Maria Rouchelle Manaig
nan
Xavier Pascual
Ana Kathleen Adoc
Rizza Indig
nan
Judy Cayabyab
nan
Nancy Niu
Khaye Banguis
nan
Chaster Joy Leones
Romina Morallos
Jem Roche Ballesteros
Harsha Bachani
Jess Soriao
Daryl Anne Centura
nan
Icko Perez
Beatrice Umila
nan
Reggie Pascual
Julia Villaos
Princess Dalumpines
Triescia Capinpin
Airene Ramilo
Trischia Mae Cabatuan
Alyssa Marie Lansangan
Joshua Kyle S.
nan
Arline Joannah Suniga
Kamilah Del Rosario
Ann Josenen Regencia
Jayson Callejo
Kyle Dominique Agramon
Ayla Paguio
Renz Cristina Garbin
Maricel Torres
Allexa Contreras
Joshua Juta
nan
Mj Visitacion
Romel Sayomac
Gerald Jetro Abuyan
Mary Rose Balingit
Ian Añonuevo
Herbert Joey Tuazon
Ma. Thelma Flores
nan
Marie Centural
Jan Marie Beltran
nan
Jonalyn Ebit
Del V.
Paolo Galve
Michelle Recaña
Joey Rose Briñes
Hazel Kelley
Roma Ramilo
Celine F
Karisse Bernille Labarda
Alvin Troy Catacutan
Claire Anne Oliman
Mark Florian Solano
Therese Ayra Malones
Mark Andrew Mercado
nan
Eliza Joy Fran
Ma. Danica Camacho
Zhaira Cosep
Ann Marimar Porquez
Casey Grandeza
Richard Justine Corporal
Joy Amio
Jeff Macapobre
Diane Grace Dayap
Hannah Camille Santos
Angelica Kolambil
Ed Patco
Roy Alegado
nan
Ivy Paragas
Czayra Gabrielle Reyes
Liz Cruz
Christine Joy Embodo
Sergius Paulo Vidallon
Paula Marie Gallian
Marissa Esmeria
Princess Helen Delos Santos
nan
John Louie Del Rosario
Lovelyn Madriaga
Jan De Guzman
Rica Niña Camangyan
Gian Karlo Legaspi
Diana Atienza
Catherine Mariano
Angelo Dipay
John Carlo Lim
nan
Loralie Felin
Darwin Gasacao
nan
Elyssa Joy Peraz
nan
Hector Sumaoang
Aira Magallon
Tito Pascual
Andrea Vasily Gallardo
Aldrin Astrande
Niela Centeno
nan
Kit Solis
Florence Hipolito
Ma. Elda Lorca
nan
Francesca Moralejo
nan
Raquel Villafuerte
John Emil Adriano
Wendell Villareal Guidoriagao
Ron Richard Ramirez
Raven Isaac
Kristianne Ysabele Capiral
Mac Adornado
Dianne Kristine Ansula
Paul Andrew Taboada
Jeryl Delaganar
Beverly Lariosa
Patricia Amor Pam
Maria Anneli Rose Suarez
Khim Mariez Geronimo
Beverly Monungolh
Rhina Hipolito
Nina Lanante
Khris Jan Larce
Diane Olano
Ana Marie Simbajon
Jb Dela Cruz
Bernadette Esteban
Randell Cortez
Maze Enrile Rivera
Marialyn Real
Nicole Capales
April Mimi Marcelo
Eric Jayson Fombo
Juan De Leon
Richmond Babasa
Regan Villacastin
Ishmael Joshua Tungol
Al Christian Agngarayngay
John Carlo Sarcia
Faye Emerald Dela Cruz
Kijo Menor
Gerald Renz Sevilla
Niña Katrina Coronel
Allan Repalda
Paola Teopiz
Quin Lawrence Sibonga
Ivan Acuna
Joan Sakuma
Venus Ozarraga
Alyssa Kirra Macarilay
Clarissa Meneses Chrp
John Jason Odquier
Rochelle Bulan
Van Cayabat
Noel Gamalindo
Ameera Valdez
nan
Patrick Jovie Alaban
Ericka Mae Tubog
Patricia Kate Concepcion
John Vincent Tan
Leroid Manahan
Silviya Georgieva
Jam Marquez Diola
Kate Santos
Christian Lumanog
Mary Genova
Dexter Tiamzon
Elizabeth Anne Cuvin King
nan
Giza Marie Miciano
Camille Gandol
Ma Samantha Nicole Villanueva
Bryan Pattaui
John Reneeric Hernandez
Entee Casanova
Jex Ashley Antonio
Rae Ramirez Chrp
nan
Jenevieve Daz
Alfred Tolentino
Christopher Villareal
Raymond De Vera
Joshua Santiago
Michelle Morales
Aiza Ricohermoso
Sam S.A. Sornito
Rommel Yumang
Roselyn Montances
Tristan Ivan Chong
Regent Sula Gacusan
Jhomer Diaz
Emmanuel Alfonso Ciencia
Mary Ann Leonida
Christine Dianne Ortiz
Ciara Domingo
nan
Miks Yalong
Hp Diaz
Marie Nazareno Reyes
Alyssa Jean Sonza
Camille Inovio
Thea Marivee Rivera
Marc Stephen Reyes
Meredith Nichole Escario
Christian Alicog
Florence Benette Gallego
Diosdado Hawang
Racel Leihart Patricio
Karl Laurezo
Jeanne Jessan Aguilar
Max Evangelista
John Leignard Ragasa
Ma. Messy Carmona
Hannah Coleen Nacion
Marlyn Mag Isa
Toty Ross Peregrino
Dyan Marie Bautista
Al D.
Ma. Faye Roz
Louise Faeldonea
Thomas Bernabe
Niño July Mabilangan
Dianne Ruth Malinao
Princess Morfe
nan
nan
nan
Noelle Noey Pangilinan
John Kervee Samonte
Cristell Dioneda
Pamela Nadine Alvaro Baldovino
Leslie Aquino
Joanna Custodio Estrada
Gilberly Joy Ablao
nan
May Buendia Palabrica
Mark Daniel Povadora
Jona Torres Benzon
Elaine Rose Malayo
Krizzia Aldovino
Angelica Fernandez
Carla Mico
Joanna Isabel Montealegre
Michelle C.
Rhoivin Mendoza Ilagan
Ron Mulleda
Rinna Lizza
nan
Lester John Pacaco
Pamela Bianca Co
Alyanna Monica Coladilla
Arguelito Solpico Jr.
Angello Poblete
Quincey Jugo
Severly Suzie Oka
Angela Alcantara
Maria Lourdes Des Gomez Alem Chrp
Carl Javier
Aira Danielle Cacho
Nickie Rose Arpon
Mikee Del Prado
Kathrina Telan
Andrea Nicole Odones
Leoric Pabila
Tricia Gayle Famadico
Jomar Lerios
Krizzia Mercado
Noel Tarranco
Kimberly Jane Marcial
Ina Buena
Marvee Juan
Clint Villanueva
Gybon Bajada
Jerome Soriano
Sarah Jane Migueh
Cindy Caseda
Margarett Racho
Dale Gilbert Galindez
John Vincent Sy
Marc Jacob Artajos
Katreena Marisse Dueñas
Meng Raymundo
Nikko De La Cerna
Jezreel Czarina Saygo
Janine Alexis Javier
Marie Rhona Maleen Carandang
Elaine Padilla
Jessica Louise Saldaña
Ivan Villaflor
Don Manongsong
Paula Del Rosario Casas
Lloyd Bathan
Gela Ga Ang
Marc Christian Palisoc
Krystel Marie Santiago
Andrea Bianca Punzal
Queenie Onipa
Philip Azur
Natasha Myrtle Sasaki
Sherilyn Bejar
Frederick Almacen
Maries Tan
David Hofer
Franchesca Oliman
Jogar Bathan
Charina Ibo
nan
Tobit Ibañez Icyb
nan
John Panganoron
nan
Maria Clarissa Felipe
Geroel James Salvador
Andrea Justiniano
Christian Glendale Fernandez
Dee Marie Joy Dada
Aloha Ferrer
Cel Rodriguez
Mirachael Mendoza
Miggy Sy
Arianne Faith Pagapulan
Gillian Adria Caballero
Jamaica Marie Gaytano
Paolo Rafael Hulog
Eumir Mondok
Cheryl Dela Cruz
Lovely San Juan
Pamela Yasmin Buluran
Deanne Fernando
Joey Agarao
Micka Alcovindas
Fernchesca Aquino
Diojam Etcobanez
Jose Maria Galang
Coleen Gapas
Bran Cruz
Mary Joy Pagulayan
Mabel Perez
Marvin Samaniego
Shane Calub
Wilma Isidro
Shae Bernabe
Carlo Angelo Baniaga
Ilyn Oso
Hasel Francisco
Raleen Aguilar
Aira Batang
Aaron Mitchel Ancheta
Janine Espanol
James Madriaga
Jhayz Gratuito
Sean Paolo Elarco
Jera Aira Santiago
Romel Buenavista
Christell Nicole Barquin
Shainna Delgado
Sarheene Khattab
Joseph Joshua Donato
Marcus Ace Gaitan
Marih Jomoc
Kristine Angela Caguiat
Gine Garcia
Mia Baylon
Al Valencia
Michelle Matanguihan
Danesa Sotomayor Pulido
John Carlo Martinez
Jan Maureen Ariota
Liza Margaret Caraos
Carla Chavez
Demirene Hentoloro
nan
Arvin Joseph De Leon
Beejey Jarabe
Jobelyn Estrella
nan
Maan Sestona
John Christian Mateo
Nerissa Anne Ojales
Diana Hilario
Lady Joan Cabilino
Trish Teodosio
Nairie Solante
Johanna Perez
Cristien Angel Mae Bernabe
Gene Reinier Nieto
Christine Joyce Sapoco
Kaye Peña
John Padua
Khyle Zybille De Leon
Greg Canillas Reyes
Mehjebin Khan
Dagami Padillo
nan
Christian Cachola Chrp
Benilda Diaz
Yohan Nicole Aroja
Julius Lee Bacani
Angelicca Sadanguel
Avi O
Raul Badon
Cyril Garcia
Jason Palinis
Efren Flores
Mary Joy Zamudio
James Topacio
Grace Ysabelle Pascual
Gealyn Pafin
Mitche Ajesta
Katrina Leyva
Archie Laranang
Aloicius Justine Kochensparger
Raymond Gatchalian
Kaye Palmiano
Kevin Brylle Santos
Al John Ezekiel Udtuhan
Glen Marquez
Gimson Mendoza
Talvy Kristine Mae R.
Naidinne Lee
Mereden Gamosa
Miah Ibañez
Alliza Mendoza
Alecks Alamo
Khristine Gutierrez
Rachelle Alfaro
Grace Baldovino
Tricia Mae Guan
Ryan Gilbert Grefiel
Mark Pencer Inopiquez
nan
Haunch Cristian Tumangan
Keanne Samar
Marianne Valdez
Jester Dayao
Peavey Gail Santos
Rona Jamaica Geronimo
Katherine Talag
Phil Dael
Jay M Villareal
Jan Oliver Dimaano
Carl Kenneth Alzaga
Alyssa Solitario
Cp Diaz
April Bea Entac
Christine Ariate
Joemarie Capistrano
Mariel Cyra Mendoza
Charlize Aberdeen Villa
Marissa Avila
Mariah Joy Masinda
Winfred Louis Camello
Maria Kristina Monroy
Katlene Kristia Galman
Chinnie Joy Obispo
Lara Jhecka Orga
Jastin Yap
Socorro Monique Zepeda
Zarah Nicole Dela Vega
Mica Baes
Abigail Baliwang
Rhain De Dios
Jo O Paulo Cunanan
Carla Lubuguin
Ehmilee Maye Garcia
John Daven Torres Clsswb
Jigs Ronquillo
Dorina Faye Antonio Torres
April Bautista
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan

In [111]:
conn_info

,email,mobile_no,company_name,conn_link,conn_name,gender,salutation
0,paulinomarcus2914@gmail.com,0,Dyson · Full-time,https://www.linkedin.com/in/paulinomarcus/,Marcus Paulino,NaN,NaN
1,jhericksid15@gmail.com,09294383786 (Home),Cielo Talent · Full-time,https://www.linkedin.com/in/jhericksid/,Jherick Sid Celestial,NaN,NaN
2,EvanJake.Montano@libertymutual.com,+639260328119 (Mobile),Tata Consultancy Services · Full-time,https://www.linkedin.com/in/evanjakesorianomon...,Evan Jake Soriano Montano,NaN,NaN
3,capiorheg@gmail.com,0,JBW Managed Services and Consulting Corp · Ful...,https://www.linkedin.com/in/reggielee-capio-a4...,Reggielee Capio,NaN,NaN
4,johncarlotadeo18@gmail.com,+639432681245 (Mobile),Trojan Recruitment Group · Full-time,https://www.linkedin.com/in/john-carlo-tadeo-2...,John Carlo Tadeo,NaN,NaN
...,...,...,...,...,...,...,...
1065,NaN,0,NaN,NaN,NaN,NaN,NaN
1066,NaN,0,NaN,NaN,NaN,NaN,NaN
1067,NaN,0,NaN,NaN,NaN,NaN,NaN
1068,NaN,0,NaN,NaN,NaN,NaN,NaN
1069,NaN,0,NaN,NaN,NaN,NaN,NaN

In [112]:
conn_info['gender'] = conn_info['gender'].astype('float')
conn_info['gender']

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
1065   NaN
1066   NaN
1067   NaN
1068   NaN
1069   NaN
Name: gender, Length: 1070, dtype: float64

In [113]:
conn_info.dtypes

email           category
mobile_no       category
company_name    category
conn_link       category
conn_name       category
gender           float64
salutation      category
dtype: object

In [114]:
temp = conn_info.apply(assign_gender, args=(os.environ['GENDER_API_KEY'], ), axis=1)
temp

nan
{'status': True, 'used_credits': 1, 'remaining_credits': 195, 'expires': 1733267100, 'q': 'Marcus Paulino', 'name': 'marcus', 'gender': 'male', 'country': 'US', 'total_names': 17142, 'probability': 100, 'duration': '9ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:26 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '200', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"c8-yFBkIUrbocWH1JoFEvgfG8llB4A"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 194, 'expires': 1733267100, 'q': 'Jherick Sid Celestial', 'name': 'sid', 'gender': 'male', 'country': 'US', 'total_names': 1625, 'probability': 92, 'duration': '8ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:27 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '202', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"ca-WIo8+bgPfr+zbY9+F4I/9j5t/ag"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 193, 'expires': 1733267100, 'q': 'Evan Jake Soriano Montano', 'name': 'jake', 'gender': 'male', 'country': 'US', 'total_names': 16557, 'probability': 99, 'duration': '11ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:28 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '209', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"d1-c2+Kwj2Z90cHPim34KBv+l1LYoE"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 192, 'expires': 1733267100, 'q': 'Reggielee Capio', 'name': 'capio', 'gender': 'male', 'country': 'FR', 'total_names': 2, 'probability': 100, 'duration': '7ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:29 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '196', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"c4-sZ14bj8iWPv8/XYxM32GybR/u4M"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 191, 'expires': 1733267100, 'q': 'John Carlo Tadeo', 'name': 'john', 'gender': 'male', 'country': 'US', 'total_names': 116219, 'probability': 99, 'duration': '7ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:29 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '200', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"c8-NnkioyMBjO8eju72Qc+4Xg1bkJ8"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 190, 'expires': 1733267100, 'q': 'Lorenzo Depone Ii', 'name': 'lorenzo', 'gender': 'male', 'country': 'IT', 'total_names': 7779, 'probability': 100, 'duration': '6ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:30 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '203', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"cb-wFYh457oZ33sXJ12PWcx+3FH72g"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 189, 'expires': 1733267100, 'q': 'Jaya Maia Alcantara', 'name': 'maia', 'gender': 'female', 'country': 'US', 'total_names': 1544, 'probability': 95, 'duration': '6ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:31 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '203', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"cb-Rz/mKIep672fvzBSwuazIkZkMmY"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 188, 'expires': 1733267100, 'q': 'Jan Laurence Valerio', 'name': 'jan', 'gender': 'male', 'country': 'US', 'total_names': 21716, 'probability': 79, 'duration': '9ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:32 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '202', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"ca-pmkmtZriHAohVdZSrXXoTeXffJg"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 187, 'expires': 1733267100, 'q': 'Kimberly Pineda', 'name': 'kimberly', 'gender': 'female', 'country': 'US', 'total_names': 21427, 'probability': 100, 'duration': '7ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:32 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '205', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"cd-7R9cLax4/vLIOXt44Bf+5xROSKU"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 186, 'expires': 1733267100, 'q': 'nan', 'name': 'nan', 'gender': 'female', 'country': 'TH', 'total_names': 3527, 'probability': 86, 'duration': '7ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:33 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '186', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"ba-VwZVCdVvsEgMJbGE4UH+4bE8NTg"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 185, 'expires': 1733267100, 'q': 'nan', 'name': 'nan', 'gender': 'female', 'country': 'TH', 'total_names': 3527, 'probability': 86, 'duration': '6ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:34 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '186', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"ba-hO0Sgcnrum8VpVQBAWaEQBLBWaE"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 184, 'expires': 1733267100, 'q': 'Moira Abesamis', 'name': 'moira', 'gender': 'female', 'country': 'US', 'total_names': 684, 'probability': 100, 'duration': '6ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:35 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '199', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"c7-gTtE5ukORT4X+NANsKXR3fWgeHw"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 183, 'expires': 1733267100, 'q': 'Rafael Ryan Lloren', 'name': 'ryan', 'gender': 'male', 'country': 'US', 'total_names': 71043, 'probability': 98, 'duration': '6ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:35 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '201', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"c9-nVi1zu0LeUyypvai4S6nspmIAwc"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 182, 'expires': 1733267100, 'q': 'Aishwarya Tanwar', 'name': 'aishwarya', 'gender': 'female', 'country': 'IN', 'total_names': 418, 'probability': 93, 'duration': '6ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:36 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '204', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"cc-dfabGIL/M0mrcoLUoIKj8odqBbs"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 181, 'expires': 1733267100, 'q': 'Lerry Aquino', 'name': 'lerry', 'gender': 'male', 'country': 'ID', 'total_names': 120, 'probability': 80, 'duration': '6ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:37 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '194', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"c2-Sg//oEQoDppqZDRbiKZwhT/M4C0"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 180, 'expires': 1733267100, 'q': 'Camelle Villarin', 'name': 'camelle', 'gender': 'female', 'country': 'US', 'total_names': 18, 'probability': 100, 'duration': '6ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:38 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '202', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"ca-MVtJbHHK6aLwPUeTKSkoscsMAwU"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 179, 'expires': 1733267100, 'q': 'Jules Macalalad', 'name': 'jules', 'gender': 'male', 'country': 'US', 'total_names': 2513, 'probability': 57, 'duration': '10ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:38 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '199', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"c7-2aq+Ki62cEXq0fCWnZX+MnByDyI"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 178, 'expires': 1733267100, 'q': 'Bryan Drexler Azarcon', 'name': 'bryan', 'gender': 'male', 'country': 'US', 'total_names': 25765, 'probability': 100, 'duration': '7ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:39 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '206', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"ce-CJAHkDRrXB1HHAvaLI5zi/DZEoY"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 177, 'expires': 1733267100, 'q': 'Christine Marie Mendoza', 'name': 'christine', 'gender': 'female', 'country': 'US', 'total_names': 26229, 'probability': 100, 'duration': '6ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:40 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '214', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"d6-L0sgZWCvoXoOzEqoHLuZ7Y1OTPo"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 176, 'expires': 1733267100, 'q': 'Nadine Lacsamana', 'name': 'nadine', 'gender': 'female', 'country': 'US', 'total_names': 4638, 'probability': 100, 'duration': '6ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:41 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '203', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"cb-rWhzKf3BKZpfD4jj672zFiqoRFE"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 175, 'expires': 1733267100, 'q': 'Alecs Rodriguez', 'name': 'alecs', 'gender': 'male', 'country': 'RO', 'total_names': 187, 'probability': 79, 'duration': '5ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:41 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '197', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"c5-dvlWBgUHw/aI4gNzLAUXhHamUcg"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 174, 'expires': 1733267100, 'q': 'Gianne Denise Dueñas', 'name': 'denise', 'gender': 'female', 'country': 'US', 'total_names': 20604, 'probability': 99, 'duration': '7ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:42 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '208', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"d0-kuGvH87tr4xv8ZL9tlmuiX4GSMQ"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 173, 'expires': 1733267100, 'q': 'Camille Eloisa Mendoza', 'name': 'camille', 'gender': 'female', 'country': 'US', 'total_names': 7153, 'probability': 95, 'duration': '6ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:43 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '209', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"d1-6LD2t/VDLAt0aeriOPqRdS9s+Mw"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 172, 'expires': 1733267100, 'q': 'Airizh Criztal Santos', 'name': 'santos', 'gender': 'male', 'country': 'US', 'total_names': 1260, 'probability': 92, 'duration': '7ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:44 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '205', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"cd-qQzSaHtgNhQhvbkx3C1aI0hBAeY"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 171, 'expires': 1733267100, 'q': 'Ericson Ramos', 'name': 'ericson', 'gender': 'male', 'country': 'BR', 'total_names': 408, 'probability': 99, 'duration': '7ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:44 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '197', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"c5-u7s1H+FSvpBEiTxMadycDkrQb4c"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 170, 'expires': 1733267100, 'q': 'Felix Dulatre', 'name': 'felix', 'gender': 'male', 'country': 'US', 'total_names': 9549, 'probability': 99, 'duration': '7ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:45 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '196', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"c4-pKCm2uoGxfs++PiwAYDzVvEApdo"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 169, 'expires': 1733267100, 'q': 'Aaron Santos', 'name': 'aaron', 'gender': 'male', 'country': 'US', 'total_names': 32918, 'probability': 99, 'duration': '8ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:46 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '196', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"c4-GSo5UibhvfwMfTNo2xWpRb0pd2A"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 168, 'expires': 1733267100, 'q': 'Herschel Zamir Laminero', 'name': 'zamir', 'gender': 'male', 'country': 'MY', 'total_names': 320, 'probability': 98, 'duration': '9ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:47 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '205', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"cd-i9Z2e9LTGpUhMgYYqTwkksBoNR8"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 167, 'expires': 1733267100, 'q': 'Corinne Supangan', 'name': 'corinne', 'gender': 'female', 'country': 'US', 'total_names': 2114, 'probability': 99, 'duration': '9ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:47 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '203', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"cb-6dB6PZ8ANkI64g7cMCZr857cXJk"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 166, 'expires': 1733267100, 'q': 'Kathlyn Pagdanganan', 'name': 'kathlyn', 'gender': 'female', 'country': 'US', 'total_names': 214, 'probability': 99, 'duration': '9ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:48 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '205', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"cd-D51qWl+qKKC44i8vygLZuZOAsjk"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 165, 'expires': 1733267100, 'q': 'Trisha Mae Borral', 'name': 'trisha', 'gender': 'female', 'country': 'US', 'total_names': 3501, 'probability': 100, 'duration': '8ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:49 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '204', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"cc-D1v6qeiaRk3IYWxLfsgK77EDE0s"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 164, 'expires': 1733267100, 'q': 'Noelle Barcenas', 'name': 'noelle', 'gender': 'female', 'country': 'US', 'total_names': 1691, 'probability': 99, 'duration': '8ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:50 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '201', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"c9-JpHgdBzn3ok1pcIq+1DEKcc8S3k"'}
nan
{'status': True, 'used_credits': 1, 'remaining_credits': 163, 'expires': 1733267100, 'q': 'Ma. Angela Lozada', 'name': 'angela', 'gender': 'female', 'country': 'US', 'total_names': 37162, 'probability': 99, 'duration': '10ms'}
{'Server': 'nginx/1.18.0 (Ubuntu)', 'Date': 'Tue, 03 Dec 2024 06:08:50 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '205', 'Connection': 'keep-alive', 'X-Powered-By': 'Express', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Headers': 'Origin, X-Requested-With, Content-Type, Accept', 'ETag': 'W/"cd-RdmOJypxPUH96Ohd4VytuwyjiT0"'}
nan

0       male
1       male
2       male
3       male
4       male
        ...
1065     NaN
1066     NaN
1067     NaN
1068     NaN
1069     NaN
Length: 1070, dtype: object

In [116]:
temp.unique()

array(['male', 'female', 'null', nan], dtype=object)

In [117]:
conn_info['gender'] = temp

In [118]:
conn_info.dtypes

email           category
mobile_no       category
company_name    category
conn_link       category
conn_name       category
gender            object
salutation      category
dtype: object

In [119]:
conn_info.to_csv('../documents/conn_info.csv')