In [8]:
import pandas as pd
from utilities.preprocessors import preprocess, assign_gender
from utilities.visualizers import view_rows
from utilities.loaders import load_file

import os
from dotenv import load_dotenv
from pathlib import Path

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [9]:
# load environment variables path
env_dir = Path('../').resolve()
load_dotenv(os.path.join(env_dir, '.env'))

True

# load dataframe

In [10]:
profiles_dump = pd.read_csv('../documents/profiles_dump.csv', index_col=0)
profiles_dump.tail()

,conn_link,conn_name,gender,salutation,email,mobile_no,company_name
458,https://www.linkedin.com/in/gealynpafin/,Gealyn Pafin,NaN,NaN,NaN,0.0,NaN
459,https://www.linkedin.com/in/mitche-ajesta-rpm-...,"Mitche Ajesta, RPm",NaN,NaN,NaN,0.0,NaN
460,https://www.linkedin.com/in/katrina-leyva-997b...,Katrina Leyva,NaN,NaN,NaN,0.0,NaN
461,https://www.linkedin.com/in/archie-laranang-54...,Archie Laranang,NaN,NaN,NaN,0.0,NaN
462,https://www.linkedin.com/in/aloicius-justine-k...,Aloicius Justine Kochensparger,NaN,NaN,NaN,0.0,NaN

In [11]:
profiles_dump['conn_name'] = profiles_dump['conn_name'].apply(preprocess)
profiles_dump.head()

Rizziane Frago
Angelica Marie Wida
Tina Caluya
Elaine Villa Balatero
Kristelle Ann Villalobos
Angel Amosin
Angely May Parel
Dhea Pineda
Karina Manzanilla
Kristine Obsioma
Joemari Rios
Angelika Barriga
Jerrome Alcarmen
Maria Althea Espinosa
Oliver Gabuna
Mae Mira
Megan Rivera
Mary Andrea Jugo
Cheska Tolosa
Zhaira Andrea Manglo
Zoan Cris Acaso
Jayson Lugtu
Ricamay Ballad
Marvic Marbb Calindro
Veronica De Leon
Rodny Selorio
Madelaine Ann Bengero
Anne Mariano
Mary Lou Gobrin
Glaiza Español
Micol Maglalang
Rochemey Ortiga
Jenny Magsino
Francis Mah
Yhing Miranda Manundo
Rhuskine Dimla
Kathleen Kate Odulio
Maria Rouchelle Manaig
Sueshem Tudtud
Xavier Pascual
Ana Kathleen Adoc
Rizza Indig
Anton Roxas
Judy Cayabyab
Aby Aquino
Nancy Niu
Khaye Banguis
Joy Rivera
Chaster Joy Leones
Romina Morallos
Jem Roche Ballesteros
Harsha Bachani
Jess Soriao
Daryl Anne Centura
Kristine G.
Icko Perez
Beatrice Umila
Roseann Cisnero
Reggie Pascual
Julia Villaos
Princess Dalumpines
Triescia Capinpin
Airene Ramilo
Trischia Mae Cabatuan
Alyssa Marie Lansangan
Joshua Kyle S.
Wilma David
Arline Joannah Suniga
Kamilah Del Rosario
Ann Josenen Regencia
Jayson Callejo
Kyle Dominique Agramon
Ayla Paguio
Renz Cristina Garbin
Maricel Torres
Allexa Contreras
Joshua Juta
Anna Paulyn Pagunsan
Mj Visitacion
Romel Sayomac
Gerald Jetro Abuyan
Mary Rose Balingit
Ian Añonuevo
Herbert Joey Tuazon
Ma. Thelma Flores
Kimberly Montillano
Marie Centural
Jan Marie Beltran
Franki
Jonalyn Ebit
Del V.
Paolo Galve
Michelle Recaña
Joey Rose Briñes
Hazel Kelley
Roma Ramilo
Celine F
Karisse Bernille Labarda
Alvin Troy Catacutan
Claire Anne Oliman
Mark Florian Solano
Therese Ayra Malones
Mark Andrew Mercado
Leo Rueda
Eliza Joy Fran
Ma. Danica Camacho
Zhaira Cosep
Ann Marimar Porquez
Casey Grandeza
Richard Justine Corporal
Joy Amio
Jeff Macapobre
Diane Grace Dayap
Hannah Camille Santos
Angelica Kolambil
Ed Patco
Roy Alegado
Amor Maligat
Ivy Paragas
Czayra Gabrielle Reyes
Liz Cruz
Christine Joy Embodo
Sergius Paulo Vidallon
Paula Marie Gallian
Marissa Esmeria
Princess Helen Delos Santos
Cherry Lou Quicoy
John Louie Del Rosario
Lovelyn Madriaga
Jan De Guzman
Rica Niña Camangyan
Gian Karlo Legaspi
Diana Atienza
Catherine Mariano
Angelo Dipay
John Carlo Lim
Angeline Bona Naron
Loralie Felin
Darwin Gasacao
Kim Malibiran
Elyssa Joy Peraz
Claire Chavez
Hector Sumaoang
Aira Magallon
Tito Pascual
Andrea Vasily Gallardo
Aldrin Astrande
Niela Centeno
Ben Trapal
Kit Solis
Florence Hipolito
Ma. Elda Lorca
Francis Charles Damondamon
Francesca Moralejo
Peter Jr. Hizon
Raquel Villafuerte
John Emil Adriano
Wendell Villareal Guidoriagao
Ron Richard Ramirez
Raven Isaac
Kristianne Ysabele Capiral
Mac Adornado
Dianne Kristine Ansula
Paul Andrew Taboada
Jeryl Delaganar
Beverly Lariosa
Patricia Amor Pam
Maria Anneli Rose Suarez
Khim Mariez Geronimo
Beverly Monungolh
Rhina Hipolito
Nina Graye Sean Lanante
Khris Jan Larce
Diane Olano
Ana Marie Simbajon
Jb Dela Cruz
Bernadette Esteban
Randell Cortez
Maze Enrile Rivera
Marialyn Real
Nicole Capales
April Mimi Marcelo
Eric Jayson Fombo
Juan De Leon
Richmond Babasa
Regan Villacastin
Ishmael Joshua Tungol
Al Christian Agngarayngay
John Carlo Sarcia
Faye Emerald Dela Cruz
Kijo Menor
Gerald Renz Sevilla
Niña Katrina Coronel
Allan Repalda
Paola Teopiz
Quin Lawrence Sibonga
Ivan Acuna
Joan Sakuma
Venus Ozarraga
Alyssa Kirra Macarilay
Clarissa Meneses Chrp
John Jason Odquier
Rochelle Bulan
Van Cayabat
Noel Gamalindo
Ameera Valdez
Shiela Roaring
Patrick Jovie Alaban
Ericka Mae Tubog
Patricia Kate Concepcion
John Vincent Tan
Leroid Manahan
Silviya Georgieva
Jam Marquez Diola
Kate Santos
Christian Lumanog
Mary Genova
Dexter Tiamzon
Elizabeth Anne Cuvin King
Jhunelle Erica Abrigo
Giza Marie Miciano
Camille Gandol
Ma Samantha Nicole Villanueva
Bryan Pattaui
John Reneeric Hernandez
Entee Casanova
Jex Ashley Antonio
Rae Ramirez Chrp
Samantha Ma. Geriline Bagorio
Jenevieve Daz
Alfred Tolentino
Christopher Villareal
Raymond De Vera
Joshua Santiago
Michelle Morales
Aiza Ricohermoso
Sam S.A. Sornito
Rommel Yumang
Roselyn Montances
Tristan Ivan Chong
Regent Sula Gacusan
Jhomer Diaz
Emmanuel Alfonso Ciencia
Mary Ann Leonida
Christine Dianne Ortiz
Ciara Domingo
John Paul Bandong
Miks Yalong
Hp Diaz
Marie Nazareno Reyes
Alyssa Jean Sonza
Camille Inovio
Thea Marivee Rivera
Marc Stephen Reyes
Meredith Nichole Escario
Christian Alicog
Florence Benette Gallego
Diosdado Hawang
Racel Leihart Patricio
Karl Laurezo
Jeanne Jessan Aguilar
Max Evangelista
John Leignard Ragasa
Ma. Messy Carmona
Hannah Coleen Nacion
Marlyn Mag Isa
Toty Ross Peregrino
Dyan Marie Bautista
Al D.
Ma. Faye Roz
Louise Faeldonea
Thomas Bernabe
Niño July Mabilangan
Dianne Ruth Malinao
Princess Morfe
Jc Digamon
Lady Charo Cadiz
Mp Baba
Noelle Noey Pangilinan
John Kervee Samonte
Cristell Dioneda
Pamela Nadine Alvaro Baldovino
Leslie Aquino
Joanna Custodio Estrada
Gilberly Joy Ablao
Steffi Jan Padilla
May Buendia Palabrica
Mark Daniel Povadora
Jona Torres Benzon
Elaine Rose Malayo
Krizzia Aldovino
Angelica Fernandez
Carla Mico
Joanna Isabel Montealegre
Michelle C.
Rhoivin Mendoza Ilagan
Ron Mulleda
Rinna Lizza
Maria Arabelle Olegario
Lester John Pacaco
Pamela Bianca Co
Alyanna Monica Coladilla
Arguelito Solpico Jr.
Angello Poblete
Quincey Jugo
Severly Suzie Oka
Angela Alcantara
Maria Lourdes Des Gomez Alem Chrp
Carl Javier
Aira Danielle Cacho
Nickie Rose Arpon
Mikee Del Prado
Kathrina Telan
Andrea Nicole Odones
Leoric Pabila
Tricia Gayle Famadico
Jomar Lerios
Krizzia Mercado
Noel Tarranco
Kimberly Jane Marcial
Ina Buena
Marvee Juan
Clint Villanueva
Gybon Bajada
Jerome Soriano
Sarah Jane Migueh
Cindy Caseda
Margarett Racho
Dale Gilbert Galindez
John Vincent Sy
Marc Jacob Artajos
Katreena Marisse Dueñas
Meng Raymundo
Nikko De La Cerna
Jezreel Czarina Saygo
Janine Alexis Javier
Marie Rhona Maleen Carandang
Elaine Padilla
Jessica Louise Saldaña
Ivan Villaflor
Don Manongsong
Paula Del Rosario Casas
Lloyd Bathan
Gela Ga Ang
Marc Christian Palisoc
Krystel Marie Santiago
Andrea Bianca Punzal
Queenie Onipa
Philip Azur
Natasha Myrtle Sasaki
Sherilyn Bejar
Frederick Almacen
Maries Tan
David Hofer
Franchesca Oliman
Jogar Bathan
Charina Ibo
Sophia Ysabela Angeles
Tobit Ibañez
Ericka Joyce Bea
John Panganoron
Kimberly Buena
Maria Clarissa Felipe
Geroel James Salvador
Andrea Justiniano
Christian Glendale Fernandez
Dee Marie Joy Dada
Aloha Ferrer
Cel Rodriguez
Mirachael Mendoza
Miggy Sy
Arianne Faith Pagapulan
Gillian Adria Caballero
Jamaica Marie Gaytano
Paolo Rafael Hulog
Eumir Mondok
Cheryl Dela Cruz
Lovely San Juan
Pamela Yasmin Buluran
Deanne Fernando
Joey A.
Micka Alcovindas
Fernchesca Aquino
Diojam Etcobanez
Jose Maria Galang
Coleen Gapas
Bran Cruz
Mary Joy Pagulayan
Mabel Perez
Marvin Samaniego
Shane Calub
Wilma Isidro
Shae Bernabe
Carlo Angelo Baniaga
Ilyn Oso
Hasel Francisco
Raleen Aguilar
Aira Batang
Aaron Mitchel Ancheta
Janine Espanol
James Madriaga
Jhayz Gratuito
Sean Paolo Elarco
Jera Aira Santiago
Romel Buenavista
Christell Nicole Barquin
Shainna Delgado
Sarheene Khattab
Joseph Joshua Donato
Marcus Ace Gaitan
Marih Jomoc
Kristine Angela Caguiat
Gine Garcia
Mia Baylon
Al Valencia
Michelle Matanguihan
Danesa Sotomayor Pulido
John Carlo Martinez
Jan Maureen Ariota
Liza Margaret Caraos
Carla Chavez
Demirene Hentoloro
Arthel Espiritu Santo
Arvin Joseph De Leon
Beejey Jarabe
Jobelyn Estrella
Arvin Bajar
Maan Sestona
John Christian Mateo
Nerissa Anne Palo
Diana Hilario
Lady Joan Cabilino
Trish Teodosio
Nairie Solante
Johanna Perez
Cristien Angel Mae Bernabe
Gene Reinier Nieto
Christine Joyce Sapoco
Kaye Peña
John Padua
Khyle Zybille De Leon
Greg Canillas Reyes
Mehjebin Khan
Dagami Padillo
Nina Stephanie Tanawit
Christian Cachola Chrp
Benilda Diaz
Yohan Nicole Aroja
Julius Lee Bacani
Angelicca Sadanguel
Avi O
Raul Badon
Cyril Garcia
Jason Palinis
Efren Flores
Mary Joy Zamudio
James Topacio
Grace Ysabelle Pascual
Gealyn Pafin
Mitche Ajesta
Katrina Leyva
Archie Laranang
Aloicius Justine Kochensparger

,conn_link,conn_name,gender,salutation,email,mobile_no,company_name
0,https://www.linkedin.com/in/rmbf2222/,Rizziane Frago,NaN,NaN,NaN,0.0,NaN
1,https://www.linkedin.com/in/angelica-marie-wid...,Angelica Marie Wida,NaN,NaN,NaN,0.0,NaN
2,https://www.linkedin.com/in/tina-caluya-9b917a...,Tina Caluya,NaN,NaN,NaN,0.0,NaN
3,https://www.linkedin.com/in/elainevilla/,Elaine Villa Balatero,NaN,NaN,NaN,0.0,NaN
4,https://www.linkedin.com/in/kristelle-ann-vill...,Kristelle Ann Villalobos,NaN,NaN,NaN,0.0,NaN

In [12]:
profiles_dump.iloc[2]

conn_link       https://www.linkedin.com/in/tina-caluya-9b917a...
conn_name                                             Tina Caluya
gender                                                        NaN
salutation                                                    NaN
email                                                         NaN
mobile_no                                                     0.0
company_name                                                  NaN
Name: 2, dtype: object

In [13]:
view_rows(profiles_dump, 'conn_name')

Rizziane Frago
Angelica Marie Wida
Tina Caluya
Elaine Villa Balatero
Kristelle Ann Villalobos
Angel Amosin
Angely May Parel
Dhea Pineda
Karina Manzanilla
Kristine Obsioma
Joemari Rios
Angelika Barriga
Jerrome Alcarmen
Maria Althea Espinosa
Oliver Gabuna
Mae Mira
Megan Rivera
Mary Andrea Jugo
Cheska Tolosa
Zhaira Andrea Manglo
Zoan Cris Acaso
Jayson Lugtu
Ricamay Ballad
Marvic Marbb Calindro
Veronica De Leon
Rodny Selorio
Madelaine Ann Bengero
Anne Mariano
Mary Lou Gobrin
Glaiza Español
Micol Maglalang
Rochemey Ortiga
Jenny Magsino
Francis Mah
Yhing Miranda Manundo
Rhuskine Dimla
Kathleen Kate Odulio
Maria Rouchelle Manaig
Sueshem Tudtud
Xavier Pascual
Ana Kathleen Adoc
Rizza Indig
Anton Roxas
Judy Cayabyab
Aby Aquino
Nancy Niu
Khaye Banguis
Joy Rivera
Chaster Joy Leones
Romina Morallos
Jem Roche Ballesteros
Harsha Bachani
Jess Soriao
Daryl Anne Centura
Kristine G.
Icko Perez
Beatrice Umila
Roseann Cisnero
Reggie Pascual
Julia Villaos
Princess Dalumpines
Triescia Capinpin
Airene Ramilo
Trischia Mae Cabatuan
Alyssa Marie Lansangan
Joshua Kyle S.
Wilma David
Arline Joannah Suniga
Kamilah Del Rosario
Ann Josenen Regencia
Jayson Callejo
Kyle Dominique Agramon
Ayla Paguio
Renz Cristina Garbin
Maricel Torres
Allexa Contreras
Joshua Juta
Anna Paulyn Pagunsan
Mj Visitacion
Romel Sayomac
Gerald Jetro Abuyan
Mary Rose Balingit
Ian Añonuevo
Herbert Joey Tuazon
Ma. Thelma Flores
Kimberly Montillano
Marie Centural
Jan Marie Beltran
Franki
Jonalyn Ebit
Del V.
Paolo Galve
Michelle Recaña
Joey Rose Briñes
Hazel Kelley
Roma Ramilo
Celine F
Karisse Bernille Labarda
Alvin Troy Catacutan
Claire Anne Oliman
Mark Florian Solano
Therese Ayra Malones
Mark Andrew Mercado
Leo Rueda
Eliza Joy Fran
Ma. Danica Camacho
Zhaira Cosep
Ann Marimar Porquez
Casey Grandeza
Richard Justine Corporal
Joy Amio
Jeff Macapobre
Diane Grace Dayap
Hannah Camille Santos
Angelica Kolambil
Ed Patco
Roy Alegado
Amor Maligat
Ivy Paragas
Czayra Gabrielle Reyes
Liz Cruz
Christine Joy Embodo
Sergius Paulo Vidallon
Paula Marie Gallian
Marissa Esmeria
Princess Helen Delos Santos
Cherry Lou Quicoy
John Louie Del Rosario
Lovelyn Madriaga
Jan De Guzman
Rica Niña Camangyan
Gian Karlo Legaspi
Diana Atienza
Catherine Mariano
Angelo Dipay
John Carlo Lim
Angeline Bona Naron
Loralie Felin
Darwin Gasacao
Kim Malibiran
Elyssa Joy Peraz
Claire Chavez
Hector Sumaoang
Aira Magallon
Tito Pascual
Andrea Vasily Gallardo
Aldrin Astrande
Niela Centeno
Ben Trapal
Kit Solis
Florence Hipolito
Ma. Elda Lorca
Francis Charles Damondamon
Francesca Moralejo
Peter Jr. Hizon
Raquel Villafuerte
John Emil Adriano
Wendell Villareal Guidoriagao
Ron Richard Ramirez
Raven Isaac
Kristianne Ysabele Capiral
Mac Adornado
Dianne Kristine Ansula
Paul Andrew Taboada
Jeryl Delaganar
Beverly Lariosa
Patricia Amor Pam
Maria Anneli Rose Suarez
Khim Mariez Geronimo
Beverly Monungolh
Rhina Hipolito
Nina Graye Sean Lanante
Khris Jan Larce
Diane Olano
Ana Marie Simbajon
Jb Dela Cruz
Bernadette Esteban
Randell Cortez
Maze Enrile Rivera
Marialyn Real
Nicole Capales
April Mimi Marcelo
Eric Jayson Fombo
Juan De Leon
Richmond Babasa
Regan Villacastin
Ishmael Joshua Tungol
Al Christian Agngarayngay
John Carlo Sarcia
Faye Emerald Dela Cruz
Kijo Menor
Gerald Renz Sevilla
Niña Katrina Coronel
Allan Repalda
Paola Teopiz
Quin Lawrence Sibonga
Ivan Acuna
Joan Sakuma
Venus Ozarraga
Alyssa Kirra Macarilay
Clarissa Meneses Chrp
John Jason Odquier
Rochelle Bulan
Van Cayabat
Noel Gamalindo
Ameera Valdez
Shiela Roaring
Patrick Jovie Alaban
Ericka Mae Tubog
Patricia Kate Concepcion
John Vincent Tan
Leroid Manahan
Silviya Georgieva
Jam Marquez Diola
Kate Santos
Christian Lumanog
Mary Genova
Dexter Tiamzon
Elizabeth Anne Cuvin King
Jhunelle Erica Abrigo
Giza Marie Miciano
Camille Gandol
Ma Samantha Nicole Villanueva
Bryan Pattaui
John Reneeric Hernandez
Entee Casanova
Jex Ashley Antonio
Rae Ramirez Chrp
Samantha Ma. Geriline Bagorio
Jenevieve Daz
Alfred Tolentino
Christopher Villareal
Raymond De Vera
Joshua Santiago
Michelle Morales
Aiza Ricohermoso
Sam S.A. Sornito
Rommel Yumang
Roselyn Montances
Tristan Ivan Chong
Regent Sula Gacusan
Jhomer Diaz
Emmanuel Alfonso Ciencia
Mary Ann Leonida
Christine Dianne Ortiz
Ciara Domingo
John Paul Bandong
Miks Yalong
Hp Diaz
Marie Nazareno Reyes
Alyssa Jean Sonza
Camille Inovio
Thea Marivee Rivera
Marc Stephen Reyes
Meredith Nichole Escario
Christian Alicog
Florence Benette Gallego
Diosdado Hawang
Racel Leihart Patricio
Karl Laurezo
Jeanne Jessan Aguilar
Max Evangelista
John Leignard Ragasa
Ma. Messy Carmona
Hannah Coleen Nacion
Marlyn Mag Isa
Toty Ross Peregrino
Dyan Marie Bautista
Al D.
Ma. Faye Roz
Louise Faeldonea
Thomas Bernabe
Niño July Mabilangan
Dianne Ruth Malinao
Princess Morfe
Jc Digamon
Lady Charo Cadiz
Mp Baba
Noelle Noey Pangilinan
John Kervee Samonte
Cristell Dioneda
Pamela Nadine Alvaro Baldovino
Leslie Aquino
Joanna Custodio Estrada
Gilberly Joy Ablao
Steffi Jan Padilla
May Buendia Palabrica
Mark Daniel Povadora
Jona Torres Benzon
Elaine Rose Malayo
Krizzia Aldovino
Angelica Fernandez
Carla Mico
Joanna Isabel Montealegre
Michelle C.
Rhoivin Mendoza Ilagan
Ron Mulleda
Rinna Lizza
Maria Arabelle Olegario
Lester John Pacaco
Pamela Bianca Co
Alyanna Monica Coladilla
Arguelito Solpico Jr.
Angello Poblete
Quincey Jugo
Severly Suzie Oka
Angela Alcantara
Maria Lourdes Des Gomez Alem Chrp
Carl Javier
Aira Danielle Cacho
Nickie Rose Arpon
Mikee Del Prado
Kathrina Telan
Andrea Nicole Odones
Leoric Pabila
Tricia Gayle Famadico
Jomar Lerios
Krizzia Mercado
Noel Tarranco
Kimberly Jane Marcial
Ina Buena
Marvee Juan
Clint Villanueva
Gybon Bajada
Jerome Soriano
Sarah Jane Migueh
Cindy Caseda
Margarett Racho
Dale Gilbert Galindez
John Vincent Sy
Marc Jacob Artajos
Katreena Marisse Dueñas
Meng Raymundo
Nikko De La Cerna
Jezreel Czarina Saygo
Janine Alexis Javier
Marie Rhona Maleen Carandang
Elaine Padilla
Jessica Louise Saldaña
Ivan Villaflor
Don Manongsong
Paula Del Rosario Casas
Lloyd Bathan
Gela Ga Ang
Marc Christian Palisoc
Krystel Marie Santiago
Andrea Bianca Punzal
Queenie Onipa
Philip Azur
Natasha Myrtle Sasaki
Sherilyn Bejar
Frederick Almacen
Maries Tan
David Hofer
Franchesca Oliman
Jogar Bathan
Charina Ibo
Sophia Ysabela Angeles
Tobit Ibañez
Ericka Joyce Bea
John Panganoron
Kimberly Buena
Maria Clarissa Felipe
Geroel James Salvador
Andrea Justiniano
Christian Glendale Fernandez
Dee Marie Joy Dada
Aloha Ferrer
Cel Rodriguez
Mirachael Mendoza
Miggy Sy
Arianne Faith Pagapulan
Gillian Adria Caballero
Jamaica Marie Gaytano
Paolo Rafael Hulog
Eumir Mondok
Cheryl Dela Cruz
Lovely San Juan
Pamela Yasmin Buluran
Deanne Fernando
Joey A.
Micka Alcovindas
Fernchesca Aquino
Diojam Etcobanez
Jose Maria Galang
Coleen Gapas
Bran Cruz
Mary Joy Pagulayan
Mabel Perez
Marvin Samaniego
Shane Calub
Wilma Isidro
Shae Bernabe
Carlo Angelo Baniaga
Ilyn Oso
Hasel Francisco
Raleen Aguilar
Aira Batang
Aaron Mitchel Ancheta
Janine Espanol
James Madriaga
Jhayz Gratuito
Sean Paolo Elarco
Jera Aira Santiago
Romel Buenavista
Christell Nicole Barquin
Shainna Delgado
Sarheene Khattab
Joseph Joshua Donato
Marcus Ace Gaitan
Marih Jomoc
Kristine Angela Caguiat
Gine Garcia
Mia Baylon
Al Valencia
Michelle Matanguihan
Danesa Sotomayor Pulido
John Carlo Martinez
Jan Maureen Ariota
Liza Margaret Caraos
Carla Chavez
Demirene Hentoloro
Arthel Espiritu Santo
Arvin Joseph De Leon
Beejey Jarabe
Jobelyn Estrella
Arvin Bajar
Maan Sestona
John Christian Mateo
Nerissa Anne Palo
Diana Hilario
Lady Joan Cabilino
Trish Teodosio
Nairie Solante
Johanna Perez
Cristien Angel Mae Bernabe
Gene Reinier Nieto
Christine Joyce Sapoco
Kaye Peña
John Padua
Khyle Zybille De Leon
Greg Canillas Reyes
Mehjebin Khan
Dagami Padillo
Nina Stephanie Tanawit
Christian Cachola Chrp
Benilda Diaz
Yohan Nicole Aroja
Julius Lee Bacani
Angelicca Sadanguel
Avi O
Raul Badon
Cyril Garcia
Jason Palinis
Efren Flores
Mary Joy Zamudio
James Topacio
Grace Ysabelle Pascual
Gealyn Pafin
Mitche Ajesta
Katrina Leyva
Archie Laranang
Aloicius Justine Kochensparger

In [14]:
gender_api_key = os.environ['GENDER_API_KEY']
profiles_dump['gender'] = profiles_dump[['conn_name', 'gender']].apply(assign_gender, axis=1, args=(gender_api_key,))

{'name': 'Rizziane Frago', 'q': 'Rizziane Frago', 'gender': 'null', 'country': 'null', 'total_names': 0, 'probability': 0, 'status': True, 'duration': '0.05s', 'used_credits': 1, 'remaining_credits': 199, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 11:59:44 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'angelica', 'q': 'Angelica Marie Wida', 'gender': 'female', 'total_names': 10407, 'probability': 100, 'country': 'US', 'status': True, 'duration': '0.04s', 'used_credits': 1, 'remaining_credits': 198, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 11:59:45 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'tina', 'q': 'Tina Caluya', 'gender': 'female', 'total_names': 19662, 'probability': 100, 'country': 'US', 'status': True, 'duration': '0.05s', 'used_credits': 1, 'remaining_credits': 197, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 11:59:46 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'elaine', 'q': 'Elaine Villa Balatero', 'gender': 'female', 'total_names': 14343, 'probability': 99, 'country': 'BR', 'status': True, 'duration': '0.05s', 'used_credits': 1, 'remaining_credits': 196, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 11:59:47 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'kristelle', 'q': 'Kristelle Ann Villalobos', 'gender': 'female', 'total_names': 114, 'probability': 99, 'country': 'PH', 'status': True, 'duration': '0.06s', 'used_credits': 1, 'remaining_credits': 195, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 11:59:48 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'angel', 'q': 'Angel Amosin', 'gender': 'male', 'total_names': 29178, 'probability': 63, 'country': 'US', 'status': True, 'duration': '0.05s', 'used_credits': 1, 'remaining_credits': 194, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 11:59:49 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'angely', 'q': 'Angely May Parel', 'gender': 'female', 'total_names': 162, 'probability': 98, 'country': 'US', 'status': True, 'duration': '0.05s', 'used_credits': 1, 'remaining_credits': 193, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 11:59:51 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'dhea', 'q': 'Dhea Pineda', 'gender': 'female', 'total_names': 1866, 'probability': 95, 'country': 'ID', 'status': True, 'duration': '0.05s', 'used_credits': 1, 'remaining_credits': 192, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 11:59:52 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'karina', 'q': 'Karina Manzanilla', 'gender': 'female', 'total_names': 25840, 'probability': 99, 'country': 'BR', 'status': True, 'duration': '0.08s', 'used_credits': 1, 'remaining_credits': 191, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 11:59:53 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'kristine', 'q': 'Kristine Obsioma', 'gender': 'female', 'total_names': 6601, 'probability': 100, 'country': 'US', 'status': True, 'duration': '0.08s', 'used_credits': 1, 'remaining_credits': 190, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 11:59:54 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'joemari', 'q': 'Joemari Rios', 'gender': 'male', 'total_names': 16, 'probability': 94, 'country': 'PH', 'status': True, 'duration': '0.08s', 'used_credits': 1, 'remaining_credits': 189, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 11:59:55 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'angelika', 'q': 'Angelika Barriga', 'gender': 'female', 'total_names': 1232, 'probability': 99, 'country': 'US', 'status': True, 'duration': '0.06s', 'used_credits': 1, 'remaining_credits': 188, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 11:59:56 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'jerrome', 'q': 'Jerrome Alcarmen', 'gender': 'male', 'total_names': 8, 'probability': 100, 'country': 'US', 'status': True, 'duration': '0.06s', 'used_credits': 1, 'remaining_credits': 187, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 11:59:57 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'maria', 'q': 'Maria Althea Espinosa', 'gender': 'female', 'total_names': 139304, 'probability': 99, 'country': 'BR', 'status': True, 'duration': '0.05s', 'used_credits': 1, 'remaining_credits': 186, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 11:59:58 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'oliver', 'q': 'Oliver Gabuna', 'gender': 'male', 'total_names': 9261, 'probability': 99, 'country': 'US', 'status': True, 'duration': '0.06s', 'used_credits': 1, 'remaining_credits': 185, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 11:59:59 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'mae', 'q': 'Mae Mira', 'gender': 'female', 'total_names': 2491, 'probability': 97, 'country': 'PH', 'status': True, 'duration': '0.05s', 'used_credits': 1, 'remaining_credits': 184, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 12:00:01 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'megan', 'q': 'Megan Rivera', 'gender': 'female', 'total_names': 29208, 'probability': 100, 'country': 'US', 'status': True, 'duration': '0.09s', 'used_credits': 1, 'remaining_credits': 183, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 12:00:02 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'mary', 'q': 'Mary Andrea Jugo', 'gender': 'female', 'total_names': 47102, 'probability': 99, 'country': 'US', 'status': True, 'duration': '0.07s', 'used_credits': 1, 'remaining_credits': 182, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 12:00:03 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'cheska', 'q': 'Cheska Tolosa', 'gender': 'female', 'total_names': 360, 'probability': 100, 'country': 'PH', 'status': True, 'duration': '0.06s', 'used_credits': 1, 'remaining_credits': 181, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 12:00:04 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'zhaira', 'q': 'Zhaira Andrea Manglo', 'gender': 'female', 'total_names': 17, 'probability': 94, 'country': 'PH', 'status': True, 'duration': '0.05s', 'used_credits': 1, 'remaining_credits': 180, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 12:00:05 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'zoan', 'q': 'Zoan Cris Acaso', 'gender': 'male', 'total_names': 12, 'probability': 67, 'country': 'ID', 'status': True, 'duration': '0.06s', 'used_credits': 1, 'remaining_credits': 179, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 12:00:06 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'jayson', 'q': 'Jayson Lugtu', 'gender': 'male', 'total_names': 2696, 'probability': 100, 'country': 'US', 'status': True, 'duration': '0.05s', 'used_credits': 1, 'remaining_credits': 178, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 12:00:07 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'Ricamay Ballad', 'q': 'Ricamay Ballad', 'gender': 'null', 'country': 'null', 'total_names': 0, 'probability': 0, 'status': True, 'duration': '0.05s', 'used_credits': 1, 'remaining_credits': 177, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 12:00:08 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'marvic', 'q': 'Marvic Marbb Calindro', 'gender': 'male', 'total_names': 64, 'probability': 73, 'country': 'PH', 'status': True, 'duration': '0.05s', 'used_credits': 1, 'remaining_credits': 176, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 12:00:09 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'veronica', 'q': 'Veronica De Leon', 'gender': 'female', 'total_names': 19056, 'probability': 100, 'country': 'US', 'status': True, 'duration': '0.05s', 'used_credits': 1, 'remaining_credits': 175, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 12:00:11 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'rodny', 'q': 'Rodny Selorio', 'gender': 'male', 'total_names': 47, 'probability': 100, 'country': 'US', 'status': True, 'duration': '0.05s', 'used_credits': 1, 'remaining_credits': 174, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 12:00:12 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'madelaine', 'q': 'Madelaine Ann Bengero', 'gender': 'female', 'total_names': 241, 'probability': 99, 'country': 'US', 'status': True, 'duration': '0.05s', 'used_credits': 1, 'remaining_credits': 173, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 12:00:13 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'anne', 'q': 'Anne Mariano', 'gender': 'female', 'total_names': 20191, 'probability': 99, 'country': 'US', 'status': True, 'duration': '0.07s', 'used_credits': 1, 'remaining_credits': 172, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 12:00:14 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'mary', 'q': 'Mary Lou Gobrin', 'gender': 'female', 'total_names': 47102, 'probability': 99, 'country': 'US', 'status': True, 'duration': '0.07s', 'used_credits': 1, 'remaining_credits': 171, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 12:00:15 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'glaiza', 'q': 'Glaiza Español', 'gender': 'female', 'total_names': 261, 'probability': 100, 'country': 'PH', 'status': True, 'duration': '0.07s', 'used_credits': 1, 'remaining_credits': 170, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 12:00:16 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'micol', 'q': 'Micol Maglalang', 'gender': 'female', 'total_names': 164, 'probability': 97, 'country': 'IT', 'status': True, 'duration': '0.07s', 'used_credits': 1, 'remaining_credits': 169, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 12:00:17 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'Rochemey Ortiga', 'q': 'Rochemey Ortiga', 'gender': 'null', 'country': 'null', 'total_names': 0, 'probability': 0, 'status': True, 'duration': '0.08s', 'used_credits': 1, 'remaining_credits': 168, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 12:00:18 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'jenny', 'q': 'Jenny Magsino', 'gender': 'female', 'total_names': 23383, 'probability': 99, 'country': 'US', 'status': True, 'duration': '0.07s', 'used_credits': 1, 'remaining_credits': 167, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 12:00:19 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'francis', 'q': 'Francis Mah', 'gender': 'male', 'total_names': 8191, 'probability': 88, 'country': 'US', 'status': True, 'duration': '0.05s', 'used_credits': 1, 'remaining_credits': 166, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 12:00:21 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'yhing', 'q': 'Yhing Miranda Manundo', 'gender': 'female', 'total_names': 31, 'probability': 100, 'country': 'TH', 'status': True, 'duration': '0.07s', 'used_credits': 1, 'remaining_credits': 165, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 12:00:22 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}
{'name': 'Rhuskine Dimla', 'q': 'Rhuskine Dimla', 'gender': 'null', 'country': 'null', 'total_names': 0, 'probability': 0, 'status': True, 'duration': '0.05s', 'used_credits': 1, 'remaining_credits': 164, 'expires': 1703721600, 'server': 'genderapi.io'}
{'Date': 'Wed, 27 Dec 2023 12:00:23 GMT', 'Server': 'Apache', 'Access-Control-Allow-Origin': '*', 'Content-Encoding': 'gzip', 'Vary': 'Accept-Encoding', 'Keep-Alive': 'timeout=5, max=100', 'Connection': 'Keep-Alive', 'Transfer-Encoding': 'chunked', 'Content-Type': 'application/json; charset=UTF-8'}

In [15]:
profiles_dump['salutation'] = profiles_dump['gender'].apply(lambda gender: 'Ms.' if gender == 'female' else 'Sir.' if gender == 'male' else '')

In [16]:
profiles_dump

,conn_link,conn_name,gender,salutation,email,mobile_no,company_name
0,https://www.linkedin.com/in/rmbf2222/,Rizziane Frago,null,,NaN,0.0,NaN
1,https://www.linkedin.com/in/angelica-marie-wid...,Angelica Marie Wida,female,Ms.,NaN,0.0,NaN
2,https://www.linkedin.com/in/tina-caluya-9b917a...,Tina Caluya,female,Ms.,NaN,0.0,NaN
3,https://www.linkedin.com/in/elainevilla/,Elaine Villa Balatero,female,Ms.,NaN,0.0,NaN
4,https://www.linkedin.com/in/kristelle-ann-vill...,Kristelle Ann Villalobos,female,Ms.,NaN,0.0,NaN
...,...,...,...,...,...,...,...
458,https://www.linkedin.com/in/gealynpafin/,Gealyn Pafin,NaN,,NaN,0.0,NaN
459,https://www.linkedin.com/in/mitche-ajesta-rpm-...,Mitche Ajesta,NaN,,NaN,0.0,NaN
460,https://www.linkedin.com/in/katrina-leyva-997b...,Katrina Leyva,NaN,,NaN,0.0,NaN
461,https://www.linkedin.com/in/archie-laranang-54...,Archie Laranang,NaN,,NaN,0.0,NaN
462,https://www.linkedin.com/in/aloicius-justine-k...,Aloicius Justine Kochensparger,NaN,,NaN,0.0,NaN

In [17]:
view_rows(profiles_dump, 'gender')

null
female
female
female
female
male
female
female
female
female
male
female
male
female
male
female
female
female
female
female
male
male
null
male
female
male
female
female
female
female
female
null
female
male
female
null
female
female
null
male
female
female
male
female
male
female
female
female
male
female
female
male
female
male
female
male
female
female
male
female
female
female
female
female
female
male
female
female
female
female
male
male
female
male
female
female
male
female
null
male
male
female
male
male
null
female
female
male
male
female
male
male
female
male
female
male
female
female
male
female
male
female
male
male
female
null
female
female
female
male
female
male
female
female
female
null
male
female
female
null
female
female
male
female
female
female
female
male
female
male
female
male
female
female
male
male
female
female
male
female
female
female
male
female
male
female
male
female
male
male
female
null
male
female
male
female
male
male
male
female
female
male
female
male
female
female
female
female
female
female
female
female
male
female
female
null
female
male
female
female
female
female
male
male
male
female
male
null
male
female
male
male
female
male
female
male
male
female
female
female
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan

In [18]:
view_rows(profiles_dump, 'salutation')

Ms.
Ms.
Ms.
Ms.
Sir.
Ms.
Ms.
Ms.
Ms.
Sir.
Ms.
Sir.
Ms.
Sir.
Ms.
Ms.
Ms.
Ms.
Ms.
Sir.
Sir.

Sir.
Ms.
Sir.
Ms.
Ms.
Ms.
Ms.
Ms.

Ms.
Sir.
Ms.

Ms.
Ms.

Sir.
Ms.
Ms.
Sir.
Ms.
Sir.
Ms.
Ms.
Ms.
Sir.
Ms.
Ms.
Sir.
Ms.
Sir.
Ms.
Sir.
Ms.
Ms.
Sir.
Ms.
Ms.
Ms.
Ms.
Ms.
Ms.
Sir.
Ms.
Ms.
Ms.
Ms.
Sir.
Sir.
Ms.
Sir.
Ms.
Ms.
Sir.
Ms.

Sir.
Sir.
Ms.
Sir.
Sir.

Ms.
Ms.
Sir.
Sir.
Ms.
Sir.
Sir.
Ms.
Sir.
Ms.
Sir.
Ms.
Ms.
Sir.
Ms.
Sir.
Ms.
Sir.
Sir.
Ms.

Ms.
Ms.
Ms.
Sir.
Ms.
Sir.
Ms.
Ms.
Ms.

Sir.
Ms.
Ms.

Ms.
Ms.
Sir.
Ms.
Ms.
Ms.
Ms.
Sir.
Ms.
Sir.
Ms.
Sir.
Ms.
Ms.
Sir.
Sir.
Ms.
Ms.
Sir.
Ms.
Ms.
Ms.
Sir.
Ms.
Sir.
Ms.
Sir.
Ms.
Sir.
Sir.
Ms.

Sir.
Ms.
Sir.
Ms.
Sir.
Sir.
Sir.
Ms.
Ms.
Sir.
Ms.
Sir.
Ms.
Ms.
Ms.
Ms.
Ms.
Ms.
Ms.
Ms.
Sir.
Ms.
Ms.

Ms.
Sir.
Ms.
Ms.
Ms.
Ms.
Sir.
Sir.
Sir.
Ms.
Sir.

Sir.
Ms.
Sir.
Sir.
Ms.
Sir.
Ms.
Sir.
Sir.
Ms.
Ms.
Ms.

In [19]:
profiles_dump.to_csv('../documents/profiles_dump_B.csv')